import { useState } from 'react'
import { Bell, Copy, History, Plus, Trash2, Workflow } from 'lucide-react'
import { usePlatform, makePlatformId } from '../platform'
import { useAuth } from '../auth'
import { actionLabels, nextRunFor, triggerLabels } from '../automationEngine'
import type { AutomationRule } from '../platformTypes'
import { AutomationBuilder } from '../components/AutomationBuilder'
import { Badge, Button, EmptyState, PageHeader, Tabs } from '../components/UI'

function when(value?:string){return value?new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'—'}

export function Automations(){
  const {data,ready,loadError,addRecord,updateRecord,removeRecord}=usePlatform(),{user}=useAuth()
  const [tab,setTab]=useState<'Rules'|'History'|'Notifications'>('Rules')
  const [editing,setEditing]=useState<AutomationRule|null|undefined>(undefined)
  const [error,setError]=useState('')
  const save=(rule:AutomationRule)=>{try{if(data.automations.some((item)=>item.id===rule.id))updateRecord('automations',rule.id,{...rule,nextRun:nextRunFor(rule)});else addRecord('automations',{...rule,nextRun:nextRunFor(rule)});setEditing(undefined);setError('')}catch(caught){setError(caught instanceof Error?caught.message:'The automation could not be saved.')}}
  const duplicate=(rule:AutomationRule)=>addRecord('automations',{...structuredClone(rule),id:makePlatformId('auto'),name:`${rule.name} copy`,active:false,createdAt:new Date().toISOString(),owner:user?.name??rule.owner,lastRun:undefined,nextRun:undefined,runs:0,error:undefined})
  const remove=(rule:AutomationRule)=>{if(window.confirm(`Delete “${rule.name}”? Its previous runs will remain in history.`))removeRecord('automations',rule.id)}
  return <div><PageHeader eyebrow="Manage" title="Automations" description="Build CRM workflows using WHEN → IF → THEN. Runs are recorded and duplicate events are ignored." actions={<Button icon={Plus} disabled={!ready} onClick={()=>setEditing(null)}>New automation</Button>}/>
    <section className="platform-summary"><article><span>Active automations</span><strong>{data.automations.filter((item)=>item.active).length}</strong></article><article><span>Successful runs</span><strong>{data.automationRuns.filter((item)=>item.status==='success').length}</strong></article><article><span>Failures</span><strong>{data.automationRuns.filter((item)=>item.status==='failed').length}</strong></article><article><span>Next scheduled run</span><strong className="automation-next-summary">{data.automations.map((item)=>nextRunFor(item)).filter(Boolean).sort()[0]?when(data.automations.map((item)=>nextRunFor(item)).filter(Boolean).sort()[0]):'None scheduled'}</strong></article></section>
    <Tabs items={['Rules','History','Notifications']} active={tab} onChange={setTab}/>
    {!ready&&!loadError&&<p className="automation-state" role="status">Loading destination automations…</p>}{loadError&&<p className="form-error" role="alert">{loadError}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
    {tab==='Rules'&&<section className="panel platform-panel"><header><div><h2>Workflow rules</h2><p>Rules are scoped to this destination. Scheduled rules run when the CRM is open.</p></div></header>{!data.automations.length?<EmptyState icon={Workflow} title="No automations yet" description="Create a rule to respond to CRM changes or run on a schedule."/>:<div className="automation-list">{data.automations.map((rule)=><article className="automation-card" key={rule.id}><header><div><Badge tone={rule.active?'green':'grey'}>{rule.active?'Active':'Inactive'}</Badge><h3>{rule.name}</h3><p>{rule.description||'No description'}</p></div><button className={`switch ${rule.active?'on':''}`} aria-pressed={rule.active} aria-label={`${rule.active?'Deactivate':'Activate'} ${rule.name}`} onClick={()=>updateRecord('automations',rule.id,{active:!rule.active,nextRun:nextRunFor({...rule,active:!rule.active})})}><span/></button></header><div className="automation-flow"><span><small>WHEN</small>{triggerLabels[rule.trigger]??rule.trigger}</span><b>→</b><span><small>IF</small>{rule.conditions.length?rule.conditions.map((item)=>`${item.field.replaceAll('_',' ')} ${item.operator.replaceAll('_',' ')} ${item.value}`).join('; '):'Every matching record'}</span><b>→</b><span><small>THEN</small>{rule.actions.map((item)=>`${actionLabels[item.type]??item.type}: ${item.value}`).join('; ')}</span></div><div className="automation-meta"><span>Owner: {rule.owner}</span><span>Created: {when(rule.createdAt)}</span><span>Last run: {when(rule.lastRun)}</span><span>Next run: {when(nextRunFor(rule))}</span><span>Runs: {rule.runs}</span></div><footer><div className="automation-card-actions"><Button size="sm" variant="secondary" onClick={()=>setEditing(rule)}>Edit</Button><Button size="sm" variant="secondary" icon={Copy} onClick={()=>duplicate(rule)}>Duplicate</Button><Button size="sm" variant="ghost" icon={Trash2} onClick={()=>remove(rule)}>Delete</Button></div></footer>{rule.error&&<p className="automation-error" role="alert">Last error: {rule.error}</p>}</article>)}</div>}</section>}
    {tab==='History'&&<section className="panel platform-panel"><header><div><h2>Automation activity</h2><p>Every attempted run, affected record, action and error.</p></div></header>{!data.automationRuns.length?<EmptyState icon={History} title="No runs yet" description="Run history will appear when a CRM event or scheduled rule matches."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Date / time</th><th>Automation</th><th>Record</th><th>Trigger</th><th>Actions</th><th>Result</th></tr></thead><tbody>{data.automationRuns.map((run)=><tr key={run.id}><td>{when(run.startedAt)}</td><td><strong>{run.ruleName}</strong></td><td>{run.recordLabel}<small>{run.recordId}</small></td><td>{triggerLabels[run.trigger]??run.trigger}</td><td>{run.actions.length?run.actions.join(' · '):'None'}{run.error&&<small className="automation-history-error">{run.error}</small>}</td><td><Badge tone={run.status==='success'?'green':run.status==='failed'?'red':'grey'}>{run.status}</Badge></td></tr>)}</tbody></table></div>}</section>}
    {tab==='Notifications'&&<section className="panel platform-panel"><header><div><h2>CRM notifications</h2><p>Internal notices produced by automation actions.</p></div></header>{!data.automationNotifications.length?<EmptyState icon={Bell} title="No automation notifications" description="Choose “Notify CRM user” in a rule to create one."/>:<div className="card-list">{data.automationNotifications.map((item)=><article className="platform-row" key={item.id}><div><strong>{item.title}</strong><p>{item.detail}</p><small>{item.user} · {when(item.createdAt)}</small></div><Badge tone={item.read?'grey':'blue'}>{item.read?'Read':'New'}</Badge>{!item.read&&<Button size="sm" variant="secondary" onClick={()=>updateRecord('automationNotifications',item.id,{read:true})}>Mark read</Button>}</article>)}</div>}</section>}
    {editing!==undefined&&<AutomationBuilder rule={editing??undefined} onClose={()=>setEditing(undefined)} onSave={save}/>}</div>
}
