import { useEffect, useMemo, useState } from 'react'
import { Copy, Mail, Pencil, Plus, Send, Trash2 } from 'lucide-react'
import { supabase, useAuth } from '../auth'
import { useCRM } from '../store'
import { makePlatformId, usePlatform } from '../platform'
import { tenant } from '../tenant'
import type { CommunicationAudience, CommunicationPreference, CommunicationRecord, CommunicationTemplate, CommunicationType } from '../platformTypes'
import { audienceFields, communicationTypes, deliveryTotals, emptyAudience, renderCommunication, resolveAudience } from '../communications'
import { Badge, Button, EmptyState, Field, Modal, PageHeader, Tabs } from '../components/UI'
import { formatDate } from '../utils'

type Tab='Communications'|'Templates'|'Preferences'
type Job={id:string;payload:CommunicationRecord;status:string;scheduled_at:string|null;sent_at:string|null;error:string|null}
type Receipt={communication_id:string;contact_id:string;organisation_id:string|null;email:string;status:string;provider_id:string|null;sent_at:string|null;delivered_at:string|null;unsubscribed_at:string|null;opens:number;clicks:number;error:string|null}
const preferenceKeys=[['service','Member / service'],['marketing','Marketing opt-in'],['trade','Travel trade'],['businessEvents','Business events'],['prMedia','PR / media'],['events','Events'],['research','Research']] as const

export function Communications(){
  const {data:crm}=useCRM();const {data,ready,addRecord,updateRecord,removeRecord}=usePlatform();const {user}=useAuth()
  const [tab,setTab]=useState<Tab>('Communications');const [editing,setEditing]=useState<CommunicationRecord|null>(null);const [editingTemplate,setEditingTemplate]=useState<CommunicationTemplate|null>(null);const [jobs,setJobs]=useState<Job[]>([]);const [receipts,setReceipts]=useState<Receipt[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(Boolean(supabase))
  useEffect(()=>{if(!supabase||!user||!ready)return;let active=true;const refresh=async()=>{const [jobResult,receiptResult]=await Promise.all([supabase!.from('communication_jobs').select('id,payload,status,scheduled_at,sent_at,error').eq('tenant_id',tenant.id),supabase!.from('communication_deliveries').select('communication_id,contact_id,organisation_id,email,status,provider_id,sent_at,delivered_at,unsubscribed_at,opens,clicks,error').eq('tenant_id',tenant.id)]);if(!active)return;if(jobResult.error||receiptResult.error)setError(jobResult.error?.message??receiptResult.error?.message??'Delivery history could not load');else{setJobs((jobResult.data??[]) as Job[]);setReceipts((receiptResult.data??[]) as Receipt[])}setLoading(false)};void refresh();const timer=window.setInterval(()=>void refresh(),15000);return()=>{active=false;window.clearInterval(timer)}},[user,ready])
  const records=useMemo(()=>{const byId=new Map(data.communications.filter((item)=>item.id!=='comm-001').map((item)=>[item.id,item]));for(const job of jobs){const prior=byId.get(job.id);const deliveryRows=receipts.filter((row)=>row.communication_id===job.id);byId.set(job.id,{...job.payload,...prior,status:job.status as CommunicationRecord['status'],scheduledAt:job.scheduled_at??undefined,sentAt:job.sent_at??undefined,error:job.error??undefined,recipientCount:deliveryRows.length||job.payload.recipientCount,recipients:deliveryRows.map((row)=>({contactId:row.contact_id,organisationId:row.organisation_id??undefined,email:row.email,status:row.status as NonNullable<CommunicationRecord['recipients']>[number]['status'],providerId:row.provider_id??undefined,sentAt:row.sent_at??undefined,deliveredAt:row.delivered_at??undefined,unsubscribedAt:row.unsubscribed_at??undefined,opens:row.opens,clicks:row.clicks,error:row.error??undefined}))})}return [...byId.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))},[data.communications,jobs,receipts])
  const save=(record:CommunicationRecord)=>{if(data.communications.some((item)=>item.id===record.id))updateRecord('communications',record.id,record);else addRecord('communications',record);setEditing(null);setError('')}
  const dispatch=async(record:CommunicationRecord,action:'send'|'schedule'|'test',testEmail?:string)=>{if(!supabase){setError('Connect Supabase and configure an email provider before sending. The draft was not sent.');return}setBusy(true);setError('');try{const {data:response,error:failure}=await supabase.functions.invoke('dispatch-communications',{body:{tenantId:tenant.id,record,action,testEmail}});if(failure||response?.error)throw new Error(response?.error??failure?.message??'The request failed');if(action!=='test'){const status=action==='schedule'?'Scheduled':'Sending';save({...record,status});setJobs((current)=>[{id:record.id,payload:record,status,scheduled_at:record.scheduledAt??null,sent_at:null,error:null},...current.filter((item)=>item.id!==record.id)])}else updateRecord('communications',record.id,{testSentAt:new Date().toISOString()});setEditing(null)}catch(cause){setError(cause instanceof Error?cause.message:'Delivery request failed. Nothing was marked sent.')}finally{setBusy(false)}}
  const savePreference=(contactId:string,changes:Partial<CommunicationPreference>)=>{const current=data.communicationPreferences.find((item)=>item.contactId===contactId);if(current)updateRecord('communicationPreferences',current.id,changes);else addRecord('communicationPreferences',{id:makePlatformId('pref'),contactId,service:true,marketing:false,trade:false,businessEvents:false,prMedia:false,events:false,research:false,unsubscribed:false,preferredEmail:'',lawfulBasis:'Not recorded',note:'',...changes})}
  return <div><PageHeader eyebrow="Workspace" title="Communications" description="Create, target and track email communications across your destination." actions={<Button icon={Plus} onClick={()=>setEditing(blankRecord(user?.name??''))}>New communication</Button>}/><Tabs items={['Communications','Templates','Preferences']} active={tab} onChange={setTab}/>
    {error&&<p className="form-note" role="alert">{error}</p>}
    {tab==='Communications'&&<section className="panel platform-panel"><header><div><h2>Communication history</h2><p>Provider acceptance and delivery are tracked separately. Open and click figures appear only when reported by the provider.</p></div></header>{loading?<p role="status">Loading communications…</p>:records.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Subject / title</th><th>Type</th><th>Audience</th><th>Status</th><th>Created by / date</th><th>Scheduled / sent</th><th>Delivered</th><th>Opens / clicks</th><th>Actions</th></tr></thead><tbody>{records.map((item)=>{const totals=deliveryTotals(item);const submitted=jobs.some((job)=>job.id===item.id);return <tr key={item.id}><td><strong>{item.subject}</strong><small>{item.name}</small>{item.error&&<small role="alert">{item.error}</small>}</td><td>{item.type??'Email campaign'}</td><td>{item.recipientCount} contacts</td><td><Badge>{item.status==='Queued'?'Draft':item.status}</Badge></td><td>{item.createdBy??'Unknown'}<small>{formatDate(item.createdAt)}</small></td><td>{item.scheduledAt?`Scheduled ${formatDate(item.scheduledAt)}`:item.sentAt?`Sent ${formatDate(item.sentAt)}`:'—'}</td><td>{totals.delivered}{totals.bounced>0&&<small>{totals.bounced} bounced</small>}</td><td>{totals.opens} / {totals.clicks}</td><td><div className="event-row-actions">{!submitted&&['Draft','Queued'].includes(item.status)&&<><button className="icon-button" aria-label={`Edit ${item.name}`} onClick={()=>setEditing(item)}><Pencil size={16}/></button><button className="icon-button danger" aria-label={`Delete ${item.name}`} onClick={()=>{if(confirm(`Delete ${item.name}?`))removeRecord('communications',item.id)}}><Trash2 size={16}/></button></>}<button className="icon-button" aria-label={`Duplicate ${item.name}`} onClick={()=>setEditing({...item,id:makePlatformId('comm'),name:`Copy of ${item.name}`,status:'Draft',createdAt:new Date().toISOString(),recipients:undefined,scheduledAt:undefined,sentAt:undefined})}><Copy size={16}/></button></div></td></tr>})}</tbody></table></div>:<EmptyState icon={Mail} title="No communications yet" description="Create a draft, choose a live CRM audience and review the recipient count before sending."/>}</section>}
    {tab==='Communications'&&records.some((item)=>deliveryTotals(item).unsubscribed>0)&&<section className="panel platform-panel"><header><div><h2>Unsubscribes by communication</h2><p>Recorded from recipient unsubscribe links.</p></div></header><div className="card-list">{records.filter((item)=>deliveryTotals(item).unsubscribed>0).map((item)=><div className="platform-row" key={item.id}><strong>{item.subject}</strong><Badge>{deliveryTotals(item).unsubscribed} unsubscribed</Badge></div>)}</div></section>}
    {tab==='Templates'&&<section className="panel platform-panel"><header><div><h2>Reusable templates</h2><p>Saved subject, sender and content can be reused in a new communication.</p></div><Button icon={Plus} onClick={()=>setEditingTemplate(blankTemplate())}>New template</Button></header>{data.communicationTemplates.length?<div className="module-card-grid">{data.communicationTemplates.map((item)=><article className="module-card" key={item.id}><Badge tone="purple">{item.category}</Badge><h3>{item.name}</h3><p>{item.subject}</p><small>{item.previewText}</small><footer><Button size="sm" variant="secondary" onClick={()=>setEditingTemplate(item)}>Edit</Button><Button size="sm" variant="ghost" onClick={()=>addRecord('communicationTemplates',{...item,id:makePlatformId('template'),name:`Copy of ${item.name}`,updatedAt:new Date().toISOString()})}>Duplicate</Button><Button size="sm" variant="danger" onClick={()=>{if(confirm(`Delete ${item.name}?`))removeRecord('communicationTemplates',item.id)}}>Delete</Button><Button size="sm" onClick={()=>setEditing({...blankRecord(user?.name??''),templateId:item.id,name:item.name,subject:item.subject,previewText:item.previewText,fromName:item.senderName,replyTo:item.replyTo,body:item.body,ctaLabel:item.ctaLabel,ctaUrl:item.ctaUrl})}>Use</Button></footer></article>)}</div>:<EmptyState icon={Mail} title="No templates yet" description="Save a reusable welcome, renewal, event or newsletter template."/>}</section>}
    {tab==='Preferences'&&<section className="panel platform-panel"><header><div><h2>Contact preferences</h2><p>Unsubscribed people are excluded from every send. Marketing sends require an explicit opt-in.</p></div></header><div className="table-scroll"><table className="data-table preference-table"><thead><tr><th>Contact</th>{preferenceKeys.map(([,label])=><th key={label}>{label}</th>)}<th>Unsubscribed</th><th>Preferred email</th></tr></thead><tbody>{crm.contacts.map((contact)=>{const pref=data.communicationPreferences.find((item)=>item.contactId===contact.id);return <tr key={contact.id}><td><strong>{contact.name}</strong><small>{contact.email}</small></td>{preferenceKeys.map(([key,label])=><td key={key}><input aria-label={`${contact.name} ${label}`} type="checkbox" checked={Boolean(pref?.[key]??(key==='service'))} onChange={(event)=>savePreference(contact.id,{[key]:event.target.checked})}/></td>)}<td><input aria-label={`${contact.name} Unsubscribed`} type="checkbox" checked={Boolean(pref?.unsubscribed)} onChange={(event)=>savePreference(contact.id,{unsubscribed:event.target.checked})}/></td><td><input aria-label={`${contact.name} preferred email`} type="email" value={pref?.preferredEmail??''} placeholder={contact.email} onChange={(event)=>savePreference(contact.id,{preferredEmail:event.target.value})}/></td></tr>})}</tbody></table></div></section>}
    {editing&&<Composer key={editing.id} record={editing} templates={data.communicationTemplates} busy={busy} onClose={()=>setEditing(null)} onSave={save} onDispatch={dispatch}/>}
    {editingTemplate&&<TemplateEditor key={editingTemplate.id} template={editingTemplate} onClose={()=>setEditingTemplate(null)} onSave={(item)=>{if(data.communicationTemplates.some((entry)=>entry.id===item.id))updateRecord('communicationTemplates',item.id,item);else addRecord('communicationTemplates',item);setEditingTemplate(null)}}/>}
  </div>
}
function blankRecord(owner:string):CommunicationRecord{return{id:makePlatformId('comm'),name:'',type:'Email campaign',subject:'',previewText:'',fromName:tenant.name,replyTo:tenant.contactEmail,body:'',status:'Draft',recipientCount:0,createdBy:owner,createdAt:new Date().toISOString(),audience:{...emptyAudience}}}
function blankTemplate():CommunicationTemplate{return{id:makePlatformId('template'),name:'',category:'Newsletter',subject:'',previewText:'',body:'',senderName:tenant.name,updatedAt:new Date().toISOString()}}
function localDateTime(value:string|undefined){if(!value)return'';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}

function Composer({record,templates,busy,onClose,onSave,onDispatch}:{record:CommunicationRecord;templates:CommunicationTemplate[];busy:boolean;onClose:()=>void;onSave:(item:CommunicationRecord)=>void;onDispatch:(item:CommunicationRecord,action:'send'|'schedule'|'test',testEmail?:string)=>void}){
  const {data:crm}=useCRM();const {data:platform}=usePlatform();const [draft,setDraft]=useState(record);const [testEmail,setTestEmail]=useState('');const [message,setMessage]=useState('')
  const audience=useMemo(()=>draft.audience??{...emptyAudience,mode:'selected' as const,contactIds:draft.contactId?[draft.contactId]:[]},[draft.audience,draft.contactId])
  const recipients=useMemo(()=>resolveAudience(audience,draft.type??'Email campaign',crm,platform),[audience,draft.type,crm,platform])
  const setAudience=(change:Partial<CommunicationAudience>)=>setDraft({...draft,audience:{...audience,...change}})
  const ready=Boolean(draft.name.trim()&&draft.subject.trim()&&draft.body.trim()&&draft.fromName?.trim()&&draft.replyTo?.trim()&&recipients.length)
  const prepared={...draft,recipientCount:recipients.length,recipients}
  return <Modal title={record.name?`Edit ${record.name}`:'New communication'} subtitle="Compose, choose a live audience, then save, test or submit to the delivery provider." onClose={onClose} width="lg"><form className="form-stack" onSubmit={(event)=>{event.preventDefault();onSave(prepared)}}>
    <div className="form-grid two"><Field label="Internal name"><input autoFocus required value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></Field><Field label="Type"><select value={draft.type??'Email campaign'} onChange={(event)=>setDraft({...draft,type:event.target.value as CommunicationType})}>{communicationTypes.map((type)=><option key={type}>{type}</option>)}</select></Field></div>
    <Field label="Template"><select value={draft.templateId??''} onChange={(event)=>{const item=templates.find((entry)=>entry.id===event.target.value);setDraft({...draft,templateId:item?.id,subject:item?.subject??draft.subject,previewText:item?.previewText??draft.previewText,fromName:item?.senderName??draft.fromName,replyTo:item?.replyTo??draft.replyTo,body:item?.body??draft.body,ctaLabel:item?.ctaLabel??draft.ctaLabel,ctaUrl:item?.ctaUrl??draft.ctaUrl})}}><option value="">No template</option>{templates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
    <Field label="Subject"><input required value={draft.subject} onChange={(event)=>setDraft({...draft,subject:event.target.value})}/></Field><Field label="Preview text"><input value={draft.previewText??''} onChange={(event)=>setDraft({...draft,previewText:event.target.value})}/></Field><div className="form-grid two"><Field label="From name"><input required value={draft.fromName??''} onChange={(event)=>setDraft({...draft,fromName:event.target.value})}/></Field><Field label="Reply-to"><input required type="email" value={draft.replyTo??''} onChange={(event)=>setDraft({...draft,replyTo:event.target.value})}/></Field></div>
    <Field label="Rich text content" hint="Use # Heading, **bold**, *italic*, or - list items. Blank lines separate paragraphs. Merge fields: {{first_name}}, {{organisation_name}}, {{membership_level}}, {{renewal_date}}."><textarea required rows={8} value={draft.body} onChange={(event)=>setDraft({...draft,body:event.target.value})}/></Field><div className="form-grid two"><Field label="CTA button label"><input value={draft.ctaLabel??''} onChange={(event)=>setDraft({...draft,ctaLabel:event.target.value})}/></Field><Field label="CTA link (HTTPS)"><input type="url" pattern="https://.*" value={draft.ctaUrl??''} onChange={(event)=>setDraft({...draft,ctaUrl:event.target.value})}/></Field></div>
    <section className="communication-preview" aria-label="Email preview"><strong>{draft.subject||'Subject preview'}</strong><small>{draft.previewText}</small><div dangerouslySetInnerHTML={{__html:renderCommunication(draft,crm.contacts.find((item)=>item.id===recipients[0]?.contactId)??{id:'preview',organisationId:'',name:'Alex Example',email:'',phone:'',jobTitle:'',roles:[]},crm.organisations.find((item)=>item.id===recipients[0]?.organisationId))}}/></section>
    <fieldset className="communication-audience"><legend>Audience</legend><div className="form-grid two"><Field label="Selection"><select value={audience.mode} onChange={(event)=>setAudience({mode:event.target.value as 'all'|'selected'})}><option value="all">All matching contacts</option><option value="selected">Selected contacts / organisations</option></select></Field><Field label="Add filter"><select value="" onChange={(event)=>{if(event.target.value)setAudience({filters:[...audience.filters,{field:event.target.value,value:''}]})}}><option value="">Choose a CRM field…</option>{audienceFields.map(([field,label])=><option value={field} key={field}>{label}</option>)}</select></Field></div>{audience.mode==='selected'&&<div className="form-grid two"><Field label="Organisations"><select multiple size={5} aria-label="Individual organisations" value={audience.organisationIds} onChange={(event)=>setAudience({organisationIds:Array.from(event.target.selectedOptions,(option)=>option.value)})}>{crm.organisations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Contacts"><select multiple size={5} aria-label="Individual contacts" value={audience.contactIds} onChange={(event)=>setAudience({contactIds:Array.from(event.target.selectedOptions,(option)=>option.value)})}>{crm.contacts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>}{audience.filters.map((filter,index)=><div className="form-grid two" key={`${filter.field}-${index}`}><Field label={audienceFields.find(([key])=>key===filter.field)?.[1]??filter.field}><input aria-label={`Filter ${index+1} value`} value={filter.value} onChange={(event)=>setAudience({filters:audience.filters.map((item,i)=>i===index?{...item,value:event.target.value}:item)})}/></Field><Button variant="ghost" onClick={()=>setAudience({filters:audience.filters.filter((_,i)=>i!==index)})}>Remove filter</Button></div>)}<p role="status"><strong>{recipients.length}</strong> eligible unique recipients now. Marketing requires opt-in; unsubscribed contacts are excluded.</p></fieldset>
    <div className="form-grid two"><Field label="Schedule date and time"><input type="datetime-local" value={localDateTime(draft.scheduledAt)} onChange={(event)=>setDraft({...draft,scheduledAt:event.target.value?new Date(event.target.value).toISOString():undefined})}/></Field><Field label="Test recipient"><input type="email" value={testEmail} onChange={(event)=>setTestEmail(event.target.value)} placeholder="you@example.com"/></Field></div>
    {message&&<p role="alert" className="form-note">{message}</p>}
    <div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save draft</Button><Button variant="secondary" disabled={!testEmail||!draft.subject||!draft.body||busy} onClick={()=>{onSave(prepared);onDispatch(prepared,'test',testEmail)}}>Test send</Button><Button variant="secondary" disabled={!ready||!draft.scheduledAt||busy} onClick={()=>{if(!draft.scheduledAt||new Date(draft.scheduledAt).getTime()<=Date.now())setMessage('Choose a future date');else onDispatch(prepared,'schedule')}}>Schedule</Button><Button icon={Send} disabled={!ready||busy} onClick={()=>{if(confirm(`Send to ${recipients.length} eligible contacts?`))onDispatch(prepared,'send')}}>Send</Button></div>
  </form></Modal>
}
function TemplateEditor({template,onClose,onSave}:{template:CommunicationTemplate;onClose:()=>void;onSave:(item:CommunicationTemplate)=>void}){const [draft,setDraft]=useState(template);return <Modal title="Communication template" onClose={onClose} width="lg"><form className="form-stack" onSubmit={(event)=>{event.preventDefault();onSave({...draft,updatedAt:new Date().toISOString()})}}><div className="form-grid two"><Field label="Name"><input required value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></Field><Field label="Category"><select value={draft.category} onChange={(event)=>setDraft({...draft,category:event.target.value})}>{['Welcome to membership','Renewal reminder','Invoice reminder','Event invitation','Opportunity invitation','Trade update','Newsletter'].map((item)=><option key={item}>{item}</option>)}</select></Field></div><Field label="Subject"><input required value={draft.subject} onChange={(event)=>setDraft({...draft,subject:event.target.value})}/></Field><Field label="Preview text"><input value={draft.previewText} onChange={(event)=>setDraft({...draft,previewText:event.target.value})}/></Field><div className="form-grid two"><Field label="From name"><input required value={draft.senderName} onChange={(event)=>setDraft({...draft,senderName:event.target.value})}/></Field><Field label="Reply-to"><input type="email" value={draft.replyTo??''} onChange={(event)=>setDraft({...draft,replyTo:event.target.value})}/></Field></div><Field label="Content"><textarea required rows={8} value={draft.body} onChange={(event)=>setDraft({...draft,body:event.target.value})}/></Field><div className="form-grid two"><Field label="CTA label"><input value={draft.ctaLabel??''} onChange={(event)=>setDraft({...draft,ctaLabel:event.target.value})}/></Field><Field label="CTA URL"><input type="url" value={draft.ctaUrl??''} onChange={(event)=>setDraft({...draft,ctaUrl:event.target.value})}/></Field></div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save template</Button></div></form></Modal>}
