import { Copy, Edit3, Eye, FileText, Plus, RotateCcw, Send, Search, Trash2, UploadCloud } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useCRM } from '../store'
import type { ContentPage } from '../types'
import { Badge, Button, Field, Modal, PageHeader } from '../components/UI'
import { imageLibrary } from '../siteData'

type PageDraft = Omit<ContentPage,'id'|'updatedAt'>
const blank:PageDraft={type:'Guide',title:'',slug:'',summary:'',body:'',image:'hero',status:'Draft',metaTitle:'',metaDescription:'',version:0}

export function Content(){
  const {data,createContentPage,updateContentPage,publishContentPage,discardContentDraft,deleteContentPage}=useCRM()
  const [query,setQuery]=useState('');const [type,setType]=useState('All');const [editing,setEditing]=useState<ContentPage|PageDraft|null>(null);const [error,setError]=useState('')
  const pages=useMemo(()=>data.contentPages.filter((page)=>(type==='All'||page.type===type)&&(!query||[page.title,page.summary,page.slug].join(' ').toLowerCase().includes(query.toLowerCase()))),[data.contentPages,query,type])
  const save=(event:FormEvent)=>{event.preventDefault();if(!editing)return;const duplicate=data.contentPages.some((page)=>page.slug===editing.slug&&(!('id'in editing)||page.id!==editing.id));if(duplicate){setError('That URL slug is already in use. Choose a unique slug.');return}if('id'in editing)updateContentPage(editing.id,editing);else createContentPage(editing);setEditing(null);setError('')}
  const duplicate=(page:ContentPage)=>{const copy:PageDraft={type:page.type,title:`${page.title} copy`,slug:`${page.slug}-copy-${Date.now().toString().slice(-4)}`,summary:page.summary,body:page.body,image:page.image,status:'Draft',metaTitle:page.metaTitle,metaDescription:page.metaDescription,version:0};const created=createContentPage(copy);setEditing(created)}
  const uploadImage=(file?:File)=>{if(!file||!editing)return;if(file.size>2*1024*1024){setError('Choose an image smaller than 2 MB.');return}const reader=new FileReader();reader.onload=()=>{setEditing((current)=>current?{...current,image:String(reader.result)}:current);setError('')};reader.onerror=()=>setError('The image could not be read.');reader.readAsDataURL(file)}
  const pageUrl=(page:Pick<ContentPage,'type'|'slug'>)=>`/${page.type==='Itinerary'?'itineraries':`${page.type.toLowerCase()}s`}/${page.slug}`

  return <div><PageHeader eyebrow="Website content" title="Guides, itineraries and trails" description="Every edit is saved as a private draft. Preview it, then publish when it is ready for visitors." actions={<Button icon={Plus} onClick={()=>setEditing({...blank})}>New page</Button>}/><section className="panel data-panel"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search content..."/></div><label className="select-wrap"><select aria-label="Filter content by type" value={type} onChange={(e)=>setType(e.target.value)}><option>All</option><option>Guide</option><option>Itinerary</option><option>Trail</option></select></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Page</th><th>Type</th><th>URL</th><th>Updated</th><th>Status</th><th/></tr></thead><tbody>{pages.map((page)=><tr key={page.id}><td><div className="org-cell"><FileText size={18}/><div><strong>{page.title}</strong><small>{page.summary}</small></div></div></td><td>{page.type}</td><td>{pageUrl(page)}</td><td>{page.updatedAt}</td><td><Badge>{page.status}</Badge>{page.publishedAt&&<small className="published-version">Live v{page.version??1}</small>}</td><td><div className="event-row-actions">{page.status!=='Published'&&<Button size="sm" icon={Send} onClick={()=>publishContentPage(page.id)}>Publish</Button>}<button className="icon-button" onClick={()=>window.open(`${pageUrl(page)}?preview=true`,'_blank','noopener,noreferrer')} aria-label={`Preview ${page.title}`} title="Preview draft"><Eye size={16}/></button>{page.status==='Draft changes'&&<button className="icon-button" onClick={()=>confirm(`Discard the draft changes to ${page.title}?`)&&discardContentDraft(page.id)} aria-label={`Discard draft changes to ${page.title}`} title="Discard draft"><RotateCcw size={16}/></button>}<button className="icon-button" onClick={()=>duplicate(page)} aria-label={`Duplicate ${page.title}`}><Copy size={16}/></button><button className="icon-button" onClick={()=>setEditing({...page})} aria-label={`Edit ${page.title}`}><Edit3 size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${page.title}?`)&&deleteContentPage(page.id)} aria-label={`Delete ${page.title}`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>
    {editing&&<Modal title={'id'in editing?`Edit ${editing.title}`:'New inspiration page'} subtitle="Saving creates a private draft. The live page will not change until you publish." onClose={()=>setEditing(null)}><form className="form-stack" onSubmit={save}><div className="form-grid two"><Field label="Type"><select value={editing.type} onChange={(e)=>setEditing({...editing,type:e.target.value as ContentPage['type']})}><option>Guide</option><option>Itinerary</option><option>Trail</option></select></Field><Field label="Publication"><div className="draft-state"><Badge>{editing.status}</Badge><span>{editing.published?'A previous version remains live':'Not yet live'}</span></div></Field></div><Field label="Title"><input required value={editing.title} onChange={(e)=>setEditing({...editing,title:e.target.value,slug:editing.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})}/></Field><Field label="URL slug"><input required value={editing.slug} onChange={(e)=>setEditing({...editing,slug:e.target.value})}/></Field><Field label="Header image"><select value={Object.hasOwn(imageLibrary,editing.image)?editing.image:'uploaded'} onChange={(e)=>e.target.value!=='uploaded'&&setEditing({...editing,image:e.target.value})}>{Object.keys(imageLibrary).map((item)=><option key={item}>{item}</option>)}{!Object.hasOwn(imageLibrary,editing.image)&&<option value="uploaded">Uploaded image</option>}</select></Field><label className="upload-zone compact"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event)=>uploadImage(event.target.files?.[0])}/><UploadCloud size={20}/><strong>Upload a header image</strong><span>JPG, PNG or WebP, up to 2 MB</span></label><Field label="Summary"><textarea required rows={3} value={editing.summary} onChange={(e)=>setEditing({...editing,summary:e.target.value})}/></Field><div className="form-grid two"><Field label="SEO title"><input maxLength={60} value={editing.metaTitle??''} onChange={(e)=>setEditing({...editing,metaTitle:e.target.value})}/></Field><Field label="SEO description"><textarea maxLength={160} rows={2} value={editing.metaDescription??''} onChange={(e)=>setEditing({...editing,metaDescription:e.target.value})}/></Field></div><Field label="Page content" hint="Separate sections with a blank line. Lines beginning with ## become section headings."><textarea required rows={9} value={editing.body} onChange={(e)=>setEditing({...editing,body:e.target.value})}/></Field>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit">Save draft</Button></div></form></Modal>}
  </div>
}
