import { Edit3, FileText, Plus, Search, Trash2 } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useCRM } from '../store'
import type { ContentPage } from '../types'
import { Badge, Button, Field, Modal, PageHeader } from '../components/UI'

const blank:Omit<ContentPage,'id'|'updatedAt'>={type:'Guide',title:'',slug:'',summary:'',body:'',image:'hero',status:'Draft'}
export function Content(){
  const {data,createContentPage,updateContentPage,deleteContentPage}=useCRM();const [query,setQuery]=useState('');const [type,setType]=useState('All');const [editing,setEditing]=useState<ContentPage|Omit<ContentPage,'id'|'updatedAt'>|null>(null)
  const pages=useMemo(()=>data.contentPages.filter((page)=>(type==='All'||page.type===type)&&(!query||[page.title,page.summary,page.slug].join(' ').toLowerCase().includes(query.toLowerCase()))),[data.contentPages,query,type])
  const save=(event:FormEvent)=>{event.preventDefault();if(!editing)return;if('id'in editing)updateContentPage(editing.id,editing);else createContentPage(editing);setEditing(null)}
  return <div><PageHeader eyebrow="Website content" title="Guides, itineraries and trails" description="Create and publish inspiration pages that feed the visitor website." actions={<Button icon={Plus} onClick={()=>setEditing({...blank})}>New page</Button>}/><section className="panel data-panel"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search content..."/></div><label className="select-wrap"><select value={type} onChange={(e)=>setType(e.target.value)}><option>All</option><option>Guide</option><option>Itinerary</option><option>Trail</option></select></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Page</th><th>Type</th><th>URL</th><th>Updated</th><th>Status</th><th/></tr></thead><tbody>{pages.map((page)=><tr key={page.id}><td><div className="org-cell"><FileText size={18}/><div><strong>{page.title}</strong><small>{page.summary}</small></div></div></td><td>{page.type}</td><td>/{page.type.toLowerCase()}s/{page.slug}</td><td>{page.updatedAt}</td><td><Badge>{page.status}</Badge></td><td><div className="event-row-actions"><button className="icon-button" onClick={()=>setEditing({...page})} aria-label={`Edit ${page.title}`}><Edit3 size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${page.title}?`)&&deleteContentPage(page.id)} aria-label={`Delete ${page.title}`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>
    {editing&&<Modal title={'id'in editing?`Edit ${editing.title}`:'New inspiration page'} subtitle="Published pages are available to the visitor website." onClose={()=>setEditing(null)}><form className="form-stack" onSubmit={save}><div className="form-grid two"><Field label="Type"><select value={editing.type} onChange={(e)=>setEditing({...editing,type:e.target.value as ContentPage['type']})}><option>Guide</option><option>Itinerary</option><option>Trail</option></select></Field><Field label="Status"><select value={editing.status} onChange={(e)=>setEditing({...editing,status:e.target.value as ContentPage['status']})}><option>Draft</option><option>Published</option></select></Field></div><Field label="Title"><input required value={editing.title} onChange={(e)=>setEditing({...editing,title:e.target.value,slug:editing.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})}/></Field><Field label="URL slug"><input required value={editing.slug} onChange={(e)=>setEditing({...editing,slug:e.target.value})}/></Field><Field label="Summary"><textarea required rows={3} value={editing.summary} onChange={(e)=>setEditing({...editing,summary:e.target.value})}/></Field><Field label="Page content"><textarea required rows={9} value={editing.body} onChange={(e)=>setEditing({...editing,body:e.target.value})}/></Field><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit">Save page</Button></div></form></Modal>}
  </div>
}
