import { ArrowRight, Building2, Check, CircleAlert, CircleDollarSign, ClipboardCheck, GripVertical, Handshake, PoundSterling, Settings2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useCRM } from '../store'
import type { Organisation, ViewKey } from '../types'
import { currency, dateLabel, formatDate } from '../utils'
import { Avatar, Button } from '../components/UI'
import { supabase, useAuth } from '../auth'

type WidgetId='active-members'|'membership-revenue'|'renewals'|'invoices'|'pipeline'|'tasks'|'approvals'
const DEFAULT_WIDGETS:WidgetId[]=['active-members','membership-revenue','renewals','invoices','pipeline','tasks','approvals']
const widgetNames:Record<WidgetId,string>={'active-members':'Active members','membership-revenue':'Membership revenue',renewals:'Upcoming renewals',invoices:'Outstanding and overdue invoices',pipeline:'Sales pipeline',tasks:'My tasks',approvals:'Items awaiting approval'}
function loadWidgets(userId:string){try{const saved=JSON.parse(localStorage.getItem(`vv-dashboard-${userId}`)??'[]') as string[];const valid=saved.filter((id):id is WidgetId=>id in widgetNames);return valid.length?valid:DEFAULT_WIDGETS}catch{return DEFAULT_WIDGETS}}

export function Dashboard({navigate,openOrganisation}:{navigate:(view:ViewKey)=>void;openOrganisation:(org:Organisation)=>void}){
  const {data,toggleTask}=useCRM();const {user}=useAuth();const [widgets,setWidgets]=useState<WidgetId[]>(()=>loadWidgets(user?.id??'default'));const [configure,setConfigure]=useState(false);const [saved,setSaved]=useState(false);const [dragging,setDragging]=useState<WidgetId|null>(null)
  const today=new Date();const todayIso=today.toISOString().slice(0,10);const limit=new Date(today);limit.setDate(limit.getDate()+60)
  const members=data.organisations.filter((org)=>['Active','Renewing'].includes(org.status)&&org.tier!=='Free Listing')
  const renewals=members.filter((org)=>org.renewalDate&&new Date(`${org.renewalDate}T12:00:00`)<=limit).sort((a,b)=>a.renewalDate.localeCompare(b.renewalDate))
  const invoices=data.invoices.filter((item)=>item.status==='Sent'||item.status==='Overdue');const overdue=invoices.filter((item)=>item.status==='Overdue')
  const pipeline=data.opportunities.filter((item)=>item.stage!=='Won'&&item.stage!=='Lost')
  const tasks=data.tasks.filter((task)=>!task.completed&&(task.assignee===user?.name||!task.assignee))
  const approvals=data.listings.filter((item)=>item.status==='In review').length+data.events.filter((item)=>item.status==='In review').length+data.submissions.filter((item)=>item.status==='New'&&(item.kind.includes('profile')||item.kind.includes('listing')||item.kind.includes('event'))).length
  useEffect(()=>{if(!supabase||!user)return;void supabase.from('user_preferences').select('dashboard_widgets').eq('user_id',user.id).eq('tenant_id',user.tenantId).maybeSingle().then(({data:preferences})=>{if(preferences?.dashboard_widgets){const valid=(preferences.dashboard_widgets as string[]).filter((id):id is WidgetId=>id in widgetNames);if(valid.length)setWidgets(valid)}})},[user])
  const saveLayout=()=>{localStorage.setItem(`vv-dashboard-${user?.id??'default'}`,JSON.stringify(widgets));if(supabase&&user)void supabase.from('user_preferences').upsert({user_id:user.id,tenant_id:user.tenantId,dashboard_widgets:widgets,updated_at:new Date().toISOString()},{onConflict:'user_id,tenant_id'});setSaved(true)}
  const dropOn=(target:WidgetId)=>{if(!dragging||dragging===target)return;setWidgets((current)=>{const next=current.filter((id)=>id!==dragging);next.splice(next.indexOf(target),0,dragging);return next});setDragging(null)}
  const toggle=(id:WidgetId)=>setWidgets((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id])
  const metric=(id:WidgetId)=>{
    if(id==='active-members')return {value:String(members.length),detail:'paid memberships currently active',icon:Building2,tone:'purple',view:'memberships' as ViewKey}
    if(id==='membership-revenue')return {value:currency.format(members.reduce((sum,item)=>sum+item.annualValue,0)),detail:'contracted annual membership fees; not cash received',icon:CircleDollarSign,tone:'green',view:'memberships' as ViewKey}
    if(id==='invoices')return {value:currency.format(invoices.reduce((sum,item)=>sum+item.total,0)),detail:`${invoices.length} outstanding · ${overdue.length} overdue`,icon:PoundSterling,tone:'coral',view:'billing' as ViewKey}
    if(id==='pipeline')return {value:currency.format(pipeline.reduce((sum,item)=>sum+item.value,0)),detail:`${pipeline.length} active opportunities; closed outcomes excluded`,icon:Handshake,tone:'amber',view:'pipeline' as ViewKey}
    return null
  }
  const render=(id:WidgetId)=>{const summary=metric(id);if(summary){const Icon=summary.icon;return <article className="dashboard-widget metric-widget"><div className="widget-top"><span className={`stat-icon ${summary.tone}`}><Icon size={19}/></span><GripVertical size={17}/></div><p>{widgetNames[id]}</p><h2>{summary.value}</h2><small>{summary.detail}</small><button className="widget-link" onClick={()=>navigate(summary.view)}>Open <ArrowRight size={13}/></button></article>}
    if(id==='renewals')return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>Upcoming renewals</h3><p>Due within 60 days · membership records</p></div><GripVertical size={17}/></div><div className="compact-table">{renewals.slice(0,5).map((org)=><button className="compact-row" key={org.id} onClick={()=>openOrganisation(org)}><Avatar name={org.name} colour={org.colour} size="sm"/><span className="compact-main"><strong>{org.name}</strong><small>{org.owner||'No owner assigned'}</small></span><span className="compact-date"><strong>{formatDate(org.renewalDate,{day:'numeric',month:'short'})}</strong><small>{org.nextAction||'Next action unknown'}</small></span></button>)}</div></article>
    if(id==='tasks')return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>My tasks</h3><p>Assigned, incomplete tasks</p></div><GripVertical size={17}/></div><div className="dashboard-tasks">{tasks.slice(0,5).map((task)=><div className="dashboard-task" key={task.id}><button className="task-check" onClick={()=>toggleTask(task.id)} aria-label={`Complete ${task.title}`}><Check size={13}/></button><div><strong>{task.title}</strong><span>{task.category}</span></div><small className={task.dueDate<todayIso?'overdue':''}>{dateLabel(task.dueDate)}</small></div>)}</div></article>
    return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>Items awaiting approval</h3><p>Listing, event and profile submissions</p></div><GripVertical size={17}/></div><div className="approval-summary"><ClipboardCheck size={24}/><strong>{approvals}</strong><span>changes need a staff decision</span></div><button className="widget-link" onClick={()=>navigate('inbox')}>Open approval queue <ArrowRight size={13}/></button></article>}
  const firstName=(user?.name??'there').split(' ')[0]
  return <div className="dashboard-page configurable-dashboard"><section className="dashboard-welcome"><div><span className="eyebrow">{new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:data.workspace.timezone}).format(today)}</span><h1>Good {today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening'}, {firstName}</h1><p>Your team’s membership, finance and publishing priorities.</p></div><Button icon={Settings2} onClick={()=>setConfigure(true)}>Customise dashboard</Button></section><section className="attention-strip"><div className="attention-title"><span><CircleAlert size={18}/></span><div><strong>Today’s focus</strong><small>Live records only; unknown values are not shown as zero</small></div></div><button onClick={()=>navigate('billing')}><strong>{overdue.length}</strong><span>overdue invoices</span><ArrowRight size={15}/></button><button onClick={()=>navigate('memberships')}><strong>{renewals.length}</strong><span>renewals within 60 days</span><ArrowRight size={15}/></button><button onClick={()=>navigate('inbox')}><strong>{approvals}</strong><span>awaiting approval</span><ArrowRight size={15}/></button></section><section className="dashboard-widget-grid">{widgets.map((id)=><div key={id} draggable onDragStart={()=>setDragging(id)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>dropOn(id)} className={metric(id)?'metric-slot':'panel-slot'}>{render(id)}</div>)}</section>{configure&&<div className="dashboard-config-overlay" onMouseDown={(e)=>e.target===e.currentTarget&&setConfigure(false)}><section className="dashboard-config"><header><div><h2>Customise your dashboard</h2><p>Choose and order the launch metrics your team uses each day.</p></div><button onClick={()=>setConfigure(false)} aria-label="Close dashboard settings"><X size={20}/></button></header><div className="widget-picker">{(Object.keys(widgetNames) as WidgetId[]).map((id)=><label key={id} className={widgets.includes(id)?'selected':''}><input type="checkbox" checked={widgets.includes(id)} onChange={()=>toggle(id)}/><span><Check size={13}/></span>{widgetNames[id]}</label>)}</div><footer><span>{saved?'Layout saved':''}</span><Button onClick={()=>{saveLayout();setConfigure(false)}}>Save layout</Button></footer></section></div>}</div>
}
