import {
  ArrowRight, Banknote, BedDouble, Building2, CalendarClock, Check, CircleAlert,
  CircleDollarSign, Eye, GripVertical, PoundSterling,
  Globe2, MousePointerClick, Settings2, Sparkles, Star, UserPlus, UsersRound, WalletCards, X,
} from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useCRM } from '../store'
import type { Organisation, ViewKey } from '../types'
import { currency, dateLabel, formatDate, timeAgo } from '../utils'
import { Avatar, Button } from '../components/UI'
import { supabase, useAuth } from '../auth'
import { engagementScore, usePlatform } from '../platform'

type WidgetId = 'active-members'|'new-members'|'membership-income'|'website-visitors'|'page-views'|'website-conversions'|'visitor-volume'|'visitor-spend'|'overnight-stays'|'pipeline'|'outstanding'|'bank-balance'|'member-risk'|'average-engagement'|'member-value'|'active-campaigns'|'automation-failures'|'member-tiers'|'review-trends'|'renewals'|'tasks'|'activity'
const DEFAULT_WIDGETS: WidgetId[] = ['active-members','new-members','membership-income','website-visitors','page-views','website-conversions','visitor-volume','visitor-spend','overnight-stays','pipeline','outstanding','bank-balance','member-tiers','review-trends','renewals','tasks','activity']
const widgetNames: Record<WidgetId,string> = {
  'active-members':'Active members','new-members':'New members','membership-income':'Membership income','website-visitors':'Website visitors','page-views':'Website page views','website-conversions':'Website conversions','visitor-volume':'Visitor volume','visitor-spend':'Visitor spend','overnight-stays':'Overnight stays','pipeline':'Open pipeline','outstanding':'Outstanding invoices','bank-balance':'Bank balance','member-risk':'Members at risk','average-engagement':'Average engagement score','member-value':'Member value delivered','active-campaigns':'Active campaigns','automation-failures':'Automation failures','member-tiers':'Members by tier','review-trends':'Visitor review trends','renewals':'Upcoming renewals','tasks':'My tasks','activity':'Recent activity'
}
const metricWidgets: WidgetId[] = ['active-members','new-members','membership-income','website-visitors','page-views','website-conversions','visitor-volume','visitor-spend','overnight-stays','pipeline','outstanding','bank-balance','member-risk','average-engagement','member-value','active-campaigns','automation-failures']

function loadWidgets(userId: string) { try { const saved=localStorage.getItem(`vv-dashboard-${userId}`); return saved ? JSON.parse(saved) as WidgetId[] : DEFAULT_WIDGETS } catch { return DEFAULT_WIDGETS } }

export function Dashboard({ navigate, openOrganisation }: { navigate: (view: ViewKey) => void; openOrganisation: (org: Organisation) => void }) {
  const { data, toggleTask } = useCRM(); const { user } = useAuth()
  const {data:platform}=usePlatform()
  const [widgets,setWidgets] = useState<WidgetId[]>(() => loadWidgets(user?.id ?? 'default'))
  const [configure,setConfigure] = useState(false); const [saved,setSaved] = useState(false); const [dragging,setDragging] = useState<WidgetId|null>(null)
  const openTasks=data.tasks.filter((task)=>!task.completed); const overdueInvoices=data.invoices.filter((i)=>i.status==='Overdue')
  const unpaidTotal=data.invoices.filter((i)=>i.status==='Sent'||i.status==='Overdue').reduce((t,i)=>t+i.total,0)
  const today=new Date();const renewalLimit=new Date(today);renewalLimit.setDate(today.getDate()+60);const renewals=data.organisations.filter((org)=>{if(org.status==='Renewing')return true;if(!org.renewalDate)return false;const date=new Date(`${org.renewalDate}T12:00:00`);return date>=today&&date<=renewalLimit}).sort((a,b)=>a.renewalDate.localeCompare(b.renewalDate)).slice(0,4)
  const membershipValue=data.organisations.filter((org)=>org.status==='Active'||org.status==='Renewing').reduce((t,o)=>t+o.annualValue,0)
  const activeMembers=data.organisations.filter((org)=>(org.status==='Active'||org.status==='Renewing')&&org.tier!=='Free Listing').length
  const threeMonthsAgo=new Date(today);threeMonthsAgo.setMonth(today.getMonth()-3);const newMembers=data.organisations.filter((org)=>org.membershipStart&&new Date(`${org.membershipStart}T12:00:00`)>=threeMonthsAgo).length
  const reviewThemes=Object.entries(data.listings.flatMap((listing)=>listing.reviewHighlights).reduce<Record<string,number>>((counts,item)=>({...counts,[item]:(counts[item]??0)+1}),{})).sort((a,b)=>b[1]-a[1]).slice(0,3)
  const analytics30=data.analyticsEvents.filter((event)=>new Date(event.occurredAt)>=new Date(today.getTime()-30*86400000))
  const websiteVisitors=new Set(analytics30.map((event)=>event.visitorId)).size
  const pageViews=analytics30.filter((event)=>event.type==='page_view').length
  const websiteConversions=analytics30.filter((event)=>event.type==='form_submit'||event.type==='booking_completed').length
  const pipelineValue=useMemo(()=>data.opportunities.filter((o)=>o.stage!=='Won').reduce((t,o)=>t+o.value,0),[data.opportunities])
  const [firstName]=(user?.name??'there').split(' ')
  const memberScores=data.organisations.filter((org)=>['Active','Renewing'].includes(org.status)).map((org)=>engagementScore({lastActivity:org.lastActivity,benefitsUsed:data.benefitUsage.filter((item)=>item.organisationId===org.id&&item.used>0).length,portal:data.contacts.some((item)=>item.organisationId===org.id&&item.portalAccess),listingCompleteness:data.listings.filter((item)=>item.organisationId===org.id).reduce((sum,item,_,rows)=>sum+item.completeness/rows.length,0),campaigns:platform.campaigns.filter((item)=>item.organisationIds.includes(org.id)).length,referrals:data.listings.filter((item)=>item.organisationId===org.id).reduce((sum,item)=>sum+item.enquiries,0),overdueInvoices:data.invoices.filter((item)=>item.organisationId===org.id&&item.status==='Overdue').length},platform.engagementSettings.weights))
  useEffect(()=>{ if(!supabase||!user)return; void supabase.from('user_preferences').select('dashboard_widgets').eq('user_id',user.id).eq('tenant_id',user.tenantId).maybeSingle().then(({data:preferences})=>{if(preferences?.dashboard_widgets)setWidgets(preferences.dashboard_widgets as WidgetId[])}) },[user])
  const saveLayout=()=>{localStorage.setItem(`vv-dashboard-${user?.id??'default'}`,JSON.stringify(widgets));if(supabase&&user)void supabase.from('user_preferences').upsert({user_id:user.id,tenant_id:user.tenantId,dashboard_widgets:widgets,updated_at:new Date().toISOString()},{onConflict:'user_id,tenant_id'});setSaved(true);setTimeout(()=>setSaved(false),1600)}
  const dropOn=(target:WidgetId)=>{if(!dragging||dragging===target)return;setWidgets((current)=>{const next=current.filter((id)=>id!==dragging);next.splice(next.indexOf(target),0,dragging);return next});setDragging(null)}
  const toggleWidget=(id:WidgetId)=>setWidgets((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id])

  const metric=(id:WidgetId)=>{
    const map: Record<WidgetId,{value:string;detail:string;icon:typeof Building2;tone:string}> = {
      'active-members':{value:String(activeMembers),detail:'current paid members',icon:Building2,tone:'purple'},
      'new-members':{value:String(newMembers),detail:'joined in the last 3 months',icon:UserPlus,tone:'green'},
      'membership-income':{value:currency.format(membershipValue),detail:`Across ${activeMembers} current paid members`,icon:CircleDollarSign,tone:'green'},
      'website-visitors':{value:Intl.NumberFormat('en-GB').format(websiteVisitors),detail:'consented visitors in the last 30 days',icon:Globe2,tone:'purple'},
      'page-views':{value:Intl.NumberFormat('en-GB').format(pageViews),detail:'first-party page views in the last 30 days',icon:Eye,tone:'blue'},
      'website-conversions':{value:Intl.NumberFormat('en-GB').format(websiteConversions),detail:pageViews?`${((websiteConversions/pageViews)*100).toFixed(1)}% of page views converted`:'No tracked page views yet',icon:MousePointerClick,tone:'green'},
      'visitor-volume':{value:Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:1}).format(data.workspace.visitorVolume),detail:'latest configured visitor-economy figure',icon:UsersRound,tone:'purple'},
      'visitor-spend':{value:currency.format(data.workspace.visitorSpend),detail:data.workspace.visitorVolume?`${currency.format(data.workspace.visitorSpend/data.workspace.visitorVolume)} average spend per visit`:'Add visitor data in Settings',icon:Banknote,tone:'green'},
      'overnight-stays':{value:Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:2}).format(data.workspace.overnightStays),detail:'latest configured overnight-stay figure',icon:BedDouble,tone:'amber'},
      'pipeline':{value:currency.format(pipelineValue),detail:`${data.opportunities.filter((o)=>o.stage!=='Won').length} live opportunities`,icon:CalendarClock,tone:'amber'},
      'outstanding':{value:currency.format(unpaidTotal),detail:`${overdueInvoices.length} invoices overdue`,icon:PoundSterling,tone:'coral'},
      'bank-balance':{value:data.workspace.bankBalance!==undefined?currency.format(data.workspace.bankBalance):'Not connected',detail:data.workspace.bankBalance!==undefined?'Latest configured available balance':'Authorise an Open Banking provider in Settings',icon:WalletCards,tone:'purple'},
      'member-risk':{value:String(memberScores.filter((score)=>score<45).length),detail:'members with engagement below 45',icon:CircleAlert,tone:'coral'},
      'average-engagement':{value:`${Math.round(memberScores.reduce((sum,score)=>sum+score,0)/(memberScores.length||1))}/100`,detail:'configurable automated score',icon:Sparkles,tone:'purple'},
      'member-value':{value:currency.format(platform.memberValue.reduce((sum,item)=>sum+item.estimatedValue,0)),detail:'estimated value delivered',icon:Star,tone:'green'},
      'active-campaigns':{value:String(platform.campaigns.filter((item)=>item.status==='Active').length),detail:`${platform.campaigns.reduce((sum,item)=>sum+item.referrals,0)} website referrals`,icon:Globe2,tone:'blue'},
      'automation-failures':{value:String(platform.automations.filter((item)=>item.error).length),detail:`${platform.automations.filter((item)=>item.active).length} active workflow rules`,icon:CircleAlert,tone:'amber'},
      'member-tiers':{value:'',detail:'',icon:Building2,tone:'purple'},'review-trends':{value:'',detail:'',icon:Star,tone:'amber'},'renewals':{value:'',detail:'',icon:CalendarClock,tone:'amber'},'tasks':{value:'',detail:'',icon:Check,tone:'green'},'activity':{value:'',detail:'',icon:Eye,tone:'purple'}
    }; const item=map[id], Icon=item.icon
    return <article className="dashboard-widget metric-widget"><div className="widget-top"><span className={`stat-icon ${item.tone}`}><Icon size={19}/></span><GripVertical size={17}/></div><p>{widgetNames[id]}</p><h2>{item.value}</h2><small>{item.detail}</small>{id==='bank-balance'&&<button className="widget-link" onClick={()=>navigate('settings')}>{data.workspace.bankBalance!==undefined?'Manage connection':'Set up connection'} <ArrowRight size={13}/></button>}</article>
  }
  const panel=(id:WidgetId)=>{
    if(id==='member-tiers') return <article className="dashboard-widget panel wide-widget"><div className="widget-heading"><div><h3>Members by level</h3><p>Paying membership mix</p></div><GripVertical size={17}/></div><div className="tier-counts compact">{data.levels.filter((level)=>['level-001','level-002','level-003','level-004'].includes(level.id)).map((level)=><button key={level.id} onClick={()=>navigate('memberships')}><i/><span><small>{level.name}</small><strong>{data.organisations.filter((org)=>org.tier===level.name&&(org.status==='Active'||org.status==='Renewing')).length}</strong><em>members</em></span></button>)}</div></article>
    if(id==='review-trends') return <article className="dashboard-widget panel wide-widget"><div className="widget-heading"><div><h3>Visitor review trends</h3><p>Recurring themes across published listings</p></div><GripVertical size={17}/></div><div className="review-trend-list">{reviewThemes.length?reviewThemes.map(([theme,count])=><span key={theme}><Star size={15}/><strong>{theme}</strong><em>{count} {count===1?'listing':'listings'}</em></span>):<span><Star size={15}/><strong>No review themes yet</strong><em>Add evidence in Listings</em></span>}</div><button className="widget-link" onClick={()=>navigate('listings')}>Review taxonomy and evidence <ArrowRight size={13}/></button></article>
    if(id==='renewals') return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>Upcoming renewals</h3><p>Members requiring action</p></div><GripVertical size={17}/></div><div className="compact-table">{renewals.map((org)=><button className="compact-row" key={org.id} onClick={()=>openOrganisation(org)}><Avatar name={org.name} colour={org.colour} size="sm"/><span className="compact-main"><strong>{org.name}</strong><small>{org.tier}</small></span><span className="compact-date"><strong>{formatDate(org.renewalDate,{day:'numeric',month:'short'})}</strong><small>{org.status}</small></span></button>)}</div></article>
    if(id==='tasks') return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>My tasks</h3><p>Next actions and follow-ups</p></div><GripVertical size={17}/></div><div className="dashboard-tasks">{openTasks.slice(0,5).map((task)=><div className="dashboard-task" key={task.id}><button className="task-check" onClick={()=>toggleTask(task.id)}><Check size={13}/></button><div><strong>{task.title}</strong><span>{task.category}</span></div><small className={dateLabel(task.dueDate).includes('overdue')?'overdue':''}>{dateLabel(task.dueDate)}</small></div>)}</div></article>
    return <article className="dashboard-widget panel"><div className="widget-heading"><div><h3>Recent activity</h3><p>The latest across the workspace</p></div><GripVertical size={17}/></div><div className="activity-list">{data.activities.slice(0,5).map((activity)=><div className="activity-item" key={activity.id}><span className={`activity-icon ${activity.type}`}><Eye size={15}/></span><div><strong>{activity.title}</strong><p>{activity.detail}</p><small>{activity.user} · {timeAgo(activity.timestamp)}</small></div></div>)}</div></article>
  }

  return <div className="dashboard-page configurable-dashboard">
    <section className="dashboard-welcome"><div><span className="eyebrow">{new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:data.workspace.timezone}).format(today)}</span><h1>Good {today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening'}, {firstName}</h1><p>Your membership, visitor economy and team priorities in one place.</p></div><div className="dashboard-actions"><Button icon={Sparkles} variant="secondary" onClick={()=>navigate('tasks')}>Plan my day</Button><Button icon={Settings2} onClick={()=>setConfigure(true)}>Customise dashboard</Button></div></section>
    <section className="attention-strip"><div className="attention-title"><span><CircleAlert size={18}/></span><div><strong>Today’s focus</strong><small>{openTasks.length} open actions across the team</small></div></div><button onClick={()=>navigate('billing')}><strong>{overdueInvoices.length}</strong><span>overdue invoices</span><ArrowRight size={15}/></button><button onClick={()=>navigate('memberships')}><strong>{renewals.length}</strong><span>renewals approaching</span><ArrowRight size={15}/></button><button onClick={()=>navigate('events')}><strong>{data.events.filter((event)=>event.status==='In review'||event.status==='Changes requested').length}</strong><span>event reviews</span><ArrowRight size={15}/></button></section>
    <section className="dashboard-widget-grid">{widgets.map((id)=><div key={id} draggable onDragStart={()=>setDragging(id)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>dropOn(id)} className={metricWidgets.includes(id)?'metric-slot':'panel-slot'}>{metricWidgets.includes(id)?metric(id):panel(id)}</div>)}</section>
    {configure&&<div className="dashboard-config-overlay" onMouseDown={(e)=>e.target===e.currentTarget&&setConfigure(false)}><section className="dashboard-config"><header><div><h2>Customise your dashboard</h2><p>Choose the information you need, then drag cards into your preferred order. This layout is saved to your account.</p></div><button onClick={()=>setConfigure(false)}><X size={20}/></button></header><div className="widget-picker">{(Object.keys(widgetNames) as WidgetId[]).map((id)=><label key={id} className={widgets.includes(id)?'selected':''}><input type="checkbox" checked={widgets.includes(id)} onChange={()=>toggleWidget(id)}/><span><Check size={13}/></span>{widgetNames[id]}</label>)}</div><div className="layout-order"><h3>Display order</h3>{widgets.map((id)=><div draggable onDragStart={()=>setDragging(id)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>dropOn(id)} key={id}><GripVertical size={16}/><span>{widgetNames[id]}</span></div>)}</div><footer><button className="reset-layout" onClick={()=>setWidgets(DEFAULT_WIDGETS)}>Restore recommended layout</button><Button onClick={()=>{saveLayout();setTimeout(()=>setConfigure(false),500)}}>{saved?'Saved':'Save my dashboard'}</Button></footer></section></div>}
  </div>
}
