import { useMemo, useState, type ChangeEvent, type FormEvent } from 'react'
import { Archive, CheckCircle2, Cloud, Copy, HardDriveUpload, Image as ImageIcon, Plus, Search, ShieldCheck } from 'lucide-react'
import { useCRM } from '../store'
import { imageLibrary } from '../siteData'
import type { ImageAsset, ImageAssetLicence } from '../types'
import { Badge, Button, Field, Modal, PageHeader, Tabs } from '../components/UI'

const resolveImage=(value:string)=>imageLibrary[value]??value
const formatBytes=(value:number)=>value?`${(value/1_000_000).toFixed(1)} MB`:'—'

export function ImageBank({createRequest=0}:{createRequest?:number}){
  const {data,createImageAsset,archiveImageAsset}=useCRM()
  const [tab,setTab]=useState<'Library'|'Storage & delivery'>('Library')
  const [query,setQuery]=useState('')
  const [collection,setCollection]=useState('All collections')
  const [adding,setAdding]=useState(Boolean(createRequest))
  const [expiryThreshold]=useState(()=>Date.now()+90*86400000)
  const collections=['All collections',...Array.from(new Set(data.imageAssets.map((asset)=>asset.collection)))]
  const assets=useMemo(()=>data.imageAssets.filter((asset)=>asset.status!=='Archived'&&(collection==='All collections'||asset.collection===collection)&&[asset.name,asset.alt,asset.credit,...asset.tags].join(' ').toLowerCase().includes(query.toLowerCase())),[collection,data.imageAssets,query])
  const expiring=data.imageAssets.filter((asset)=>asset.usageExpiry&&Date.parse(asset.usageExpiry)<expiryThreshold&&asset.status!=='Archived').length
  return <div><PageHeader eyebrow="Website" title="Image bank" description="A single, rights-managed library for website, campaign and member imagery." actions={<Button icon={Plus} onClick={()=>setAdding(true)}>Add image</Button>}/><Tabs items={['Library','Storage & delivery']} active={tab} onChange={setTab}/>
    {tab==='Library'?<><section className="website-kpi-grid image-bank-kpis"><article><span><ImageIcon size={18}/></span><small>Available assets</small><strong>{data.imageAssets.filter((asset)=>asset.status==='Ready').length}</strong></article><article><span><ShieldCheck size={18}/></span><small>Rights recorded</small><strong>{data.imageAssets.filter((asset)=>asset.rightsHolder).length}</strong></article><article><span><Archive size={18}/></span><small>Collections</small><strong>{collections.length-1}</strong></article><article><span><CheckCircle2 size={18}/></span><small>Rights expiring soon</small><strong>{expiring}</strong></article></section>
    <section className="panel media-library"><header className="panel-header"><div><h3>Media library</h3><p>Search alt text, credits, tags and filenames.</p></div><div className="media-filters"><label><Search size={15}/><input aria-label="Search images" placeholder="Search images…" value={query} onChange={(event)=>setQuery(event.target.value)}/></label><select aria-label="Filter collection" value={collection} onChange={(event)=>setCollection(event.target.value)}>{collections.map((item)=><option key={item}>{item}</option>)}</select></div></header><div className="asset-grid">{assets.map((asset)=><article className="asset-card" key={asset.id}><div className="asset-preview"><img src={resolveImage(asset.url)} alt={asset.alt}/><Badge>{asset.status}</Badge></div><div><h3>{asset.name}</h3><p>{asset.alt}</p><div className="asset-tags">{asset.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><dl><div><dt>Credit</dt><dd>{asset.credit||'Not set'}</dd></div><div><dt>Rights</dt><dd>{asset.licence}{asset.usageExpiry?` · to ${asset.usageExpiry}`:''}</dd></div><div><dt>File</dt><dd>{asset.width} × {asset.height} · {formatBytes(asset.fileSize)}</dd></div></dl><footer><Button size="sm" variant="secondary" icon={Copy} onClick={()=>void navigator.clipboard.writeText(asset.url)}>Copy reference</Button><button className="icon-button" aria-label={`Archive ${asset.name}`} title="Archive image" onClick={()=>confirm(`Archive ${asset.name}?`)&&archiveImageAsset(asset.id)}><Archive size={15}/></button></footer></div></article>)}</div>{!assets.length&&<div className="visitor-empty">No images match those filters.</div>}</section></>:<StoragePanel/>}
    {adding&&<AddImageModal onClose={()=>setAdding(false)} onAdd={(asset)=>{createImageAsset(asset);setAdding(false)}}/>}
  </div>
}

function StoragePanel(){return <div className="storage-options"><article className="panel recommended-storage"><span><Cloud size={22}/></span><div><Badge tone="green">Recommended for launch</Badge><h2>Supabase Storage + image transformations</h2><p>Keep media in the same tenant-aware platform as the CRM, store public delivery URLs against each asset and enforce upload access through existing user roles.</p><ul><li>One account, authentication model and audit trail</li><li>Tenant folders and database metadata stay aligned</li><li>Easy route to a CDN or specialist DAM when volume grows</li></ul></div></article><article className="panel storage-comparison"><h2>Hosting decision</h2><div><strong>Supabase Storage</strong><span>Best fit for the current product stack and first production release.</span></div><div><strong>Cloudinary</strong><span>Choose when automatic renditions, focal crops and advanced media workflows become central.</span></div><div><strong>S3 / R2 compatible</strong><span>Choose for maximum infrastructure control and lower-level delivery configuration.</span></div><aside><HardDriveUpload size={18}/><p>The local demo stores small uploads in browser storage. Production uploads are designed for object storage; the database keeps metadata, rights and usage references.</p></aside></article></div>}

function AddImageModal({onClose,onAdd}:{onClose:()=>void;onAdd:(asset:Omit<ImageAsset,'id'|'uploadedAt'>)=>void}){
  const [preview,setPreview]=useState('')
  const [fileMeta,setFileMeta]=useState({size:0,type:'image/jpeg',width:0,height:0})
  const chooseFile=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>1_500_000){alert('For the browser demo, choose an image under 1.5 MB. Production storage supports larger originals.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>{const value=String(reader.result);const image=new Image();image.onload=()=>setFileMeta({size:file.size,type:file.type,width:image.naturalWidth,height:image.naturalHeight});image.src=value;setPreview(value)};reader.readAsDataURL(file)}
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const url=preview||String(form.get('url'));onAdd({name:String(form.get('name')),url,alt:String(form.get('alt')),caption:String(form.get('caption')),credit:String(form.get('credit')),rightsHolder:String(form.get('rightsHolder')),licence:String(form.get('licence')) as ImageAssetLicence,usageExpiry:String(form.get('usageExpiry'))||undefined,tags:String(form.get('tags')).split(',').map((tag)=>tag.trim()).filter(Boolean),collection:String(form.get('collection')),width:fileMeta.width,height:fileMeta.height,fileSize:fileMeta.size,mimeType:fileMeta.type,storageProvider:'Demo library',uploadedBy:'Workspace user',status:'Ready'})}
  return <Modal title="Add image" subtitle="Record the image, accessibility text and usage rights together." onClose={onClose} width="lg"><form className="settings-form" onSubmit={submit}><div className="image-upload-zone">{preview?<img src={preview} alt="Upload preview"/>:<HardDriveUpload size={28}/>}<label>Choose local image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={chooseFile}/></label><small>Demo limit 1.5 MB, or register a hosted URL below.</small></div><div className="form-grid two"><Field label="Image name"><input name="name" required/></Field><Field label="Hosted image URL"><input name="url" type="url" required={!preview}/></Field></div><Field label="Alt text" hint="Describe the purpose of the image for someone who cannot see it."><input name="alt" required/></Field><div className="form-grid two"><Field label="Caption"><input name="caption"/></Field><Field label="Credit"><input name="credit"/></Field><Field label="Rights holder"><input name="rightsHolder" required/></Field><Field label="Licence"><select name="licence">{(['Owned','Licensed','Partner supplied','Creative Commons'] as ImageAssetLicence[]).map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Usage expiry"><input name="usageExpiry" type="date"/></Field><Field label="Collection"><input name="collection" defaultValue="Destination campaign" required/></Field></div><Field label="Tags" hint="Comma-separated"><input name="tags" placeholder="riverside, families, summer"/></Field><footer className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Add to image bank</Button></footer></form></Modal>
}
