import { Inbox as InboxIcon, Mail, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useCRM } from '../store'
import { supabase, useAuth } from '../auth'
import { openEmail } from '../actions'
import { Badge, Button, EmptyState, PageHeader } from '../components/UI'

export function Inbox(){
  const {data,updateSubmission,publishListing,publishEvent,updateListing,updateEvent,addActivity}=useCRM();const [query,setQuery]=useState('');const [status,setStatus]=useState('All')
  const {user}=useAuth();const canPublish=!supabase||user?.role==='Administrator'||user?.role==='Membership manager'
  const [actionError,setActionError]=useState('')
  const runListingAction=(action:()=>Promise<void>)=>{setActionError('');void action().catch((error:unknown)=>setActionError(error instanceof Error?error.message:'Listing action failed'))}
  const submissions=useMemo(()=>data.submissions.filter((item)=>(status==='All'||item.status===status)&&(!query||JSON.stringify(item.payload).toLowerCase().includes(query.toLowerCase())||item.kind.toLowerCase().includes(query.toLowerCase()))),[data.submissions,query,status])
  const listings=data.listings.filter((item)=>item.status==='In review');const events=data.events.filter((item)=>item.status==='In review')
  const requestListing=(id:string)=>{const reason=window.prompt('What needs to change?');if(!reason)return;runListingAction(async()=>{await updateListing(id,{status:'Changes requested'});addActivity(data.listings.find((item)=>item.id===id)?.organisationId,'Listing changes requested',reason)})}
  const requestEvent=(id:string)=>{const reason=window.prompt('What needs to change?');if(!reason)return;updateEvent(id,{status:'Changes requested',moderationNote:reason})}
  const rejectListing=(id:string)=>{const reason=window.prompt('Reason for rejection');if(!reason)return;runListingAction(async()=>{await updateListing(id,{status:'Rejected'});addActivity(data.listings.find((item)=>item.id===id)?.organisationId,'Listing rejected',reason)})}
  const rejectEvent=(id:string)=>{const reason=window.prompt('Reason for rejection');if(!reason)return;updateEvent(id,{status:'Rejected',moderationNote:reason})}
  return <div><PageHeader eyebrow="Home" title="Approvals & website enquiries" description="Review submitted listing and event changes before publication, then handle visitor enquiries."/>{actionError&&<p className="form-error" role="alert">{actionError}</p>}
    <section className="panel platform-panel"><header><div><h2>Awaiting approval</h2><p>Submitted content remains unpublished until a staff member approves it.</p></div><Badge tone={listings.length+events.length?'amber':'green'}>{listings.length+events.length} open</Badge></header><div className="card-list">{listings.map((item)=><article className="platform-row" key={item.id}><div><strong>{item.name}</strong><p>Listing edit · submitted {new Date(item.lastUpdated).toLocaleDateString('en-GB')}</p><small>Proposed listing content is held privately; compare it with the published site before approving.</small></div><div className="event-row-actions">{canPublish&&<Button size="sm" onClick={()=>{if(window.confirm(`Publish ${item.name}?`))runListingAction(()=>publishListing(item.id))}}>Approve & publish</Button>}<Button size="sm" variant="secondary" onClick={()=>requestListing(item.id)}>Request changes</Button><Button size="sm" variant="danger" onClick={()=>rejectListing(item.id)}>Reject</Button></div></article>)}{events.map((item)=><article className="platform-row" key={item.id}><div><strong>{item.title}</strong><p>Event submission by {item.submittedBy||'Unknown submitter'} · {new Date(item.lastUpdated).toLocaleDateString('en-GB')}</p><small>{item.moderationNote||'No submitter note supplied.'}</small></div><div className="event-row-actions"><Button size="sm" onClick={()=>publishEvent(item.id)}>Approve & publish</Button><Button size="sm" variant="secondary" onClick={()=>requestEvent(item.id)}>Request changes</Button><Button size="sm" variant="danger" onClick={()=>rejectEvent(item.id)}>Reject</Button></div></article>)}</div>{!listings.length&&!events.length&&<EmptyState icon={InboxIcon} title="Approval queue is clear" description="Submitted listing and event changes will appear here."/>}</section>
    <section className="summary-strip"><div><InboxIcon size={18}/><p><strong>{data.submissions.filter((item)=>item.status==='New').length}</strong><small>New</small></p></div><div><p><strong>{data.submissions.filter((item)=>item.kind.includes('enquir')).length}</strong><small>Enquiries</small></p></div><div><p><strong>{data.submissions.filter((item)=>item.kind.includes('newsletter')).length}</strong><small>Newsletter signups</small></p></div></section>
    <section className="panel data-panel"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search website submissions..."/></div><label className="select-wrap"><select aria-label="Filter inbox by status" value={status} onChange={(e)=>setStatus(e.target.value)}><option>All</option><option>New</option><option>In progress</option><option>Resolved</option></select></label></div>
    {submissions.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Type</th><th>Contact</th><th>Details</th><th>Received</th><th>Status</th><th/></tr></thead><tbody>{submissions.map((item)=>{const email=String(item.payload.email??'');const name=String(item.payload.name??item.payload.listingName??email);return <tr key={item.id}><td><strong>{item.kind.replace(/-/g,' ')}</strong></td><td><strong>{name}</strong><small>{email}</small></td><td>{Object.entries(item.payload).filter(([key])=>!['email','name'].includes(key)).slice(0,3).map(([key,value])=><span key={key}><strong>{key.replace(/([A-Z])/g,' $1')}: </strong>{String(value)}</span>)}</td><td>{new Date(item.createdAt).toLocaleString('en-GB')}</td><td><Badge>{item.status}</Badge></td><td><div className="event-row-actions">{email&&<button className="icon-button" onClick={()=>openEmail(email,'Your Visit Valechester enquiry')} aria-label={`Email ${email}`}><Mail size={16}/></button>}<label className="select-wrap"><select aria-label={`Update ${name} submission status`} value={item.status} onChange={(event)=>updateSubmission(item.id,{status:event.target.value as typeof item.status})}><option>New</option><option>In progress</option><option>Resolved</option></select></label></div></td></tr>})}</tbody></table></div>:<EmptyState icon={InboxIcon} title="No submissions found" description="New website enquiries will appear here."/>}</section>
  </div>
}
