import { Inbox as InboxIcon, Mail, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useCRM } from '../store'
import { openEmail } from '../actions'
import { Badge, EmptyState, PageHeader } from '../components/UI'

export function Inbox(){
  const {data,updateSubmission}=useCRM();const [query,setQuery]=useState('');const [status,setStatus]=useState('All')
  const submissions=useMemo(()=>data.submissions.filter((item)=>(status==='All'||item.status===status)&&(!query||JSON.stringify(item.payload).toLowerCase().includes(query.toLowerCase())||item.kind.toLowerCase().includes(query.toLowerCase()))),[data.submissions,query,status])
  return <div><PageHeader eyebrow="Website" title="Inbox" description="Handle enquiries, newsletter registrations and other visitor website submissions."/>
    <section className="summary-strip"><div><InboxIcon size={18}/><p><strong>{data.submissions.filter((item)=>item.status==='New').length}</strong><small>New</small></p></div><div><p><strong>{data.submissions.filter((item)=>item.kind.includes('enquir')).length}</strong><small>Enquiries</small></p></div><div><p><strong>{data.submissions.filter((item)=>item.kind.includes('newsletter')).length}</strong><small>Newsletter signups</small></p></div></section>
    <section className="panel data-panel"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search website submissions..."/></div><label className="select-wrap"><select value={status} onChange={(e)=>setStatus(e.target.value)}><option>All</option><option>New</option><option>In progress</option><option>Resolved</option></select></label></div>
    {submissions.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Type</th><th>Contact</th><th>Details</th><th>Received</th><th>Status</th><th/></tr></thead><tbody>{submissions.map((item)=>{const email=String(item.payload.email??'');const name=String(item.payload.name??item.payload.listingName??email);return <tr key={item.id}><td><strong>{item.kind.replace(/-/g,' ')}</strong></td><td><strong>{name}</strong><small>{email}</small></td><td>{Object.entries(item.payload).filter(([key])=>!['email','name'].includes(key)).slice(0,3).map(([key,value])=><span key={key}><strong>{key.replace(/([A-Z])/g,' $1')}: </strong>{String(value)}</span>)}</td><td>{new Date(item.createdAt).toLocaleString('en-GB')}</td><td><Badge>{item.status}</Badge></td><td><div className="event-row-actions">{email&&<button className="icon-button" onClick={()=>openEmail(email,'Your Visit Valechester enquiry')} aria-label={`Email ${email}`}><Mail size={16}/></button>}<label className="select-wrap"><select aria-label={`Update ${name} submission status`} value={item.status} onChange={(event)=>updateSubmission(item.id,{status:event.target.value as typeof item.status})}><option>New</option><option>In progress</option><option>Resolved</option></select></label></div></td></tr>})}</tbody></table></div>:<EmptyState icon={InboxIcon} title="No submissions found" description="New website enquiries will appear here."/>}</section>
  </div>
}
