import { BarChart3, MessageSquareText, Star, TrendingUp } from 'lucide-react'
import { useMemo } from 'react'
import { useCRM } from '../store'
import { Button, Field, PageHeader } from '../components/UI'

export function Insights(){
 const {data,updateSocialMetric}=useCRM()
 const themes=useMemo(()=>{const counts=new Map<string,number>();data.listings.forEach((listing)=>listing.reviewHighlights.forEach((theme)=>counts.set(theme,(counts.get(theme)??0)+1)));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12)},[data.listings])
 const tags=useMemo(()=>{const counts=new Map<string,number>();data.listings.forEach((listing)=>listing.searchTags.forEach((tag)=>counts.set(tag,(counts.get(tag)??0)+1)));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12)},[data.listings])
 return <div><PageHeader eyebrow="Reporting" title="Visitor and social insights" description="Review visitor themes, search coverage and configurable social performance data."/><section className="insight-grid"><article className="panel"><header className="panel-header"><div><h3><Star size={17}/> Review themes</h3><p>Recurring themes recorded across published listings.</p></div></header><div className="review-trend-list">{themes.map(([theme,count])=><span key={theme}><MessageSquareText size={15}/><strong>{theme}</strong><em>{count} listings</em></span>)}</div></article><article className="panel"><header className="panel-header"><div><h3><BarChart3 size={17}/> Search taxonomy coverage</h3><p>The categories visitors can currently discover.</p></div></header><div className="review-trend-list">{tags.map(([tag,count])=><span key={tag}><TrendingUp size={15}/><strong>{tag}</strong><em>{count} listings</em></span>)}</div></article></section><section className="panel settings-content"><header><div><h2>Social performance</h2><p>Update supplied figures or replace them through a connected provider.</p></div></header><div className="settings-form">{data.socialMetrics.map((metric)=><div className="form-grid two" key={metric.id}><Field label={metric.label}><input type="number" value={metric.value} onChange={(e)=>updateSocialMetric(metric.id,{value:Number(e.target.value),displayValue:Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:1}).format(Number(e.target.value)),updatedAt:new Date().toISOString().slice(0,10)})}/></Field><Field label="Source"><input value={metric.source} onChange={(e)=>updateSocialMetric(metric.id,{source:e.target.value})}/></Field></div>)}</div><footer className="settings-save"><span>Changes save to the workspace automatically.</span><Button onClick={()=>window.print()}>Print report</Button></footer></section></div>
}
