import { CalendarDays, Eye, EyeOff, Map, MapPin, Search, Settings2, Star } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { InteractiveMap } from '../components/InteractiveMap'
import { Badge, Button, Field, Modal, PageHeader, Tabs } from '../components/UI'
import { coordinatesFor, eventMapPoint, listingMapPoint, publicMapPoints } from '../mapData'
import { useCRM } from '../store'
import type { DestinationEvent, Listing } from '../types'

type MapEntity = { kind: 'Place'; record: Listing } | { kind: 'Event'; record: DestinationEvent }

export function MapProduct() {
  const { data, updateListing, updateEvent } = useCRM()
  const [tab, setTab] = useState('Locations')
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<MapEntity | null>(null)
  const entities = useMemo<MapEntity[]>(() => [
    ...data.listings.map((record) => ({ kind: 'Place' as const, record })),
    ...data.events.filter((record) => record.format !== 'Online events').map((record) => ({ kind: 'Event' as const, record })),
  ], [data.events, data.listings])
  const rows = entities.filter((entity) => {
    const entityTitle = entity.kind === 'Place' ? entity.record.name : entity.record.title
    return !query || `${entity.kind} ${entityTitle} ${entity.record.category} ${entity.record.town}`.toLowerCase().includes(query.toLowerCase())
  })
  const publicPoints = useMemo(() => publicMapPoints(data.listings, data.events), [data.events, data.listings])
  const update = (entity: MapEntity, changes: { mapLatitude?: number; mapLongitude?: number; mapVisible?: boolean; mapFeatured?: boolean }) => entity.kind === 'Place' ? updateListing(entity.record.id, changes) : updateEvent(entity.record.id, changes)
  const title = (entity: MapEntity) => entity.kind === 'Place' ? entity.record.name : entity.record.title
  return <div><PageHeader eyebrow="Additional product" title="Interactive map" description="Control which published places and events appear on the visitor map, refine their pins and highlight priority locations." actions={<Button icon={Eye} onClick={() => window.open('/map','_blank','noopener,noreferrer')}>View public map</Button>}/>
    <section className="map-product-kpis"><article><MapPin size={18}/><span><strong>{entities.length}</strong><small>Available locations</small></span></article><article><Eye size={18}/><span><strong>{entities.filter(({record})=>record.mapVisible!==false).length}</strong><small>Visible on map</small></span></article><article><Star size={18}/><span><strong>{entities.filter(({record})=>record.mapFeatured).length}</strong><small>Featured pins</small></span></article><article><CalendarDays size={18}/><span><strong>{entities.filter((entity)=>entity.kind==='Event').length}</strong><small>Mappable events</small></span></article></section>
    <Tabs items={['Locations','Map preview','Product setup']} active={tab} onChange={setTab}/>
    {tab === 'Locations' && <section className="panel data-panel map-location-manager"><div className="table-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search map locations..."/></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Location</th><th>Type</th><th>Town</th><th>Coordinates</th><th>Map status</th><th/></tr></thead><tbody>{rows.map((entity)=>{const fallback=coordinatesFor(entity.record.town,entity.record.id);const latitude=entity.record.mapLatitude??fallback[0];const longitude=entity.record.mapLongitude??fallback[1];return <tr key={`${entity.kind}-${entity.record.id}`}><td><div className="org-cell"><MapPin size={18}/><div><strong>{title(entity)}</strong><small>{entity.record.category}</small></div></div></td><td><Badge>{entity.kind}</Badge></td><td>{entity.record.town}</td><td><code>{latitude.toFixed(5)}, {longitude.toFixed(5)}</code></td><td><div className="map-status-stack"><span className={entity.record.mapVisible===false?'hidden':''}>{entity.record.mapVisible===false?<EyeOff size={13}/>:<Eye size={13}/>} {entity.record.mapVisible===false?'Hidden':'Visible'}</span>{entity.record.mapFeatured&&<span className="featured"><Star size={12}/>Featured</span>}</div></td><td><div className="event-row-actions"><button className={`icon-button${entity.record.mapFeatured?' active':''}`} onClick={()=>update(entity,{mapFeatured:!entity.record.mapFeatured})} title={entity.record.mapFeatured?'Remove featured status':'Feature on map'} aria-label={`${entity.record.mapFeatured?'Unfeature':'Feature'} ${title(entity)}`}><Star size={16}/></button><button className="icon-button" onClick={()=>update(entity,{mapVisible:entity.record.mapVisible===false})} title={entity.record.mapVisible===false?'Show on map':'Hide from map'} aria-label={`${entity.record.mapVisible===false?'Show':'Hide'} ${title(entity)} on map`}>{entity.record.mapVisible===false?<Eye size={16}/>:<EyeOff size={16}/>}</button><Button size="sm" variant="secondary" onClick={()=>setEditing(entity)}>Edit pin</Button></div></td></tr>})}</tbody></table></div></section>}
    {tab === 'Map preview' && <section className="panel map-admin-preview"><InteractiveMap points={publicPoints} onOpen={(point)=>window.open(point.path,'_blank','noopener,noreferrer')}/></section>}
    {tab === 'Product setup' && <section className="panel map-product-setup"><header><div><Map size={20}/><span><h2>Interactive Map product</h2><p>A configurable add-on that reuses approved CRM content.</p></span></div><Badge>Enabled</Badge></header><div><article><MapPin size={19}/><span><strong>Automatic content sync</strong><p>Published listings and approved in-person events become map locations automatically.</p></span></article><article><Settings2 size={19}/><span><strong>Editorial control</strong><p>Teams can hide individual pins, correct coordinates and highlight featured places without changing the listing.</p></span></article><article><Search size={19}/><span><strong>Visitor discovery</strong><p>Search, place/event filters, nearby location and direct links back into existing website journeys.</p></span></article></div><footer><strong>Map provider</strong><span>Leaflet interface · OpenStreetMap data and attribution · provider can be replaced per client</span></footer></section>}
    {editing&&<PinEditor entity={editing} onClose={()=>setEditing(null)} onSave={(changes)=>{update(editing,changes);setEditing(null)}}/>}
  </div>
}

function PinEditor({entity,onClose,onSave}:{entity:MapEntity;onClose:()=>void;onSave:(changes:{mapLatitude:number;mapLongitude:number;mapVisible:boolean;mapFeatured:boolean})=>void}){
  const record=entity.record;const fallback=coordinatesFor(record.town,record.id);const [latitude,setLatitude]=useState(record.mapLatitude??fallback[0]);const [longitude,setLongitude]=useState(record.mapLongitude??fallback[1]);const [visible,setVisible]=useState(record.mapVisible!==false);const [featured,setFeatured]=useState(record.mapFeatured??false);const point=entity.kind==='Place'?listingMapPoint(entity.record):eventMapPoint(entity.record)
  const submit=(event:FormEvent)=>{event.preventDefault();onSave({mapLatitude:latitude,mapLongitude:longitude,mapVisible:visible,mapFeatured:featured})}
  return <Modal title={`Edit map pin · ${point.title}`} subtitle="Fine-tune this location without changing its public listing or event content." onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="form-grid two"><Field label="Latitude"><input type="number" step="0.00001" required value={latitude} onChange={(event)=>setLatitude(Number(event.target.value))}/></Field><Field label="Longitude"><input type="number" step="0.00001" required value={longitude} onChange={(event)=>setLongitude(Number(event.target.value))}/></Field></div><div className="pin-editor-options"><label><input type="checkbox" checked={visible} onChange={(event)=>setVisible(event.target.checked)}/><span><strong>Visible on public map</strong><small>Only published content can appear to visitors.</small></span></label><label><input type="checkbox" checked={featured} onChange={(event)=>setFeatured(event.target.checked)}/><span><strong>Featured location</strong><small>Uses a larger marker and can be promoted on landing pages.</small></span></label></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save pin</Button></div></form></Modal>
}
