import { useMemo, useState, type FormEvent } from 'react'
import { Building2, Download, Mail, Pencil, Plus, Search, Trash2, UserRound, UsersRound } from 'lucide-react'
import { Avatar, Badge, Button, EmptyState, Field, Modal, PageHeader } from '../components/UI'
import { TagPicker } from '../components/TagPicker'
import { downloadCsv, openEmail } from '../actions'
import { useCRM } from '../store'
import { usePlatform } from '../platform'
import { useCommunicationHistory } from '../communicationHistory'
import type { Contact } from '../types'

const roleSuggestions=['Primary','Membership','Marketing','Accounts','Signatory','PR','Media','Travel Trade','Creator','Event organiser','General']
const tagSuggestions=['National media','Regional media','Trade media','Press trip','Tour operator','Coach operator','Groups','UK inbound','International','Agency','Media relations','Campaign partner','Family travel','Luxury travel','Accessible travel','Food & drink','Culture','Outdoors','Instagram','LinkedIn','Newsletter']
const emptyPerson:Contact={id:'',organisationId:'',name:'',jobTitle:'',email:'',phone:'',roles:['General'],tags:[],primary:false,portalAccess:false}

export function People({createRequest=0}:{createRequest?:number}){
  const {data,addContact,updateContact,deleteContact}=useCRM()
  const {data:platform}=usePlatform()
  const [query,setQuery]=useState('')
  const [tag,setTag]=useState('All tags')
  const [affiliation,setAffiliation]=useState<'All people'|'Organisation contacts'|'Independent contacts'>('All people')
  const [editing,setEditing]=useState<Contact|null>(createRequest?{...emptyPerson}:null)
  const [historyContact,setHistoryContact]=useState<Contact|null>(null)
  const history=useCommunicationHistory('contact',historyContact?.id??'',platform.communications)
  const allTags=useMemo(()=>Array.from(new Set(data.contacts.flatMap((person)=>person.tags??[]))).sort(),[data.contacts])
  const people=useMemo(()=>data.contacts.filter((person)=>{const organisation=data.organisations.find((item)=>item.id===person.organisationId);const matchesSearch=!query||[person.name,person.jobTitle,person.email,organisation?.name,...person.roles,...(person.tags??[])].join(' ').toLowerCase().includes(query.toLowerCase());const matchesTag=tag==='All tags'||person.tags?.includes(tag);const linked=Boolean(organisation);const matchesAffiliation=affiliation==='All people'||(affiliation==='Organisation contacts'?linked:!linked);return matchesSearch&&matchesTag&&matchesAffiliation}).sort((a,b)=>a.name.localeCompare(b.name)),[affiliation,data.contacts,data.organisations,query,tag])
  const linkedCount=data.contacts.filter((person)=>data.organisations.some((organisation)=>organisation.id===person.organisationId)).length
  const externalCount=data.contacts.length-linkedCount
  const tradeCount=data.contacts.filter((person)=>person.roles.some((role)=>['PR','Media','Travel Trade','Creator'].includes(role))).length
  return <div><PageHeader eyebrow="CRM" title="People" description="Manage organisation contacts, media relationships, travel-trade buyers and other destination partners in one directory." actions={<><Button variant="secondary" icon={Download} onClick={()=>downloadCsv('people.csv',[['Name','Job title','Email','Phone','Organisation','Roles','Tags'],...people.map((person)=>[person.name,person.jobTitle,person.email,person.phone,data.organisations.find((item)=>item.id===person.organisationId)?.name??'',person.roles.join('; '),(person.tags??[]).join('; ')])])}>Export</Button><Button icon={Plus} onClick={()=>setEditing({...emptyPerson})}>Add person</Button></>}/>
    <section className="summary-strip people-summary"><div><span className="summary-icon purple"><UsersRound size={18}/></span><p><strong>{data.contacts.length}</strong><small>All people</small></p></div><div><span className="summary-icon blue"><Building2 size={18}/></span><p><strong>{linkedCount}</strong><small>Organisation contacts</small></p></div><div><span className="summary-icon green"><UserRound size={18}/></span><p><strong>{externalCount}</strong><small>Independent contacts</small></p></div><div><span className="summary-icon amber"><Mail size={18}/></span><p><strong>{tradeCount}</strong><small>PR, media & trade</small></p></div></section>
    <section className="panel data-panel people-directory"><div className="table-toolbar people-toolbar"><div className="table-search"><Search size={17}/><input aria-label="Search people" placeholder="Search people, organisations, roles or tags…" value={query} onChange={(event)=>setQuery(event.target.value)}/></div><select aria-label="Filter people by affiliation" value={affiliation} onChange={(event)=>setAffiliation(event.target.value as typeof affiliation)}><option>All people</option><option>Organisation contacts</option><option>Independent contacts</option></select><select aria-label="Filter people by tag" value={tag} onChange={(event)=>setTag(event.target.value)}><option>All tags</option>{allTags.map((item)=><option key={item}>{item}</option>)}</select></div>
    {people.length?<div className="table-scroll people-table-scroll"><table className="data-table people-table"><thead><tr><th>Person</th><th>Organisation</th><th>Roles</th><th>Tags</th><th>Contact</th><th/></tr></thead><tbody>{people.map((person)=>{const organisation=data.organisations.find((item)=>item.id===person.organisationId);return <tr key={person.id}><td><div className="org-cell"><Avatar name={person.name} colour={organisation?.colour}/><div><strong>{person.name}</strong><small>{person.jobTitle||'Role not set'}</small></div></div></td><td>{organisation?<span className="person-affiliation"><Building2 size={14}/>{organisation.name}</span>:<Badge tone="purple">Independent</Badge>}</td><td><div className="role-tags">{person.roles.map((role)=><Badge key={role} tone="blue">{role}</Badge>)}</div></td><td><div className="directory-tags">{(person.tags??[]).slice(0,3).map((item)=><span key={item}>{item}</span>)}{(person.tags?.length??0)>3&&<em>+{person.tags!.length-3}</em>}</div></td><td><a className="people-email" href={`mailto:${person.email}`}>{person.email}</a><small className="people-phone">{person.phone||'No phone'}</small></td><td><div className="event-row-actions"><button className="icon-button" onClick={()=>openEmail(person.email,'Visit Valechester')} aria-label={`Email ${person.name}`}><Mail size={16}/></button><button className="icon-button" onClick={()=>setEditing({...person,tags:[...(person.tags??[])],roles:[...person.roles]})} aria-label={`Edit ${person.name}`}><Pencil size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${person.name}?`)&&deleteContact(person.id)} aria-label={`Delete ${person.name}`}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table></div>:<EmptyState icon={Search} title="No people found" description="Try changing the search or filters."/>}<footer className="table-footer"><span>Showing {people.length} of {data.contacts.length} people</span><span>Organisation contacts and independent relationships share one directory</span></footer></section>
    <section className="panel platform-panel"><header><div><h2>Contact communication history</h2><p>Open the email activity for any person in this directory.</p></div><select aria-label="Contact communication history" value="" onChange={(event)=>setHistoryContact(data.contacts.find((item)=>item.id===event.target.value)??null)}><option value="">Choose a contact…</option>{people.map((person)=><option key={person.id} value={person.id}>View {person.name}’s history</option>)}</select></header></section>
    {historyContact&&<Modal title={`Communications · ${historyContact.name}`} onClose={()=>setHistoryContact(null)}><div className="card-list">{history.map((item)=><article className="platform-row" key={item.id}><div><strong>{item.subject}</strong><p>{item.status}</p><small>{item.at}</small></div></article>)}{!history.length&&<p>No communications for this contact yet.</p>}</div></Modal>}
    {editing&&<PersonModal person={editing} organisations={data.organisations} allTags={Array.from(new Set([...tagSuggestions,...allTags]))} onClose={()=>setEditing(null)} onSave={(person)=>{if(person.id)updateContact(person.id,person);else{const {id,...input}=person;void id;addContact(input)}setEditing(null)}}/>}
  </div>
}

function PersonModal({person,organisations,allTags,onClose,onSave}:{person:Contact;organisations:ReturnType<typeof useCRM>['data']['organisations'];allTags:string[];onClose:()=>void;onSave:(person:Contact)=>void}){
  const [draft,setDraft]=useState(person)
  const submit=(event:FormEvent)=>{event.preventDefault();onSave({...draft,primary:draft.organisationId?draft.primary:false,portalAccess:draft.organisationId?draft.portalAccess:false})}
  return <Modal title={person.id?'Edit person':'Add person'} subtitle="A person can belong to an organisation or be kept as an independent destination relationship." onClose={onClose} width="lg"><form className="form-stack" onSubmit={submit}><div className="form-grid two"><Field label="Name"><input autoFocus required value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></Field><Field label="Job title"><input value={draft.jobTitle} onChange={(event)=>setDraft({...draft,jobTitle:event.target.value})}/></Field><Field label="Email"><input type="email" required value={draft.email} onChange={(event)=>setDraft({...draft,email:event.target.value})}/></Field><Field label="Phone"><input value={draft.phone} onChange={(event)=>setDraft({...draft,phone:event.target.value})}/></Field></div><Field label="Organisation"><select value={draft.organisationId} onChange={(event)=>setDraft({...draft,organisationId:event.target.value,primary:event.target.value?draft.primary:false,portalAccess:event.target.value?draft.portalAccess:false})}><option value="">Independent contact — no organisation</option>{organisations.map((organisation)=><option key={organisation.id} value={organisation.id}>{organisation.name}</option>)}</select></Field><TagPicker label="Roles" value={draft.roles} onChange={(roles)=>setDraft({...draft,roles})} suggestions={roleSuggestions}/><TagPicker value={draft.tags??[]} onChange={(tags)=>setDraft({...draft,tags})} suggestions={allTags}/>{draft.organisationId&&<div className="form-grid two"><label className="settings-checkbox"><input type="checkbox" checked={draft.primary??false} onChange={(event)=>setDraft({...draft,primary:event.target.checked})}/><span><strong>Primary contact</strong><small>Default person for this organisation.</small></span></label><label className="settings-checkbox"><input type="checkbox" checked={draft.portalAccess??false} onChange={(event)=>setDraft({...draft,portalAccess:event.target.checked})}/><span><strong>Portal access</strong><small>Can use member services.</small></span></label></div>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save person</Button></div></form></Modal>
}
