import { useState, type ReactNode } from 'react'
import { BriefcaseBusiness, CheckCircle2, Download, FileSearch, Globe2, Newspaper, Plus, ShieldCheck } from 'lucide-react'
import { useCRM } from '../store'
import { engagementScore, usePlatform } from '../platform'
import type { MediaCoverage, Survey, WebsiteHealthIssue } from '../platformTypes'
import { Badge, Button, EmptyState, Modal, PageHeader, Progress, Tabs } from '../components/UI'
import { currency, formatDate } from '../utils'
import { downloadCsv } from '../actions'
import { FamTripEditor } from '../components/FamTripEditor'
import type { FamTrip } from '../platformTypes'
import { BrandLogo } from '../components/BrandLogo'
import { downloadFamTripPdf, famTripMemberDetails, parseFamItinerary } from '../famTripPdf'

function Summary({items}:{items:Array<{label:string;value:string|number;detail?:string}>}){return <section className="platform-summary">{items.map((item)=><article key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.detail&&<small>{item.detail}</small>}</article>)}</section>}
function Panel({title,description,action,children}:{title:string;description?:string;action?:ReactNode;children:ReactNode}){return <section className="panel platform-panel"><header><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>{children}</section>}
export { MemberValue } from './MemberValueManagement'

export { Campaigns } from './CampaignManagement'

export { MemberOpportunities } from './OpportunityManagement'

export function Engagement(){const {data:crm}=useCRM();const {data}=usePlatform();const [today]=useState(()=>Date.now());const rows=crm.organisations.filter((org)=>['Active','Renewing'].includes(org.status)).map((org)=>{const listings=crm.listings.filter((item)=>item.organisationId===org.id);const score=engagementScore({lastActivity:org.lastActivity,benefitsUsed:crm.benefitUsage.filter((item)=>item.organisationId===org.id&&item.used>0).length,portal:crm.contacts.some((item)=>item.organisationId===org.id&&item.portalAccess),listingCompleteness:listings.length?listings.reduce((sum,item)=>sum+item.completeness,0)/listings.length:0,campaigns:data.campaigns.filter((item)=>item.organisationIds.includes(org.id)).length,referrals:listings.reduce((sum,item)=>sum+item.enquiries,0),overdueInvoices:crm.invoices.filter((item)=>item.organisationId===org.id&&item.status==='Overdue').length},data.engagementSettings.weights);const flags=[today-new Date(org.lastActivity).getTime()>data.engagementSettings.riskDays*86400000?'No contact for 90 days':'',!crm.benefitUsage.some((item)=>item.organisationId===org.id&&item.used>0)?'No benefits used':'',crm.invoices.some((item)=>item.organisationId===org.id&&item.status==='Overdue')?'Invoice overdue':'',listings.some((item)=>item.completeness<data.engagementSettings.completenessThreshold)?'Listing incomplete':''].filter(Boolean);return{org,score,flags}}).sort((a,b)=>a.score-b.score);return <div><PageHeader eyebrow="Membership" title="Members at risk" description="An automated engagement score supports staff judgement; it never changes the manual health status."/><Summary items={[{label:'Average engagement',value:`${Math.round(rows.reduce((sum,item)=>sum+item.score,0)/(rows.length||1))}/100`},{label:'High risk',value:rows.filter((item)=>item.score<45).length},{label:'Needs attention',value:rows.filter((item)=>item.org.health==='Needs attention').length},{label:'Risk flags',value:rows.reduce((sum,item)=>sum+item.flags.length,0)}]}/><Panel title="Engagement overview" description="Default weights combine contact recency, benefits, portal use, content completeness, campaign activity, referrals and invoice status."><div className="table-scroll"><table className="data-table"><thead><tr><th>Member</th><th>Manual health</th><th>Engagement</th><th>Risk flags</th><th>Renewal</th></tr></thead><tbody>{rows.map(({org,score,flags})=><tr key={org.id}><td><strong>{org.name}</strong><small>{org.tier}</small></td><td><Badge>{org.health}</Badge></td><td><div className="score-cell"><strong>{score}/100</strong><Progress value={score} colour={score<45?'#b23b3b':score<70?'#b97918':'#278362'}/></div></td><td><div className="filter-chips">{flags.length?flags.map((flag)=><span key={flag}>{flag}</span>):<Badge tone="green">No current flags</Badge>}</div></td><td>{formatDate(org.renewalDate)}</td></tr>)}</tbody></table></div></Panel></div>}

export function TravelTrade(){
  const {data,addRecord,updateRecord}=usePlatform()
  const {data:crm}=useCRM()
  const [tab,setTab]=useState<'Buyers'|'Leads'|'Trade Shows'|'FAM Trips'>('Buyers')
  const [editingTrip,setEditingTrip]=useState<FamTrip|null|undefined>(undefined)
  const [previewTrip,setPreviewTrip]=useState<FamTrip|null>(null)
  const [pdfError,setPdfError]=useState('')
  const saveTrip=(trip:FamTrip)=>{if(editingTrip)updateRecord('famTrips',trip.id,trip);else addRecord('famTrips',trip);setEditingTrip(undefined)}
  const download=(trip:FamTrip)=>{setPdfError('');void downloadFamTripPdf(trip,crm,data.travelBuyers).catch(()=>setPdfError('The itinerary PDF could not be created. Please try again.'))}
  return <div>
    <PageHeader eyebrow="Travel Trade" title="Travel Trade" description="Buyer relationships, leads, industry events and familiarisation activity in one place." actions={tab==='FAM Trips'&&<Button icon={Plus} onClick={()=>setEditingTrip(null)}>New FAM trip</Button>}/>
    <Tabs items={['Buyers','Leads','Trade Shows','FAM Trips']} active={tab} onChange={setTab}/>
    {tab==='Buyers'&&<Panel title="Buyers" description="Profiles reuse VisitMade’s relationship model and can link to CRM people and organisations."><div className="module-card-grid">{data.travelBuyers.map((item)=><article className="module-card" key={item.id}><header><Badge>{item.priority}</Badge><span>{item.country}</span></header><h3>{item.company}</h3><p>{item.contact} · {item.type}</p><div className="filter-chips">{item.interests.map((value)=><span key={value}>{value}</span>)}</div><footer>{item.relationshipStatus} · Next: {item.nextAction}</footer></article>)}</div></Panel>}
    {tab==='Leads'&&<Panel title="Trade leads"><div className="card-list">{data.tradeLeads.map((item)=><article className="platform-row" key={item.id}><span className="module-icon"><BriefcaseBusiness size={18}/></span><div><strong>{item.description}</strong><p>{item.markets.join(', ')} · {item.partySize} people · {item.dates}</p><small>Next: {item.nextAction}</small></div><strong>{currency.format(item.estimatedValue)}</strong><Badge>{item.stage}</Badge></article>)}</div></Panel>}
    {tab==='Trade Shows'&&<Panel title="Trade shows"><div className="module-card-grid">{data.tradeShows.map((item)=><article className="module-card" key={item.id}><h3>{item.name}</h3><p>{item.location} · {formatDate(item.startDate)}–{formatDate(item.endDate)}</p><dl><div><dt>Appointments</dt><dd>{item.appointments}</dd></div><div><dt>Qualified buyers</dt><dd>{item.qualifiedBuyers}</dd></div><div><dt>Leads</dt><dd>{item.leads}</dd></div><div><dt>Pipeline</dt><dd>{currency.format(item.estimatedPipeline)}</dd></div></dl></article>)}</div></Panel>}
    {tab==='FAM Trips'&&<Panel title="FAM trips" description="Plan familiarisation visits and connect them with buyer and member records."><>{pdfError&&<p className="form-error" role="alert">{pdfError}</p>}<div className="module-card-grid">{data.famTrips.map((item)=>{const members=famTripMemberDetails(item,crm);const days=parseFamItinerary(item.itinerary);return <article className="module-card fam-trip-card" key={item.id}><header><Badge tone="teal">{item.targetMarket}</Badge><span>{formatDate(item.startDate)}–{formatDate(item.endDate)}</span></header><h3>{item.title}</h3><div className="fam-mini-days">{days.slice(0,3).map((day,index)=><div key={`${day.label}-${index}`}><strong>{day.label}</strong><span>{day.text}</span></div>)}{days.length>3&&<small>+ {days.length-3} more days</small>}</div><div className="fam-member-summary"><strong>Members included</strong><p>{members.length?members.map((member)=>member.name).join(' · '):'No members linked yet'}</p></div><footer>{item.buyerIds.length} buyers · {item.listingIds.length} places · internal cost {currency.format(item.cost)}</footer><div className="fam-card-actions"><Button variant="secondary" size="sm" onClick={()=>setEditingTrip(item)}>Edit FAM trip</Button><Button variant="secondary" size="sm" onClick={()=>setPreviewTrip(item)}>Preview itinerary</Button><Button variant="secondary" size="sm" icon={Download} onClick={()=>download(item)}>Download PDF</Button></div></article>})}</div></></Panel>}
    {editingTrip!==undefined&&<FamTripEditor trip={editingTrip??undefined} onClose={()=>setEditingTrip(undefined)} onSave={saveTrip}/>}
    {previewTrip&&<Modal title="Itinerary preview" subtitle="The downloadable PDF uses this destination's colours, logo and contact details." width="lg" onClose={()=>setPreviewTrip(null)}><div className="fam-preview"><header><BrandLogo inverse/><span>FAMILIARISATION VISIT</span><h2>{previewTrip.title}</h2><p>{previewTrip.targetMarket} · {formatDate(previewTrip.startDate)} – {formatDate(previewTrip.endDate)}</p></header><div className="fam-preview-body"><h3>The itinerary</h3>{parseFamItinerary(previewTrip.itinerary).map((day,index)=><article className="fam-preview-day" key={`${day.label}-${index}`}><strong>{day.label}</strong><p>{day.text}</p></article>)}<h3>Members included</h3><div className="fam-preview-members">{famTripMemberDetails(previewTrip,crm).map((member)=><article key={member.id}><strong>{member.name}</strong><span>{member.places.length?member.places.join(', '):`${member.type} · ${member.town}`}</span></article>)}</div>{previewTrip.accessibility&&<p><strong>Accessibility:</strong> {previewTrip.accessibility}</p>}{previewTrip.dietary&&<p><strong>Dietary:</strong> {previewTrip.dietary}</p>}</div><footer><strong>{crm.workspace.legalName}</strong><span>{crm.workspace.publicWebsiteUrl||window.location.origin} · {crm.workspace.contactEmail}{crm.workspace.contactPhone?` · ${crm.workspace.contactPhone}`:''}</span><span>{crm.workspace.address}</span></footer></div><div className="modal-actions"><Button variant="secondary" onClick={()=>setPreviewTrip(null)}>Close</Button><Button icon={Download} onClick={()=>download(previewTrip)}>Download PDF</Button></div></Modal>}
  </div>
}

export function BusinessEvents(){const {data}=usePlatform();const {data:crm}=useCRM();const match=(delegates:number)=>data.venueCapabilities.filter((item)=>item.maxDelegates>=delegates);return <div><PageHeader eyebrow="Business Events" title="Enquiries & RFPs" description="Match qualified event enquiries with member venues and track responses through to confirmed business."/><Summary items={[{label:'Open enquiries',value:data.businessEnquiries.filter((item)=>!['Won','Lost'].includes(item.stage)).length},{label:'Potential economic value',value:currency.format(data.businessEnquiries.reduce((sum,item)=>sum+item.economicValue,0))},{label:'Venue responses',value:data.businessEnquiries.flatMap((item)=>item.responses).length},{label:'Capable venues',value:data.venueCapabilities.length}]}/>{data.businessEnquiries.map((item)=><Panel key={item.id} title={`${item.client} · ${item.eventType}`} description={`${item.delegates} delegates · ${item.preferredDates}`} action={<Badge>{item.stage}</Badge>}><div className="opportunity-meta"><span><strong>{item.delegates}</strong>Delegates</span><span><strong>{item.roomNights}</strong>Room nights</span><span><strong>{currency.format(item.budget)}</strong>Known budget</span><span><strong>{currency.format(item.economicValue)}</strong>Estimated impact</span></div><p>{item.requirements}</p><h3>Potentially suitable venues</h3><div className="card-list">{match(item.delegates).map((venue)=><article className="platform-row" key={venue.id}><div><strong>{crm.listings.find((listing)=>listing.id===venue.listingId)?.name??'Venue'}</strong><p>Up to {venue.maxDelegates} delegates · {venue.bedrooms} bedrooms · {venue.breakoutRooms} breakouts</p><small>{venue.accessibility}</small></div><Badge tone={item.invitedVenueIds.includes(venue.id)?'blue':'grey'}>{item.invitedVenueIds.includes(venue.id)?'Invited':'Suitable'}</Badge></article>)}</div></Panel>)}</div>}

export function PRMedia(){const {data}=usePlatform();const [tab,setTab]=useState<'Contacts'|'Opportunities'|'Coverage'|'Releases'>('Contacts');return <div><PageHeader eyebrow="Marketing" title="PR & Media" description="Media relationships, reactive opportunities, coverage and controlled release drafting."/><Tabs items={['Contacts','Opportunities','Coverage','Releases']} active={tab} onChange={setTab}/>{tab==='Contacts'&&<Panel title="Media contacts"><div className="module-card-grid">{data.mediaProfiles.map((item)=><article className="module-card" key={item.id}><Badge tone="purple">{item.type}</Badge><h3>{item.name}</h3><p>{item.outlet} · {item.country}</p><div className="filter-chips">{item.topics.map((topic)=><span key={topic}>{topic}</span>)}</div><footer>{item.audience.toLocaleString()} audience · {item.preference}</footer></article>)}</div></Panel>}{tab==='Opportunities'&&<Panel title="PR opportunities"><div className="card-list">{data.prOpportunities.map((item)=><article className="platform-row" key={item.id}><span className="module-icon"><Newspaper size={18}/></span><div><strong>{item.title}</strong><p>{item.publication} · deadline {formatDate(item.deadline)}</p><small>{item.request}</small></div><Badge tone={item.responseSent?'green':'amber'}>{item.responseSent?'Response sent':'Action needed'}</Badge></article>)}</div></Panel>}{tab==='Coverage'&&<Panel title="Coverage"><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Coverage</th><th>Audience</th><th>Sentiment</th><th>Estimated value</th></tr></thead><tbody>{data.mediaCoverage.map((item:MediaCoverage)=><tr key={item.id}><td>{formatDate(item.publicationDate)}</td><td><a href={item.url} target="_blank" rel="noreferrer"><strong>{item.title}</strong></a><small>{item.outlet} · {item.journalist}</small></td><td>{item.audience.toLocaleString()}</td><td><Badge>{item.sentiment}</Badge></td><td>{currency.format(item.estimatedValue)}<small>Indicative estimate</small></td></tr>)}</tbody></table></div></Panel>}{tab==='Releases'&&<Panel title="Press releases" description="Draft, approve and record distribution without presenting VisitMade as a public distribution network."><EmptyState icon={Newspaper} title="No release drafts" description="Create a communication using a media segment, then record the approved release and distribution history here."/></Panel>}</div>}

export function Surveys(){const {data}=usePlatform();const responses=(surveyId:string)=>data.surveyResponses.filter((item)=>item.surveyId===surveyId);const nps=(survey:Survey)=>{const values=responses(survey.id).map((item)=>Number(item.answers[survey.questions.find((q)=>q.type==='nps')?.id??''])).filter(Number.isFinite);if(!values.length)return null;return Math.round((values.filter((v)=>v>=9).length/values.length-values.filter((v)=>v<=6).length/values.length)*100)};return <div><PageHeader eyebrow="Research" title="Surveys" description="Member, visitor and stakeholder research with public or identified responses."/><Summary items={[{label:'Open surveys',value:data.surveys.filter((item)=>item.status==='Open').length},{label:'Responses',value:data.surveyResponses.length},{label:'Identified responses',value:data.surveyResponses.filter((item)=>item.organisationId).length},{label:'Average NPS',value:nps(data.surveys[0])??'—'}]}/><div className="module-card-grid">{data.surveys.map((survey)=><article className="module-card" key={survey.id}><header><Badge>{survey.status}</Badge><span>{survey.anonymous?'Anonymous':'Identified'}</span></header><h3>{survey.title}</h3><p>{survey.introduction}</p><dl><div><dt>Responses</dt><dd>{responses(survey.id).length}</dd></div><div><dt>Questions</dt><dd>{survey.questions.length}</dd></div><div><dt>NPS</dt><dd>{nps(survey)??'—'}</dd></div></dl><footer><a href={`/survey/${survey.slug}`} target="_blank" rel="noreferrer">Open public survey</a> · closes {formatDate(survey.closingDate)}</footer><Button variant="secondary" size="sm" icon={Download} onClick={()=>downloadCsv(`${survey.slug}.csv`,[['Submitted','Organisation','Answers'],...responses(survey.id).map((item)=>[item.submittedAt,item.organisationId??'Anonymous',JSON.stringify(item.answers)])])}>Export CSV</Button></article>)}</div></div>}

export function WebsiteHealth({navigate}:{navigate:(view:'pages'|'listings'|'events'|'images')=>void}){
  const {data:crm}=useCRM();const {data,addRecord,updateRecord}=usePlatform();const [area,setArea]=useState<'All'|WebsiteHealthIssue['area']>('All');const [today]=useState(()=>new Date().toISOString().slice(0,10))
  const generated:WebsiteHealthIssue[]=[
    ...crm.imageAssets.filter((item)=>item.status!=='Archived'&&!item.alt.trim()).map((item)=>({id:`derived-image-alt-${item.id}`,area:'Accessibility' as const,severity:'High' as const,title:'Missing alternative text',description:`${item.name} has no useful alternative text.`,entityType:'Image' as const,entityId:item.id,route:'images',resolved:false,check:'Active images must have contextual alternative text'})),
    ...crm.websitePages.filter((item)=>!item.draft.metaTitle.trim()).map((item)=>({id:`derived-page-title-${item.id}`,area:'SEO' as const,severity:'High' as const,title:'Missing page title',description:`${item.name} has no SEO title in its current draft.`,entityType:'Page' as const,entityId:item.id,route:'pages',resolved:false,check:'Every indexable page needs a unique title'})),
    ...crm.websitePages.filter((item)=>item.draft.metaDescription.trim().length>0&&item.draft.metaDescription.trim().length<70).map((item)=>({id:`derived-page-description-${item.id}`,area:'SEO' as const,severity:'Medium' as const,title:'Meta description is too short',description:`${item.name} has a ${item.draft.metaDescription.trim().length}-character description.`,entityType:'Page' as const,entityId:item.id,route:'pages',resolved:false,check:'Meta descriptions should usually be 70–160 characters'})),
    ...crm.listings.filter((item)=>item.status!=='Draft'&&item.completeness<data.engagementSettings.completenessThreshold).map((item)=>({id:`derived-listing-${item.id}`,area:'Content' as const,severity:'High' as const,title:'Listing completeness below threshold',description:`${item.name} is ${item.completeness}% complete.`,entityType:'Listing' as const,entityId:item.id,route:'listings',resolved:false,check:`Review-stage and published listings should be at least ${data.engagementSettings.completenessThreshold}% complete`})),
    ...crm.events.filter((item)=>item.status==='Published'&&item.endDate<today).map((item)=>({id:`derived-event-${item.id}`,area:'Content' as const,severity:'Medium' as const,title:'Past event remains published',description:`${item.title} ended on ${formatDate(item.endDate)}.`,entityType:'Event' as const,entityId:item.id,route:'events',resolved:false,check:'Past events should be archived or explicitly retained'})),
  ]
  const generatedIds=new Set(generated.map((item)=>item.id));const all=[...data.healthIssues.filter((item)=>!generatedIds.has(item.id)),...generated.filter((item)=>!data.healthIssues.some((saved)=>saved.id===item.id&&saved.resolved)),...data.healthIssues.filter((item)=>generatedIds.has(item.id)&&item.resolved)]
  const issues=all.filter((item)=>!item.resolved&&(area==='All'||item.area===area));const penalties={Critical:25,High:15,Medium:8,Low:3};const score=(type:WebsiteHealthIssue['area'])=>Math.max(0,100-all.filter((item)=>item.area===type&&!item.resolved).reduce((sum,item)=>sum+penalties[item.severity],0));const resolve=(item:WebsiteHealthIssue)=>data.healthIssues.some((saved)=>saved.id===item.id)?updateRecord('healthIssues',item.id,{resolved:true}):addRecord('healthIssues',{...item,resolved:true})
  return <div><PageHeader eyebrow="Website" title="Website Health" description="Transparent automated checks support—but cannot guarantee—WCAG compliance, SEO quality or editorial accuracy."/><section className="health-scores">{(['Accessibility','SEO','Content'] as const).map((item)=><article key={item}><span className="module-icon">{item==='Accessibility'?<ShieldCheck/>:item==='SEO'?<Globe2/>:<FileSearch/>}</span><div><small>{item}</small><strong>{score(item)}/100</strong><Progress value={score(item)}/><span>{all.filter((issue)=>issue.area===item&&!issue.resolved).length} open issues</span></div></article>)}</section><div className="filter-pills" role="group" aria-label="Filter issues">{(['All','Accessibility','SEO','Content'] as const).map((item)=><button className={area===item?'active':''} onClick={()=>setArea(item)} key={item}>{item}</button>)}</div><Panel title="Open issues" description="Each score starts at 100 and deducts 25/15/8/3 points for critical/high/medium/low unresolved issues."><div className="card-list">{issues.map((item)=><article className="platform-row health-row" key={item.id}><span className={`severity-dot ${item.severity.toLowerCase()}`}/><div><strong>{item.title}</strong><p>{item.description}</p><small>{item.check}</small></div><Badge>{item.severity}</Badge>{item.route!=='Site'&&<Button size="sm" variant="secondary" onClick={()=>navigate(item.route as 'pages'|'listings'|'events'|'images')}>Open record</Button>}<Button size="sm" variant="ghost" onClick={()=>resolve(item)}>Resolve</Button></article>)}</div>{!issues.length&&<EmptyState icon={CheckCircle2} title="No open issues" description="There are no unresolved issues in this category."/>}</Panel></div>
}
