import { useState, type ReactNode } from 'react'
import { BriefcaseBusiness, CheckCircle2, Download, FileSearch, Globe2, Mail, Newspaper, Play, Plus, ShieldCheck, Target } from 'lucide-react'
import { useCRM } from '../store'
import { engagementScore, makePlatformId, usePlatform } from '../platform'
import type { Campaign, CommunicationRecord, ContactSegment, MediaCoverage, MemberValueEntry, Survey, WebsiteHealthIssue } from '../platformTypes'
import { Badge, Button, EmptyState, Field, Modal, PageHeader, Progress, Tabs } from '../components/UI'
import { currency, formatDate } from '../utils'
import { downloadCsv } from '../actions'
import { FamTripEditor } from '../components/FamTripEditor'
import type { FamTrip } from '../platformTypes'
import { BrandLogo } from '../components/BrandLogo'
import { downloadFamTripPdf, famTripMemberDetails, parseFamItinerary } from '../famTripPdf'

function Summary({items}:{items:Array<{label:string;value:string|number;detail?:string}>}){return <section className="platform-summary">{items.map((item)=><article key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.detail&&<small>{item.detail}</small>}</article>)}</section>}
function Panel({title,description,action,children}:{title:string;description?:string;action?:ReactNode;children:ReactNode}){return <section className="panel platform-panel"><header><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>{children}</section>}
function DateFilter({value,onChange}:{value:string;onChange:(value:string)=>void}){return <label className="compact-filter"><span>Period</span><select value={value} onChange={(event)=>onChange(event.target.value)}><option value="current">Current membership year</option><option value="previous">Previous membership year</option><option value="all">All records</option></select></label>}

export function MemberValue(){
  const {data:crm}=useCRM();const {data,addRecord}=usePlatform();const [period,setPeriod]=useState('current');const [adding,setAdding]=useState(false)
  const rows=data.memberValue.filter((item)=>period==='all'||(period==='current'?item.date>='2026-09-01':item.date<'2026-09-01'))
  const delivered=rows.reduce((sum,item)=>sum+item.estimatedValue,0);const referrals=rows.filter((item)=>item.activity.toLowerCase().includes('referral')).reduce((sum,item)=>sum+item.quantity,0)
  const save=(input:Omit<MemberValueEntry,'id'>)=>{addRecord('memberValue',{...input,id:makePlatformId('value')});setAdding(false)}
  return <div><PageHeader eyebrow="Membership" title="Member Value" description="Evidence of the activity, exposure and support delivered to members. Monetary figures are indicative estimates, not objective financial returns." actions={<><DateFilter value={period} onChange={setPeriod}/><Button icon={Plus} onClick={()=>setAdding(true)}>Record value</Button></>}/>
    <Summary items={[{label:'Estimated value delivered',value:currency.format(delivered),detail:'Clearly labelled estimate'},{label:'Member activities',value:rows.length},{label:'Website referrals',value:referrals},{label:'Members receiving value',value:new Set(rows.map((item)=>item.organisationId)).size}]}/>
    <Panel title="Value delivery ledger" description="Filterable evidence across website, marketing, PR, travel trade, MICE and engagement."><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Member</th><th>Category</th><th>Activity</th><th>Quantity</th><th>Estimated value</th><th>Evidence</th></tr></thead><tbody>{rows.map((item)=><tr key={item.id}><td>{formatDate(item.date)}</td><td><strong>{crm.organisations.find((org)=>org.id===item.organisationId)?.name??'Unknown member'}</strong></td><td><Badge>{item.category}</Badge></td><td>{item.activity}</td><td>{item.quantity}</td><td>{item.estimatedValue?currency.format(item.estimatedValue):'Measured only'}</td><td>{item.evidence}</td></tr>)}</tbody></table></div></Panel>
    {adding&&<ValueModal onClose={()=>setAdding(false)} onSave={save}/>}</div>
}
function ValueModal({onClose,onSave}:{onClose:()=>void;onSave:(value:Omit<MemberValueEntry,'id'>)=>void}){const {data}=useCRM();const [draft,setDraft]=useState<Omit<MemberValueEntry,'id'>>({organisationId:data.organisations[0]?.id??'',date:new Date().toISOString().slice(0,10),category:'Marketing',activity:'',quantity:1,estimatedValue:0,evidence:''});return <Modal title="Record member value" subtitle="Record a measured activity and, where appropriate, an explicitly estimated value." onClose={onClose}><form className="form-stack" onSubmit={(event)=>{event.preventDefault();onSave(draft)}}><Field label="Member"><select required value={draft.organisationId} onChange={(e)=>setDraft({...draft,organisationId:e.target.value})}>{data.organisations.filter((org)=>!['Prospect','Non-member'].includes(org.status)).map((org)=><option value={org.id} key={org.id}>{org.name}</option>)}</select></Field><div className="form-grid two"><Field label="Date"><input required type="date" value={draft.date} onChange={(e)=>setDraft({...draft,date:e.target.value})}/></Field><Field label="Category"><select value={draft.category} onChange={(e)=>setDraft({...draft,category:e.target.value as MemberValueEntry['category']})}>{['Website','Marketing','PR','Travel trade','MICE','Engagement'].map((item)=><option key={item}>{item}</option>)}</select></Field></div><Field label="Activity"><input required autoFocus value={draft.activity} onChange={(e)=>setDraft({...draft,activity:e.target.value})}/></Field><div className="form-grid two"><Field label="Quantity"><input type="number" min="0" value={draft.quantity} onChange={(e)=>setDraft({...draft,quantity:Number(e.target.value)})}/></Field><Field label="Estimated value (£)" hint="Optional and always shown as an estimate."><input type="number" min="0" value={draft.estimatedValue} onChange={(e)=>setDraft({...draft,estimatedValue:Number(e.target.value)})}/></Field></div><Field label="Evidence"><textarea required rows={3} value={draft.evidence} onChange={(e)=>setDraft({...draft,evidence:e.target.value})}/></Field><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save record</Button></div></form></Modal>}

export function Communications(){
  const {data:crm,addActivity}=useCRM();const {data,addRecord,updateRecord}=usePlatform();const [tab,setTab]=useState<'Campaigns'|'Templates'|'Segments'|'Preferences'>('Campaigns');const [composer,setComposer]=useState(false)
  const segmentCount=(segment:ContactSegment)=>crm.contacts.filter((contact)=>{const org=crm.organisations.find((item)=>item.id===contact.organisationId);return segment.filters.every((filter)=>{const value=filter.field==='membership_level'?org?.tier:filter.field==='organisation_type'?org?.type:filter.field==='portal_access'?String(Boolean(contact.portalAccess)):filter.field==='contact_role'?contact.roles.join(','):'';return filter.operator==='equals'?value===filter.value:filter.operator==='is one of'?filter.value.split(',').map((item)=>item.trim()).includes(value??''):true})}).length
  const queue=(draft:Omit<CommunicationRecord,'id'|'createdAt'|'recipientCount'>)=>{const recipients=draft.segmentId?segmentCount(data.segments.find((item)=>item.id===draft.segmentId)??data.segments[0]):crm.contacts.length;const record={...draft,id:makePlatformId('comm'),createdAt:new Date().toISOString(),recipientCount:recipients};addRecord('communications',record);crm.organisations.forEach((org)=>{if(crm.contacts.some((contact)=>contact.organisationId===org.id))addActivity(org.id,'Communication queued',draft.subject)});setComposer(false)}
  const preferenceFor=(contactId:string)=>data.communicationPreferences.find((item)=>item.contactId===contactId)
  const savePreference=(contactId:string,changes:Partial<{service:boolean;marketing:boolean;trade:boolean;events:boolean;research:boolean;lawfulBasis:string}>)=>{const existing=preferenceFor(contactId);if(existing)updateRecord('communicationPreferences',existing.id,changes);else addRecord('communicationPreferences',{id:makePlatformId('preference'),contactId,service:true,marketing:false,trade:false,events:false,research:false,lawfulBasis:'Legitimate interests',note:'',...changes})}
  return <div><PageHeader eyebrow="Workspace" title="Communications" description="Create targeted member communications without pretending the CRM is an email-delivery network." actions={<Button icon={Plus} onClick={()=>setComposer(true)}>New communication</Button>}/><Tabs items={['Campaigns','Templates','Segments','Preferences']} active={tab} onChange={setTab}/>
    {tab==='Campaigns'&&<Panel title="Communication history" description="Drafts remain reviewable until a delivery provider is configured."><div className="card-list">{data.communications.map((item)=><article className="platform-row" key={item.id}><span className="module-icon"><Mail size={18}/></span><div><strong>{item.name}</strong><p>{item.subject}</p><small>{item.recipientCount} recipients · created {formatDate(item.createdAt)}</small></div><Badge>{item.status}</Badge>{item.status==='Draft'&&<Button size="sm" variant="secondary" onClick={()=>updateRecord('communications',item.id,{status:'Queued'})}>Queue</Button>}</article>)}</div></Panel>}
    {tab==='Templates'&&<Panel title="Email templates" description="Merge fields are resolved only when a communication is prepared."><div className="module-card-grid">{data.communicationTemplates.map((item)=><article className="module-card" key={item.id}><Badge tone="purple">{item.category}</Badge><h3>{item.name}</h3><p><strong>{item.subject}</strong></p><small>{item.previewText}</small><footer>Updated {formatDate(item.updatedAt)}</footer></article>)}</div></Panel>}
    {tab==='Segments'&&<Panel title="Dynamic segments" description="Membership and relationship filters recalculate against current CRM data."><div className="module-card-grid">{data.segments.map((item)=><article className="module-card" key={item.id}><Badge tone="blue">{item.dynamic?'Dynamic':'Static'}</Badge><h3>{item.name}</h3><p>{item.description}</p><div className="filter-chips">{item.filters.map((filter)=><span key={`${filter.field}-${filter.value}`}>{filter.field.replaceAll('_',' ')} {filter.operator} {filter.value}</span>)}</div><footer><strong>{segmentCount(item)}</strong> matching contacts</footer></article>)}</div></Panel>}
    {tab==='Preferences'&&<Panel title="Communication preferences" description="Service messages, marketing consent and lawful basis remain separate. Unrecorded contacts default to service-only."><div className="table-scroll"><table className="data-table preference-table"><thead><tr><th>Contact</th><th>Service</th><th>Marketing</th><th>Trade</th><th>Events</th><th>Research</th><th>Lawful basis</th></tr></thead><tbody>{crm.contacts.map((contact)=>{const preference=preferenceFor(contact.id);return <tr key={contact.id}><td><strong>{contact.name}</strong><small>{contact.email}</small></td>{(['service','marketing','trade','events','research'] as const).map((key)=><td key={key}><input aria-label={`${contact.name} ${key}`} type="checkbox" checked={preference?.[key]??key==='service'} onChange={(event)=>savePreference(contact.id,{[key]:event.target.checked})}/></td>)}<td><select aria-label={`${contact.name} lawful basis`} value={preference?.lawfulBasis??'Legitimate interests'} onChange={(event)=>savePreference(contact.id,{lawfulBasis:event.target.value})}><option>Legitimate interests</option><option>Consent</option><option>Contract</option><option>Legal obligation</option><option>Not recorded</option></select></td></tr>})}</tbody></table></div></Panel>}
    {composer&&<CommunicationModal onClose={()=>setComposer(false)} onSave={queue}/>}</div>
}
function CommunicationModal({onClose,onSave}:{onClose:()=>void;onSave:(draft:Omit<CommunicationRecord,'id'|'createdAt'|'recipientCount'>)=>void}){const {data}=usePlatform();const first=data.communicationTemplates[0];const [draft,setDraft]=useState<Omit<CommunicationRecord,'id'|'createdAt'|'recipientCount'>>({name:'',templateId:first?.id,segmentId:data.segments[0]?.id,subject:first?.subject??'',body:first?.body??'',status:'Draft'});return <Modal title="New communication" subtitle="Prepare a reviewable draft or queue it for a configured provider." onClose={onClose} width="lg"><form className="form-stack" onSubmit={(e)=>{e.preventDefault();onSave(draft)}}><div className="form-grid two"><Field label="Internal name"><input required autoFocus value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Recipient segment"><select value={draft.segmentId} onChange={(e)=>setDraft({...draft,segmentId:e.target.value})}>{data.segments.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><Field label="Template"><select value={draft.templateId} onChange={(e)=>{const template=data.communicationTemplates.find((item)=>item.id===e.target.value);setDraft({...draft,templateId:e.target.value,subject:template?.subject??draft.subject,body:template?.body??draft.body})}}>{data.communicationTemplates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Subject"><input required value={draft.subject} onChange={(e)=>setDraft({...draft,subject:e.target.value})}/></Field><Field label="Body"><textarea required rows={9} value={draft.body} onChange={(e)=>setDraft({...draft,body:e.target.value})}/></Field><p className="form-note">Supported merge fields include {'{{first_name}}'}, {'{{organisation_name}}'}, {'{{membership_level}}'} and {'{{renewal_date}}'}.</p><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save draft</Button></div></form></Modal>}

export function Automations(){const {data,updateRecord,runAutomation}=usePlatform();return <div><PageHeader eyebrow="Manage" title="Automations" description="Focused DMO workflows built around WHEN → CONDITIONS → THEN."/><Summary items={[{label:'Active rules',value:data.automations.filter((item)=>item.active).length},{label:'Total runs',value:data.automations.reduce((sum,item)=>sum+item.runs,0)},{label:'Failures',value:data.automations.filter((item)=>item.error).length},{label:'Loop protection',value:'Enabled',detail:'One rule per event'}]}/><Panel title="Workflow rules" description="Use Run test to execute safe internal actions such as task creation; external messages remain queued."><div className="automation-list">{data.automations.map((rule)=><article key={rule.id} className="automation-card"><header><div><Badge tone={rule.active?'green':'grey'}>{rule.active?'Active':'Inactive'}</Badge><h3>{rule.name}</h3><p>{rule.description}</p></div><button className={`switch ${rule.active?'on':''}`} aria-pressed={rule.active} aria-label={`${rule.active?'Disable':'Enable'} ${rule.name}`} onClick={()=>updateRecord('automations',rule.id,{active:!rule.active})}><span/></button></header><div className="automation-flow"><span><small>WHEN</small>{rule.trigger.replaceAll('_',' ')}</span><b>→</b><span><small>CONDITIONS</small>{rule.conditions.length?rule.conditions.map((item)=>`${item.field.replaceAll('_',' ')} ${item.operator} ${item.value}`).join('; '):'No extra conditions'}</span><b>→</b><span><small>THEN</small>{rule.actions.map((item)=>`${item.type.replaceAll('_',' ')}: ${item.value}`).join('; ')}</span></div><footer><span>{rule.lastRun?`Last run ${formatDate(rule.lastRun)}`:'Not run yet'} · {rule.runs} runs</span><Button size="sm" variant="secondary" icon={Play} disabled={!rule.active} onClick={()=>runAutomation(rule.id)}>Run test</Button></footer>{rule.error&&<p className="automation-error" role="alert">{rule.error}</p>}</article>)}</div></Panel></div>}

export function Campaigns(){const {data,addRecord}=usePlatform();const [adding,setAdding]=useState(false);const active=data.campaigns.filter((item)=>item.status==='Active');return <div><PageHeader eyebrow="Marketing" title="Campaigns" description="Connect campaign plans, member participation and measured website outcomes." actions={<Button icon={Plus} onClick={()=>setAdding(true)}>New campaign</Button>}/><Summary items={[{label:'Active campaigns',value:active.length},{label:'Live budget',value:currency.format(active.reduce((sum,item)=>sum+item.budget,0))},{label:'Website referrals',value:data.campaigns.reduce((sum,item)=>sum+item.referrals,0)},{label:'Conversions',value:data.campaigns.reduce((sum,item)=>sum+item.conversions,0),detail:'Last-touch where campaign tagged'}]}/><div className="module-card-grid">{data.campaigns.map((item)=><article className="module-card campaign-card" key={item.id}><header><Badge>{item.status}</Badge><span>{item.owner}</span></header><h3>{item.name}</h3><p>{item.objective}</p><div className="campaign-progress"><span><small>Spend</small><strong>{currency.format(item.actualSpend)} / {currency.format(item.budget)}</strong></span><Progress value={item.budget?item.actualSpend/item.budget*100:0}/></div><dl><div><dt>Reach</dt><dd>{item.reach.toLocaleString()}</dd></div><div><dt>Clicks</dt><dd>{item.clicks.toLocaleString()}</dd></div><div><dt>Referrals</dt><dd>{item.referrals.toLocaleString()}</dd></div><div><dt>Conversions</dt><dd>{item.conversions.toLocaleString()}</dd></div></dl><footer>{formatDate(item.startDate)} – {formatDate(item.endDate)}</footer></article>)}</div>{adding&&<CampaignModal onClose={()=>setAdding(false)} onSave={(record)=>{addRecord('campaigns',record);setAdding(false)}}/>}</div>}
function CampaignModal({onClose,onSave}:{onClose:()=>void;onSave:(record:Campaign)=>void}){const [draft,setDraft]=useState({name:'',owner:'Alex Morgan',startDate:'',endDate:'',objective:'',audience:'',budget:0});return <Modal title="New campaign" onClose={onClose}><form className="form-stack" onSubmit={(e)=>{e.preventDefault();onSave({id:makePlatformId('campaign'),...draft,status:'Planning',markets:[],themes:[],channels:[],actualSpend:0,organisationIds:[],listingIds:[],pageIds:[],impressions:0,reach:0,clicks:0,conversions:0,referrals:0})}}><Field label="Campaign name"><input autoFocus required value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Objective"><textarea required value={draft.objective} onChange={(e)=>setDraft({...draft,objective:e.target.value})}/></Field><Field label="Audience"><input value={draft.audience} onChange={(e)=>setDraft({...draft,audience:e.target.value})}/></Field><div className="form-grid two"><Field label="Start date"><input required type="date" value={draft.startDate} onChange={(e)=>setDraft({...draft,startDate:e.target.value})}/></Field><Field label="End date"><input required type="date" value={draft.endDate} onChange={(e)=>setDraft({...draft,endDate:e.target.value})}/></Field></div><Field label="Budget (£)"><input type="number" min="0" value={draft.budget} onChange={(e)=>setDraft({...draft,budget:Number(e.target.value)})}/></Field><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Create campaign</Button></div></form></Modal>}

export function MemberOpportunities(){const {data,updateRecord}=usePlatform();const {data:crm}=useCRM();return <div><PageHeader eyebrow="Membership" title="Opportunities" description="Campaign, trade, PR, training and research opportunities offered to eligible members."/><Summary items={[{label:'Open opportunities',value:data.memberOpportunities.filter((item)=>item.status==='Open').length},{label:'Applications',value:data.memberOpportunities.flatMap((item)=>item.applications).length},{label:'Approved',value:data.memberOpportunities.flatMap((item)=>item.applications).filter((item)=>item.status==='Approved').length},{label:'Potential contribution',value:currency.format(data.memberOpportunities.reduce((sum,item)=>sum+item.applications.length*item.price,0))}]}/>{data.memberOpportunities.map((item)=><Panel key={item.id} title={item.title} description={item.description} action={<Badge>{item.status}</Badge>}><div className="opportunity-meta"><span><strong>{item.category}</strong>Category</span><span><strong>{item.capacity}</strong>Places</span><span><strong>{currency.format(item.price)}</strong>Contribution</span><span><strong>{formatDate(item.closingDate)}</strong>Closes</span></div><p className="requirements"><strong>Required:</strong> {item.requirements}</p>{item.applications.length?<div className="card-list">{item.applications.map((application)=><article className="platform-row" key={application.id}><div><strong>{crm.organisations.find((org)=>org.id===application.organisationId)?.name}</strong><p>{application.response}</p><small>{application.notes}</small></div><Badge>{application.status}</Badge>{application.status==='Applied'&&<><Button size="sm" variant="secondary" onClick={()=>updateRecord('memberOpportunities',item.id,{applications:item.applications.map((entry)=>entry.id===application.id?{...entry,status:'Approved'}:entry)})}>Approve</Button><Button size="sm" variant="ghost" onClick={()=>updateRecord('memberOpportunities',item.id,{applications:item.applications.map((entry)=>entry.id===application.id?{...entry,status:'Information requested'}:entry)})}>Request information</Button></>}</article>)}</div>:<EmptyState icon={Target} title="No applications yet" description="Eligible portal users can apply until the closing date."/>}</Panel>)}</div>}

export function Engagement(){const {data:crm}=useCRM();const {data}=usePlatform();const [today]=useState(()=>Date.now());const rows=crm.organisations.filter((org)=>['Active','Renewing'].includes(org.status)).map((org)=>{const listings=crm.listings.filter((item)=>item.organisationId===org.id);const score=engagementScore({lastActivity:org.lastActivity,benefitsUsed:crm.benefitUsage.filter((item)=>item.organisationId===org.id&&item.used>0).length,portal:crm.contacts.some((item)=>item.organisationId===org.id&&item.portalAccess),listingCompleteness:listings.length?listings.reduce((sum,item)=>sum+item.completeness,0)/listings.length:0,campaigns:data.campaigns.filter((item)=>item.organisationIds.includes(org.id)).length,referrals:listings.reduce((sum,item)=>sum+item.enquiries,0),overdueInvoices:crm.invoices.filter((item)=>item.organisationId===org.id&&item.status==='Overdue').length},data.engagementSettings.weights);const flags=[today-new Date(org.lastActivity).getTime()>data.engagementSettings.riskDays*86400000?'No contact for 90 days':'',!crm.benefitUsage.some((item)=>item.organisationId===org.id&&item.used>0)?'No benefits used':'',crm.invoices.some((item)=>item.organisationId===org.id&&item.status==='Overdue')?'Invoice overdue':'',listings.some((item)=>item.completeness<data.engagementSettings.completenessThreshold)?'Listing incomplete':''].filter(Boolean);return{org,score,flags}}).sort((a,b)=>a.score-b.score);return <div><PageHeader eyebrow="Membership" title="Members at risk" description="An automated engagement score supports staff judgement; it never changes the manual health status."/><Summary items={[{label:'Average engagement',value:`${Math.round(rows.reduce((sum,item)=>sum+item.score,0)/(rows.length||1))}/100`},{label:'High risk',value:rows.filter((item)=>item.score<45).length},{label:'Needs attention',value:rows.filter((item)=>item.org.health==='Needs attention').length},{label:'Risk flags',value:rows.reduce((sum,item)=>sum+item.flags.length,0)}]}/><Panel title="Engagement overview" description="Default weights combine contact recency, benefits, portal use, content completeness, campaign activity, referrals and invoice status."><div className="table-scroll"><table className="data-table"><thead><tr><th>Member</th><th>Manual health</th><th>Engagement</th><th>Risk flags</th><th>Renewal</th></tr></thead><tbody>{rows.map(({org,score,flags})=><tr key={org.id}><td><strong>{org.name}</strong><small>{org.tier}</small></td><td><Badge>{org.health}</Badge></td><td><div className="score-cell"><strong>{score}/100</strong><Progress value={score} colour={score<45?'#b23b3b':score<70?'#b97918':'#278362'}/></div></td><td><div className="filter-chips">{flags.length?flags.map((flag)=><span key={flag}>{flag}</span>):<Badge tone="green">No current flags</Badge>}</div></td><td>{formatDate(org.renewalDate)}</td></tr>)}</tbody></table></div></Panel></div>}

export function TravelTrade(){
  const {data,addRecord,updateRecord}=usePlatform()
  const {data:crm}=useCRM()
  const [tab,setTab]=useState<'Buyers'|'Leads'|'Trade Shows'|'FAM Trips'>('Buyers')
  const [editingTrip,setEditingTrip]=useState<FamTrip|null|undefined>(undefined)
  const [previewTrip,setPreviewTrip]=useState<FamTrip|null>(null)
  const [pdfError,setPdfError]=useState('')
  const saveTrip=(trip:FamTrip)=>{if(editingTrip)updateRecord('famTrips',trip.id,trip);else addRecord('famTrips',trip);setEditingTrip(undefined)}
  const download=(trip:FamTrip)=>{setPdfError('');void downloadFamTripPdf(trip,crm,data.travelBuyers).catch(()=>setPdfError('The itinerary PDF could not be created. Please try again.'))}
  return <div>
    <PageHeader eyebrow="Travel Trade" title="Travel Trade" description="Buyer relationships, leads, industry events and familiarisation activity in one place." actions={tab==='FAM Trips'&&<Button icon={Plus} onClick={()=>setEditingTrip(null)}>New FAM trip</Button>}/>
    <Tabs items={['Buyers','Leads','Trade Shows','FAM Trips']} active={tab} onChange={setTab}/>
    {tab==='Buyers'&&<Panel title="Buyers" description="Profiles reuse VisitMade’s relationship model and can link to CRM people and organisations."><div className="module-card-grid">{data.travelBuyers.map((item)=><article className="module-card" key={item.id}><header><Badge>{item.priority}</Badge><span>{item.country}</span></header><h3>{item.company}</h3><p>{item.contact} · {item.type}</p><div className="filter-chips">{item.interests.map((value)=><span key={value}>{value}</span>)}</div><footer>{item.relationshipStatus} · Next: {item.nextAction}</footer></article>)}</div></Panel>}
    {tab==='Leads'&&<Panel title="Trade leads"><div className="card-list">{data.tradeLeads.map((item)=><article className="platform-row" key={item.id}><span className="module-icon"><BriefcaseBusiness size={18}/></span><div><strong>{item.description}</strong><p>{item.markets.join(', ')} · {item.partySize} people · {item.dates}</p><small>Next: {item.nextAction}</small></div><strong>{currency.format(item.estimatedValue)}</strong><Badge>{item.stage}</Badge></article>)}</div></Panel>}
    {tab==='Trade Shows'&&<Panel title="Trade shows"><div className="module-card-grid">{data.tradeShows.map((item)=><article className="module-card" key={item.id}><h3>{item.name}</h3><p>{item.location} · {formatDate(item.startDate)}–{formatDate(item.endDate)}</p><dl><div><dt>Appointments</dt><dd>{item.appointments}</dd></div><div><dt>Qualified buyers</dt><dd>{item.qualifiedBuyers}</dd></div><div><dt>Leads</dt><dd>{item.leads}</dd></div><div><dt>Pipeline</dt><dd>{currency.format(item.estimatedPipeline)}</dd></div></dl></article>)}</div></Panel>}
    {tab==='FAM Trips'&&<Panel title="FAM trips" description="Plan familiarisation visits and connect them with buyer and member records."><>{pdfError&&<p className="form-error" role="alert">{pdfError}</p>}<div className="module-card-grid">{data.famTrips.map((item)=>{const members=famTripMemberDetails(item,crm);const days=parseFamItinerary(item.itinerary);return <article className="module-card fam-trip-card" key={item.id}><header><Badge tone="teal">{item.targetMarket}</Badge><span>{formatDate(item.startDate)}–{formatDate(item.endDate)}</span></header><h3>{item.title}</h3><div className="fam-mini-days">{days.slice(0,3).map((day,index)=><div key={`${day.label}-${index}`}><strong>{day.label}</strong><span>{day.text}</span></div>)}{days.length>3&&<small>+ {days.length-3} more days</small>}</div><div className="fam-member-summary"><strong>Members included</strong><p>{members.length?members.map((member)=>member.name).join(' · '):'No members linked yet'}</p></div><footer>{item.buyerIds.length} buyers · {item.listingIds.length} places · internal cost {currency.format(item.cost)}</footer><div className="fam-card-actions"><Button variant="secondary" size="sm" onClick={()=>setEditingTrip(item)}>Edit FAM trip</Button><Button variant="secondary" size="sm" onClick={()=>setPreviewTrip(item)}>Preview itinerary</Button><Button variant="secondary" size="sm" icon={Download} onClick={()=>download(item)}>Download PDF</Button></div></article>})}</div></></Panel>}
    {editingTrip!==undefined&&<FamTripEditor trip={editingTrip??undefined} onClose={()=>setEditingTrip(undefined)} onSave={saveTrip}/>}
    {previewTrip&&<Modal title="Itinerary preview" subtitle="The downloadable PDF uses this destination's colours, logo and contact details." width="lg" onClose={()=>setPreviewTrip(null)}><div className="fam-preview"><header><BrandLogo inverse/><span>FAMILIARISATION VISIT</span><h2>{previewTrip.title}</h2><p>{previewTrip.targetMarket} · {formatDate(previewTrip.startDate)} – {formatDate(previewTrip.endDate)}</p></header><div className="fam-preview-body"><h3>The itinerary</h3>{parseFamItinerary(previewTrip.itinerary).map((day,index)=><article className="fam-preview-day" key={`${day.label}-${index}`}><strong>{day.label}</strong><p>{day.text}</p></article>)}<h3>Members included</h3><div className="fam-preview-members">{famTripMemberDetails(previewTrip,crm).map((member)=><article key={member.id}><strong>{member.name}</strong><span>{member.places.length?member.places.join(', '):`${member.type} · ${member.town}`}</span></article>)}</div>{previewTrip.accessibility&&<p><strong>Accessibility:</strong> {previewTrip.accessibility}</p>}{previewTrip.dietary&&<p><strong>Dietary:</strong> {previewTrip.dietary}</p>}</div><footer><strong>{crm.workspace.legalName}</strong><span>{crm.workspace.publicWebsiteUrl||window.location.origin} · {crm.workspace.contactEmail}{crm.workspace.contactPhone?` · ${crm.workspace.contactPhone}`:''}</span><span>{crm.workspace.address}</span></footer></div><div className="modal-actions"><Button variant="secondary" onClick={()=>setPreviewTrip(null)}>Close</Button><Button icon={Download} onClick={()=>download(previewTrip)}>Download PDF</Button></div></Modal>}
  </div>
}

export function BusinessEvents(){const {data}=usePlatform();const {data:crm}=useCRM();const match=(delegates:number)=>data.venueCapabilities.filter((item)=>item.maxDelegates>=delegates);return <div><PageHeader eyebrow="Business Events" title="Enquiries & RFPs" description="Match qualified event enquiries with member venues and track responses through to confirmed business."/><Summary items={[{label:'Open enquiries',value:data.businessEnquiries.filter((item)=>!['Won','Lost'].includes(item.stage)).length},{label:'Potential economic value',value:currency.format(data.businessEnquiries.reduce((sum,item)=>sum+item.economicValue,0))},{label:'Venue responses',value:data.businessEnquiries.flatMap((item)=>item.responses).length},{label:'Capable venues',value:data.venueCapabilities.length}]}/>{data.businessEnquiries.map((item)=><Panel key={item.id} title={`${item.client} · ${item.eventType}`} description={`${item.delegates} delegates · ${item.preferredDates}`} action={<Badge>{item.stage}</Badge>}><div className="opportunity-meta"><span><strong>{item.delegates}</strong>Delegates</span><span><strong>{item.roomNights}</strong>Room nights</span><span><strong>{currency.format(item.budget)}</strong>Known budget</span><span><strong>{currency.format(item.economicValue)}</strong>Estimated impact</span></div><p>{item.requirements}</p><h3>Potentially suitable venues</h3><div className="card-list">{match(item.delegates).map((venue)=><article className="platform-row" key={venue.id}><div><strong>{crm.listings.find((listing)=>listing.id===venue.listingId)?.name??'Venue'}</strong><p>Up to {venue.maxDelegates} delegates · {venue.bedrooms} bedrooms · {venue.breakoutRooms} breakouts</p><small>{venue.accessibility}</small></div><Badge tone={item.invitedVenueIds.includes(venue.id)?'blue':'grey'}>{item.invitedVenueIds.includes(venue.id)?'Invited':'Suitable'}</Badge></article>)}</div></Panel>)}</div>}

export function PRMedia(){const {data}=usePlatform();const [tab,setTab]=useState<'Contacts'|'Opportunities'|'Coverage'|'Releases'>('Contacts');return <div><PageHeader eyebrow="Marketing" title="PR & Media" description="Media relationships, reactive opportunities, coverage and controlled release drafting."/><Tabs items={['Contacts','Opportunities','Coverage','Releases']} active={tab} onChange={setTab}/>{tab==='Contacts'&&<Panel title="Media contacts"><div className="module-card-grid">{data.mediaProfiles.map((item)=><article className="module-card" key={item.id}><Badge tone="purple">{item.type}</Badge><h3>{item.name}</h3><p>{item.outlet} · {item.country}</p><div className="filter-chips">{item.topics.map((topic)=><span key={topic}>{topic}</span>)}</div><footer>{item.audience.toLocaleString()} audience · {item.preference}</footer></article>)}</div></Panel>}{tab==='Opportunities'&&<Panel title="PR opportunities"><div className="card-list">{data.prOpportunities.map((item)=><article className="platform-row" key={item.id}><span className="module-icon"><Newspaper size={18}/></span><div><strong>{item.title}</strong><p>{item.publication} · deadline {formatDate(item.deadline)}</p><small>{item.request}</small></div><Badge tone={item.responseSent?'green':'amber'}>{item.responseSent?'Response sent':'Action needed'}</Badge></article>)}</div></Panel>}{tab==='Coverage'&&<Panel title="Coverage"><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Coverage</th><th>Audience</th><th>Sentiment</th><th>Estimated value</th></tr></thead><tbody>{data.mediaCoverage.map((item:MediaCoverage)=><tr key={item.id}><td>{formatDate(item.publicationDate)}</td><td><a href={item.url} target="_blank" rel="noreferrer"><strong>{item.title}</strong></a><small>{item.outlet} · {item.journalist}</small></td><td>{item.audience.toLocaleString()}</td><td><Badge>{item.sentiment}</Badge></td><td>{currency.format(item.estimatedValue)}<small>Indicative estimate</small></td></tr>)}</tbody></table></div></Panel>}{tab==='Releases'&&<Panel title="Press releases" description="Draft, approve and record distribution without presenting VisitMade as a public distribution network."><EmptyState icon={Newspaper} title="No release drafts" description="Create a communication using a media segment, then record the approved release and distribution history here."/></Panel>}</div>}

export function Surveys(){const {data}=usePlatform();const responses=(surveyId:string)=>data.surveyResponses.filter((item)=>item.surveyId===surveyId);const nps=(survey:Survey)=>{const values=responses(survey.id).map((item)=>Number(item.answers[survey.questions.find((q)=>q.type==='nps')?.id??''])).filter(Number.isFinite);if(!values.length)return null;return Math.round((values.filter((v)=>v>=9).length/values.length-values.filter((v)=>v<=6).length/values.length)*100)};return <div><PageHeader eyebrow="Research" title="Surveys" description="Member, visitor and stakeholder research with public or identified responses."/><Summary items={[{label:'Open surveys',value:data.surveys.filter((item)=>item.status==='Open').length},{label:'Responses',value:data.surveyResponses.length},{label:'Identified responses',value:data.surveyResponses.filter((item)=>item.organisationId).length},{label:'Average NPS',value:nps(data.surveys[0])??'—'}]}/><div className="module-card-grid">{data.surveys.map((survey)=><article className="module-card" key={survey.id}><header><Badge>{survey.status}</Badge><span>{survey.anonymous?'Anonymous':'Identified'}</span></header><h3>{survey.title}</h3><p>{survey.introduction}</p><dl><div><dt>Responses</dt><dd>{responses(survey.id).length}</dd></div><div><dt>Questions</dt><dd>{survey.questions.length}</dd></div><div><dt>NPS</dt><dd>{nps(survey)??'—'}</dd></div></dl><footer><a href={`/survey/${survey.slug}`} target="_blank" rel="noreferrer">Open public survey</a> · closes {formatDate(survey.closingDate)}</footer><Button variant="secondary" size="sm" icon={Download} onClick={()=>downloadCsv(`${survey.slug}.csv`,[['Submitted','Organisation','Answers'],...responses(survey.id).map((item)=>[item.submittedAt,item.organisationId??'Anonymous',JSON.stringify(item.answers)])])}>Export CSV</Button></article>)}</div></div>}

export function WebsiteHealth({navigate}:{navigate:(view:'pages'|'listings'|'events'|'images')=>void}){
  const {data:crm}=useCRM();const {data,addRecord,updateRecord}=usePlatform();const [area,setArea]=useState<'All'|WebsiteHealthIssue['area']>('All');const [today]=useState(()=>new Date().toISOString().slice(0,10))
  const generated:WebsiteHealthIssue[]=[
    ...crm.imageAssets.filter((item)=>item.status!=='Archived'&&!item.alt.trim()).map((item)=>({id:`derived-image-alt-${item.id}`,area:'Accessibility' as const,severity:'High' as const,title:'Missing alternative text',description:`${item.name} has no useful alternative text.`,entityType:'Image' as const,entityId:item.id,route:'images',resolved:false,check:'Active images must have contextual alternative text'})),
    ...crm.websitePages.filter((item)=>!item.draft.metaTitle.trim()).map((item)=>({id:`derived-page-title-${item.id}`,area:'SEO' as const,severity:'High' as const,title:'Missing page title',description:`${item.name} has no SEO title in its current draft.`,entityType:'Page' as const,entityId:item.id,route:'pages',resolved:false,check:'Every indexable page needs a unique title'})),
    ...crm.websitePages.filter((item)=>item.draft.metaDescription.trim().length>0&&item.draft.metaDescription.trim().length<70).map((item)=>({id:`derived-page-description-${item.id}`,area:'SEO' as const,severity:'Medium' as const,title:'Meta description is too short',description:`${item.name} has a ${item.draft.metaDescription.trim().length}-character description.`,entityType:'Page' as const,entityId:item.id,route:'pages',resolved:false,check:'Meta descriptions should usually be 70–160 characters'})),
    ...crm.listings.filter((item)=>item.status!=='Draft'&&item.completeness<data.engagementSettings.completenessThreshold).map((item)=>({id:`derived-listing-${item.id}`,area:'Content' as const,severity:'High' as const,title:'Listing completeness below threshold',description:`${item.name} is ${item.completeness}% complete.`,entityType:'Listing' as const,entityId:item.id,route:'listings',resolved:false,check:`Review-stage and published listings should be at least ${data.engagementSettings.completenessThreshold}% complete`})),
    ...crm.events.filter((item)=>item.status==='Published'&&item.endDate<today).map((item)=>({id:`derived-event-${item.id}`,area:'Content' as const,severity:'Medium' as const,title:'Past event remains published',description:`${item.title} ended on ${formatDate(item.endDate)}.`,entityType:'Event' as const,entityId:item.id,route:'events',resolved:false,check:'Past events should be archived or explicitly retained'})),
  ]
  const generatedIds=new Set(generated.map((item)=>item.id));const all=[...data.healthIssues.filter((item)=>!generatedIds.has(item.id)),...generated.filter((item)=>!data.healthIssues.some((saved)=>saved.id===item.id&&saved.resolved)),...data.healthIssues.filter((item)=>generatedIds.has(item.id)&&item.resolved)]
  const issues=all.filter((item)=>!item.resolved&&(area==='All'||item.area===area));const penalties={Critical:25,High:15,Medium:8,Low:3};const score=(type:WebsiteHealthIssue['area'])=>Math.max(0,100-all.filter((item)=>item.area===type&&!item.resolved).reduce((sum,item)=>sum+penalties[item.severity],0));const resolve=(item:WebsiteHealthIssue)=>data.healthIssues.some((saved)=>saved.id===item.id)?updateRecord('healthIssues',item.id,{resolved:true}):addRecord('healthIssues',{...item,resolved:true})
  return <div><PageHeader eyebrow="Website" title="Website Health" description="Transparent automated checks support—but cannot guarantee—WCAG compliance, SEO quality or editorial accuracy."/><section className="health-scores">{(['Accessibility','SEO','Content'] as const).map((item)=><article key={item}><span className="module-icon">{item==='Accessibility'?<ShieldCheck/>:item==='SEO'?<Globe2/>:<FileSearch/>}</span><div><small>{item}</small><strong>{score(item)}/100</strong><Progress value={score(item)}/><span>{all.filter((issue)=>issue.area===item&&!issue.resolved).length} open issues</span></div></article>)}</section><div className="filter-pills" role="group" aria-label="Filter issues">{(['All','Accessibility','SEO','Content'] as const).map((item)=><button className={area===item?'active':''} onClick={()=>setArea(item)} key={item}>{item}</button>)}</div><Panel title="Open issues" description="Each score starts at 100 and deducts 25/15/8/3 points for critical/high/medium/low unresolved issues."><div className="card-list">{issues.map((item)=><article className="platform-row health-row" key={item.id}><span className={`severity-dot ${item.severity.toLowerCase()}`}/><div><strong>{item.title}</strong><p>{item.description}</p><small>{item.check}</small></div><Badge>{item.severity}</Badge>{item.route!=='Site'&&<Button size="sm" variant="secondary" onClick={()=>navigate(item.route as 'pages'|'listings'|'events'|'images')}>Open record</Button>}<Button size="sm" variant="ghost" onClick={()=>resolve(item)}>Resolve</Button></article>)}</div>{!issues.length&&<EmptyState icon={CheckCircle2} title="No open issues" description="There are no unresolved issues in this category."/>}</Panel></div>
}
