import { Banknote, BellRing, Building2, Check, CreditCard, Database, Globe2, KeyRound, Palette, PlugZap, RotateCcw, ShieldCheck, SlidersHorizontal, UserPlus, UsersRound, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useCRM } from '../store'
import { Button, Field, PageHeader } from '../components/UI'
import { type FeatureKey } from '../tenant'
import { useFeatures } from '../features'
import { useAuth, type UserRole, type WorkspaceUser } from '../auth'

const sections=[
  {id:'workspace',label:'Workspace',icon:Building2},{id:'branding',label:'Branding',icon:Palette},{id:'modules',label:'Modules & features',icon:SlidersHorizontal},{id:'data',label:'Data & integrations',icon:PlugZap},{id:'team',label:'Team & permissions',icon:UsersRound},{id:'security',label:'Security',icon:ShieldCheck},
]
const modules:Array<{key:FeatureKey;name:string;detail:string}>=[
  {key:'organisations',name:'Organisations & contacts',detail:'Member, partner and prospect records.'},{key:'salesPipeline',name:'Sales pipeline',detail:'Lead stages, values and next actions.'},{key:'memberships',name:'Membership',detail:'Configurable tiers, benefits and usage.'},{key:'billing',name:'Billing',detail:'Invoices, payments and reminders.'},{key:'listings',name:'Listings CMS',detail:'Edit, approve and publish listings.'},{key:'events',name:'What’s on',detail:'Events and date-led discovery.'},{key:'itineraries',name:'Guides & itineraries',detail:'Ideas, trails and trip planning.'},{key:'reviewIntelligence',name:'Review intelligence',detail:'Evidence-led visitor themes and operational insight.'},{key:'socialInsights',name:'Social performance',detail:'Manual or connected channel metrics.'},{key:'businessPortal',name:'Business portal',detail:'Partner-managed contacts and submissions.'},
]
const roles:UserRole[]=['Administrator','Membership manager','Content editor','Finance user']

export function Settings(){
  const {data,resetWorkspace,updateWorkspace}=useCRM(); const {features,setFeature}=useFeatures(); const {user,users,inviteUser,updateUser,removeUser,resetPassword,productionAuth}=useAuth()
  const [section,setSection]=useState('workspace'); const [saved,setSaved]=useState(false); const [editing,setEditing]=useState<WorkspaceUser|null>(null); const [inviting,setInviting]=useState(false)
  const [workspace,setWorkspace]=useState(data.workspace)
  const [bankConnected,setBankConnected]=useState(()=>localStorage.getItem('vv-bank-connected')==='true')
  const setWorkspaceField=<K extends keyof typeof workspace>(key:K,value:(typeof workspace)[K])=>setWorkspace((current)=>({...current,[key]:value}))
  const save=()=>{updateWorkspace(workspace);document.documentElement.style.setProperty('--tenant-primary',workspace.primaryColour);document.documentElement.style.setProperty('--tenant-accent',workspace.accentColour);document.documentElement.style.setProperty('--tenant-sage',workspace.supportingColour);setSaved(true);setTimeout(()=>setSaved(false),1600)}
  return <div><PageHeader eyebrow="Manage" title="Settings" description="Configure the destination workspace, connected data and team access."/>
    <div className="settings-layout"><nav className="settings-nav">{sections.map(({id,label,icon:Icon})=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={17}/>{label}</button>)}</nav>
      <section className="panel settings-content">
        {section==='workspace'&&<><header><div><h2>Workspace details</h2><p>Core settings used across the CRM and visitor website.</p></div></header><div className="settings-form"><Field label="Destination name"><input value={workspace.destinationName} onChange={(e)=>setWorkspaceField('destinationName',e.target.value)}/></Field><div className="form-grid two"><Field label="Default timezone"><select value={workspace.timezone} onChange={(e)=>setWorkspaceField('timezone',e.target.value)}><option>Europe/London</option><option>Europe/Dublin</option><option>UTC</option></select></Field><Field label="Default currency"><select value={workspace.currency} onChange={(e)=>setWorkspaceField('currency',e.target.value)}><option value="GBP">GBP — Pound sterling</option><option value="EUR">EUR — Euro</option><option value="USD">USD — US dollar</option></select></Field></div><div className="form-grid two"><Field label="Financial year starts"><select value={workspace.financialYearStart} onChange={(e)=>setWorkspaceField('financialYearStart',e.target.value)}><option>September</option><option>April</option><option>January</option></select></Field><Field label="Membership year starts"><select value={workspace.membershipYearStart} onChange={(e)=>setWorkspaceField('membershipYearStart',e.target.value)}><option>1 September</option><option>1 April</option><option>1 January</option></select></Field></div><Field label="Workspace address"><textarea rows={3} value={workspace.address} onChange={(e)=>setWorkspaceField('address',e.target.value)}/></Field></div></>}
        {section==='branding'&&<><header><div><h2>Branding</h2><p>One identity across the website, workspace, invoices and partner communications.</p></div></header><div className="settings-form"><Field label="Organisation name"><input value={workspace.legalName} onChange={(e)=>setWorkspaceField('legalName',e.target.value)}/></Field><Field label="Visitor-facing strapline"><input value={workspace.strapline} onChange={(e)=>setWorkspaceField('strapline',e.target.value)}/></Field><div className="colour-settings"><label>Primary colour<input type="color" value={workspace.primaryColour} onChange={(e)=>setWorkspaceField('primaryColour',e.target.value)}/></label><label>Accent colour<input type="color" value={workspace.accentColour} onChange={(e)=>setWorkspaceField('accentColour',e.target.value)}/></label><label>Supporting colour<input type="color" value={workspace.supportingColour} onChange={(e)=>setWorkspaceField('supportingColour',e.target.value)}/></label></div></div></>}
        {section==='modules'&&<><header><div><h2>Modules & features</h2><p>Choose the tools included in this workspace.</p></div></header><div className="module-grid">{modules.map((m)=><article key={m.key}><div><strong>{m.name}</strong><p>{m.detail}</p></div><button className={`switch ${features[m.key]?'on':''}`} onClick={()=>setFeature(m.key,!features[m.key])} aria-pressed={features[m.key]}><span/></button></article>)}</div></>}
        {section==='data'&&<><header><div><h2>Data & integrations</h2><p>Control the sources available to dashboard widgets and reporting.</p></div></header><div className="integration-list">
          <article><span className="integration-icon"><Globe2 size={21}/></span><div><strong>Visitor website</strong><p>Published listings, events and taxonomy are connected.</p></div><em className="connected"><i/>Connected</em><Button variant="secondary" size="sm" onClick={()=>window.open('/','_blank','noopener,noreferrer')}>Open website</Button></article>
          <article><span className="integration-icon"><Database size={21}/></span><div><strong>Visitor economy data</strong><p>{workspace.visitorVolume.toLocaleString()} visits · £{workspace.visitorSpend.toLocaleString()} spend · {workspace.overnightStays.toLocaleString()} nights.</p></div><em className="connected"><i/>Configured</em><Button variant="secondary" size="sm" onClick={()=>{const volume=window.prompt('Visitor volume',String(workspace.visitorVolume));const spend=window.prompt('Visitor spend (£)',String(workspace.visitorSpend));const nights=window.prompt('Overnight stays',String(workspace.overnightStays));if(volume&&spend&&nights)setWorkspace((current)=>({...current,visitorVolume:Number(volume),visitorSpend:Number(spend),overnightStays:Number(nights)}))}}>Update data</Button></article>
          <article><span className="integration-icon"><Banknote size={21}/></span><div><strong>Business bank account</strong><p>{bankConnected?`${workspace.bankProvider??'Open Banking'} · latest imported balance £${(workspace.bankBalance??0).toLocaleString()}.`:'Connect through an approved Open Banking provider. Access is read only and can be revoked at any time.'}</p></div><em className={bankConnected?'connected':'not-connected'}><i/>{bankConnected?'Connected':'Not connected'}</em><Button variant="secondary" size="sm" onClick={()=>{if(bankConnected){setBankConnected(false);localStorage.setItem('vv-bank-connected','false');setWorkspace((current)=>({...current,bankBalance:undefined,bankProvider:undefined}))}else{const provider=window.prompt('Open Banking provider','TrueLayer');const balance=window.prompt('Current available balance (£)','0');if(provider&&balance!==null){setBankConnected(true);localStorage.setItem('vv-bank-connected','true');setWorkspace((current)=>({...current,bankProvider:provider,bankBalance:Number(balance)}))}}}}>{bankConnected?'Disconnect':'Connect account'}</Button></article>
          <article><span className="integration-icon"><CreditCard size={21}/></span><div><strong>Accounting platform</strong><p>{workspace.accountingProvider?`${workspace.accountingProvider} is selected. Add its API credentials at deployment to enable syncing.`:'Sync invoices and payment status with Xero, QuickBooks or Sage.'}</p></div><em className={workspace.accountingProvider?'connected':'not-connected'}><i/>{workspace.accountingProvider?'Configured':'Not connected'}</em><Button variant="secondary" size="sm" onClick={()=>{const provider=window.prompt('Provider: Xero, QuickBooks or Sage',workspace.accountingProvider??'Xero');if(provider)setWorkspaceField('accountingProvider',provider)}}>Choose provider</Button></article>
        </div><div className="settings-note"><KeyRound size={17}/><p>Financial integrations use read-only scopes by default. Bank balances are available only to administrators and finance users.</p></div></>}
        {section==='team'&&<><header><div><h2>Team & permissions</h2><p>Invite users, assign roles and suspend access.</p></div><Button size="sm" icon={UserPlus} onClick={()=>setInviting(true)}>Invite team member</Button></header><div className="role-summary">{roles.map((role)=><span key={role}><strong>{users.filter((p)=>p.role===role&&p.active).length}</strong>{role}</span>)}</div><div className="team-admin-list">{users.map((person)=><article key={person.id} className={!person.active?'suspended':''}><span style={{background:person.colour}}>{person.initials}</span><div><strong>{person.name}{person.id===user?.id&&<small>You</small>}</strong><p>{person.email}</p></div><div><strong>{person.role}</strong><p>{person.active?person.lastActive:'Access suspended'}</p></div><button onClick={()=>setEditing(person)}>Manage</button></article>)}</div></>}
        {section==='security'&&<><header><div><h2>Security & data</h2><p>Control authentication, audit records and workspace data.</p></div></header><div className="security-row"><span><ShieldCheck size={18}/></span><div><strong>Production authentication</strong><p>{productionAuth?'Supabase authentication is active. MFA policies are managed in Supabase.':'Local demonstration authentication is active. Connect Supabase before using real accounts.'}</p></div><em className={productionAuth?'connected':'not-connected'}>{productionAuth?'Active':'Setup required'}</em></div><div className="security-row"><span><BellRing size={18}/></span><div><strong>Login alerts</strong><p>Configure email delivery credentials to send unusual-login notifications.</p></div><em className="not-connected">Provider required</em></div><div className="security-row"><span><Database size={18}/></span><div><strong>Audit history</strong><p>{data.activities.length} recorded workspace actions.</p></div><Button variant="secondary" size="sm" onClick={()=>{const rows=data.activities.map((item)=>`${item.timestamp}\t${item.user}\t${item.title}\t${item.detail}`).join('\n');const blob=new Blob([rows],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='audit-history.txt';a.click();URL.revokeObjectURL(url)}}>Export audit log</Button></div><div className="danger-zone"><div><strong>Restore workspace sample records</strong><p>Replace changed records with the original Valechester workspace data.</p></div><Button variant="danger" size="sm" icon={RotateCcw} onClick={()=>{if(confirm('Restore the original workspace records?'))resetWorkspace()}}>Restore records</Button></div></>}
        <footer className="settings-save"><span>{saved&&<><Check size={14}/>Settings saved</>}</span><Button onClick={save}>Save changes</Button></footer>
      </section></div>
    {(inviting||editing)&&<UserDialog person={editing} onClose={()=>{setInviting(false);setEditing(null)}} onInvite={inviteUser} onUpdate={updateUser} onRemove={removeUser} onReset={resetPassword}/>} </div>
}

function UserDialog({person,onClose,onInvite,onUpdate,onRemove,onReset}:{person:WorkspaceUser|null;onClose:()=>void;onInvite:(input:Pick<WorkspaceUser,'name'|'email'|'role'>)=>void;onUpdate:(id:string,changes:Partial<Pick<WorkspaceUser,'name'|'email'|'role'|'active'>>)=>void;onRemove:(id:string)=>void;onReset:(id:string)=>void}){
 const [name,setName]=useState(person?.name??'');const [email,setEmail]=useState(person?.email??'');const [role,setRole]=useState<UserRole>(person?.role??'Content editor')
 const submit=(e:FormEvent)=>{e.preventDefault();if(person)onUpdate(person.id,{name,email,role});else onInvite({name,email,role});onClose()}
 return <div className="user-dialog-overlay" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><form className="user-dialog" onSubmit={submit}><header><div><h2>{person?'Manage team member':'Invite team member'}</h2><p>{person?'Update permissions or account status.':'Add a secure account to this destination workspace.'}</p></div><button type="button" onClick={onClose}><X size={19}/></button></header><Field label="Full name"><input value={name} onChange={(e)=>setName(e.target.value)} required/></Field><Field label="Email address"><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></Field><Field label="Workspace role"><select value={role} onChange={(e)=>setRole(e.target.value as UserRole)}>{roles.map((r)=><option key={r}>{r}</option>)}</select></Field><div className="permission-preview"><strong>Role access</strong><p>{role==='Administrator'?'Full workspace, finance, settings and user administration.':role==='Membership manager'?'Members, pipeline, listings, agreements and tasks.':role==='Finance user'?'Dashboard, organisations, billing and finance tasks.':'Dashboard, organisations, listings and content tasks.'}</p></div>{person&&<div className="user-secondary-actions"><button type="button" onClick={()=>onReset(person.id)}>Send password reset</button><button type="button" onClick={()=>onUpdate(person.id,{active:!person.active})}>{person.active?'Suspend access':'Restore access'}</button><button type="button" className="danger" onClick={()=>{if(confirm(`Remove ${person.name}?`)){onRemove(person.id);onClose()}}}>Remove user</button></div>}<footer><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit">{person?'Save user':'Send invitation'}</Button></footer></form></div>
}
