import { useState, type FormEvent } from 'react'
import { BarChart3, Beaker, Eye, Pause, Play, Plus, Square, Trash2, Users } from 'lucide-react'
import { Badge, Button, Field, Modal, PageHeader } from '../components/UI'
import { useCRM } from '../store'
import type { WebsiteExperiment, WebsiteExperimentGoal, WebsiteExperimentVariant } from '../types'

const goalLabels:Record<WebsiteExperimentGoal,string>={page_view:'Page view',cta_click:'CTA click',form_submit:'Form submission',booking_completed:'Booking completed'}

export function WebsiteExperiments({createRequest=0}:{createRequest?:number}){
  const {data,createWebsiteExperiment,updateWebsiteExperiment,deleteWebsiteExperiment}=useCRM()
  const [creating,setCreating]=useState(Boolean(createRequest))
  const start=(experiment:WebsiteExperiment)=>updateWebsiteExperiment(experiment.id,{status:'Running',startedAt:experiment.startedAt??new Date().toISOString(),endedAt:undefined})
  const changeStatus=(experiment:WebsiteExperiment,status:WebsiteExperiment['status'])=>updateWebsiteExperiment(experiment.id,{status,...(status==='Completed'?{endedAt:new Date().toISOString()}: {})})
  return <div><PageHeader eyebrow="Website" title="A/B testing" description="Test website messages safely, split traffic consistently and measure consented conversion events." actions={<Button icon={Plus} onClick={()=>setCreating(true)}>Create experiment</Button>}/><section className="experiment-guide"><Beaker size={21}/><div><strong>Experiments never change a CMS draft.</strong><p>A running test overlays its variant on the published page. Pause or complete it to return every visitor to the published control.</p></div></section><div className="experiment-list">{data.websiteExperiments.map((experiment)=>{
    const events=data.analyticsEvents.filter((event)=>event.experimentId===experiment.id)
    const results=experiment.variants.map((variant)=>{const assigned=events.filter((event)=>event.variantId===variant.id);const visitors=new Set(assigned.map((event)=>event.visitorId)).size;const conversions=assigned.filter((event)=>event.type===experiment.goal).length;return {variant,visitors,conversions,rate:visitors?conversions/visitors*100:0}})
    return <article className="panel experiment-card" key={experiment.id}><header><div><Badge>{experiment.status}</Badge><h2>{experiment.name}</h2><p>{experiment.hypothesis}</p></div><div className="event-row-actions">{['Draft','Paused'].includes(experiment.status)&&<Button size="sm" icon={Play} onClick={()=>start(experiment)}>Start</Button>}{experiment.status==='Running'&&<Button size="sm" variant="secondary" icon={Pause} onClick={()=>changeStatus(experiment,'Paused')}>Pause</Button>}{['Running','Paused'].includes(experiment.status)&&<Button size="sm" variant="secondary" icon={Square} onClick={()=>changeStatus(experiment,'Completed')}>Complete</Button>}{experiment.status==='Draft'&&<button className="icon-button danger" aria-label={`Delete ${experiment.name}`} onClick={()=>confirm(`Delete ${experiment.name}?`)&&deleteWebsiteExperiment(experiment.id)}><Trash2 size={16}/></button>}</div></header><div className="experiment-meta"><span><Eye size={15}/><strong>{experiment.pagePath}</strong> page</span><span><BarChart3 size={15}/><strong>{goalLabels[experiment.goal]}</strong> goal</span><span><Users size={15}/><strong>{new Set(events.map((event)=>event.visitorId)).size}</strong> visitors measured</span></div><div className="variant-results">{results.map(({variant,visitors,conversions,rate})=><section key={variant.id}><header><div><strong>{variant.name}</strong><span>{variant.weight}% traffic</span></div><Button size="sm" variant="ghost" onClick={()=>window.open(`${experiment.pagePath}?experiment=${experiment.id}&variant=${variant.id}`,'_blank','noopener,noreferrer')}>Preview</Button></header><blockquote>{variant.title}</blockquote><div className="variant-metrics"><span><small>Visitors</small><strong>{visitors}</strong></span><span><small>Conversions</small><strong>{conversions}</strong></span><span><small>Rate</small><strong>{rate.toFixed(1)}%</strong></span></div></section>)}</div>{experiment.status==='Running'&&!events.length&&<p className="experiment-empty">The test is live. Results will appear as consented visitors see the page and complete the selected goal.</p>}</article>})}</div>{creating&&<CreateExperiment onClose={()=>setCreating(false)} pagePaths={data.websitePages.map((page)=>page.path)} onCreate={(experiment)=>{createWebsiteExperiment(experiment);setCreating(false)}}/>}</div>
}

function CreateExperiment({onClose,onCreate,pagePaths}:{onClose:()=>void;onCreate:(experiment:Omit<WebsiteExperiment,'id'|'createdAt'>)=>void;pagePaths:string[]}){
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const path=String(form.get('pagePath'));const controlTitle=String(form.get('controlTitle'));const variants:WebsiteExperimentVariant[]=[{id:'control',name:'Control',weight:50,title:controlTitle,description:String(form.get('controlDescription')),buttonLabel:String(form.get('controlButton'))},{id:'variant-b',name:'Variant B',weight:50,title:String(form.get('variantTitle')),description:String(form.get('variantDescription')),buttonLabel:String(form.get('variantButton'))}];onCreate({name:String(form.get('name')),hypothesis:String(form.get('hypothesis')),pagePath:path,goal:String(form.get('goal')) as WebsiteExperimentGoal,status:'Draft',variants})}
  return <Modal title="Create A/B test" subtitle="Build the experiment as a draft, preview both versions, then start it when ready." onClose={onClose} width="lg"><form className="settings-form" onSubmit={submit}><Field label="Experiment name"><input name="name" required placeholder="Homepage autumn message"/></Field><Field label="Hypothesis"><textarea name="hypothesis" rows={2} required placeholder="We believe that… because…"/></Field><div className="form-grid two"><Field label="Page"><select name="pagePath">{pagePaths.map((path)=><option key={path}>{path}</option>)}</select></Field><Field label="Conversion goal"><select name="goal">{Object.entries(goalLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field></div><div className="variant-editor-grid"><fieldset><legend>Control</legend><Field label="Headline"><input name="controlTitle" required/></Field><Field label="Description"><textarea name="controlDescription" rows={3}/></Field><Field label="Button label"><input name="controlButton"/></Field></fieldset><fieldset><legend>Variant B</legend><Field label="Headline"><input name="variantTitle" required/></Field><Field label="Description"><textarea name="variantDescription" rows={3}/></Field><Field label="Button label"><input name="variantButton"/></Field></fieldset></div><footer className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save draft experiment</Button></footer></form></Modal>
}
