import { useState, type FormEvent } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { useAuth } from '../auth'
import { usePlatform, makePlatformId } from '../platform'
import { actionLabels, fieldLabels, triggerLabels, validateAutomation } from '../automationEngine'
import type { AutomationAction, AutomationCondition, AutomationRule, AutomationTrigger } from '../platformTypes'
import { Button, Field, Modal } from './UI'

const operators:AutomationCondition['operator'][]=['equals','not_equals','contains','before','after','within_days']
const emptyCondition=():AutomationCondition=>({field:'membership_tier',operator:'equals',value:''})
const emptyAction=():AutomationAction=>({type:'create_task',value:''})
function localDateTime(value?:string){if(!value)return'';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'':new Date(parsed.getTime()-parsed.getTimezoneOffset()*60000).toISOString().slice(0,16)}

export function AutomationBuilder({rule,onClose,onSave}:{rule?:AutomationRule;onClose:()=>void;onSave:(rule:AutomationRule)=>void}){
  const {user,users}=useAuth(),{data}=usePlatform()
  const [draft,setDraft]=useState<AutomationRule>(()=>rule?structuredClone(rule):{id:makePlatformId('auto'),name:'',description:'',trigger:'organisation_created',conditions:[],actions:[emptyAction()],active:false,createdAt:new Date().toISOString(),owner:user?.name??'',runs:0})
  const [error,setError]=useState('')
  const update=<K extends keyof AutomationRule>(key:K,value:AutomationRule[K])=>{setDraft((current)=>({...current,[key]:value}));setError('')}
  const updateCondition=(index:number,changes:Partial<AutomationCondition>)=>update('conditions',draft.conditions.map((item,position)=>position===index?{...item,...changes}:item))
  const updateAction=(index:number,changes:Partial<AutomationAction>)=>update('actions',draft.actions.map((item,position)=>position===index?{...item,...changes}:item))
  const save=(event:FormEvent)=>{event.preventDefault();const prepared={...draft,name:draft.name.trim(),description:draft.description.trim(),nextRun:undefined};const message=validateAutomation(prepared);if(message){setError(message);return}onSave(prepared)}
  return <Modal title={rule?'Edit automation':'New automation'} subtitle="Build a tenant-specific workflow. All actions are logged; emails are queued for review." onClose={onClose} width="lg">
    <form className="form-stack automation-builder" onSubmit={save}>
      <div className="form-grid two"><Field label="Name"><input autoFocus required value={draft.name} onChange={(event)=>update('name',event.target.value)}/></Field><Field label="Owner"><select required value={draft.owner} onChange={(event)=>update('owner',event.target.value)}><option value="">Choose a user</option>{users.filter((item)=>item.active&&item.tenantId===user?.tenantId).map((item)=><option key={item.id} value={item.name}>{item.name}</option>)}</select></Field></div>
      <Field label="Description"><textarea required rows={2} value={draft.description} onChange={(event)=>update('description',event.target.value)}/></Field>
      <label className="automation-active-label"><input type="checkbox" checked={draft.active} onChange={(event)=>update('active',event.target.checked)}/> Active after saving</label>
      <section className="automation-builder-section"><h3><span>WHEN</span> Trigger</h3><Field label="CRM event or schedule"><select value={draft.trigger} onChange={(event)=>{const trigger=event.target.value as AutomationTrigger;setDraft((current)=>({...current,trigger,interval:trigger==='scheduled_recurring'?current.interval??'daily':current.interval}));setError('')}}>{Object.entries(triggerLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>
        {['date_based','scheduled_recurring'].includes(draft.trigger)&&<div className="form-grid two"><Field label="Start date and time"><input required type="datetime-local" value={localDateTime(draft.scheduleAt)} onChange={(event)=>update('scheduleAt',event.target.value?new Date(event.target.value).toISOString():'')}/></Field>{draft.trigger==='scheduled_recurring'&&<Field label="Repeat"><select value={draft.interval??'daily'} onChange={(event)=>update('interval',event.target.value as AutomationRule['interval'])}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></Field>}</div>}
        {['date_based','scheduled_recurring'].includes(draft.trigger)&&<p>Scheduled runs evaluate each organisation in this destination against the conditions below.</p>}
      </section>
      <section className="automation-builder-section"><div className="automation-section-heading"><h3><span>IF</span> Conditions</h3><Button type="button" size="sm" variant="secondary" icon={Plus} onClick={()=>update('conditions',[...draft.conditions,emptyCondition()])}>Add condition</Button></div><p>All conditions must match. Leave empty to run for every matching event.</p>
        {draft.conditions.map((item,index)=><div className="automation-builder-row" key={index}><select aria-label={`Condition ${index+1} field`} value={item.field} onChange={(event)=>updateCondition(index,{field:event.target.value as AutomationCondition['field']})}>{Object.entries(fieldLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label={`Condition ${index+1} operator`} value={item.operator} onChange={(event)=>updateCondition(index,{operator:event.target.value as AutomationCondition['operator']})}>{operators.map((operator)=><option key={operator} value={operator}>{operator.replaceAll('_',' ')}</option>)}</select><input aria-label={`Condition ${index+1} value`} required value={item.value} placeholder="Value" onChange={(event)=>updateCondition(index,{value:event.target.value})}/><button type="button" aria-label={`Remove condition ${index+1}`} onClick={()=>update('conditions',draft.conditions.filter((_,position)=>position!==index))}><Trash2 size={16}/></button></div>)}
      </section>
      <section className="automation-builder-section"><div className="automation-section-heading"><h3><span>THEN</span> Actions</h3><Button type="button" size="sm" variant="secondary" icon={Plus} onClick={()=>update('actions',[...draft.actions,emptyAction()])}>Add action</Button></div><p>Actions run in order. A failed action stops the run and appears in history.</p>
        {draft.actions.map((item,index)=><div className="automation-builder-row" key={index}><select aria-label={`Action ${index+1} type`} value={item.type} onChange={(event)=>updateAction(index,{type:event.target.value as AutomationAction['type'],value:'',field:undefined})}>{Object.entries(actionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>
          {item.type==='update_field'&&<select aria-label={`Action ${index+1} field`} value={item.field??''} onChange={(event)=>updateAction(index,{field:event.target.value})}><option value="">Choose field</option>{['owner','nextAction','notes','town','type'].map((field)=><option key={field} value={field}>{field.replace(/([A-Z])/g,' $1')}</option>)}</select>}
          {item.type==='notify'&&<select aria-label={`Action ${index+1} recipient`} value={item.field??draft.owner} onChange={(event)=>updateAction(index,{field:event.target.value})}>{users.filter((person)=>person.active&&person.tenantId===user?.tenantId).map((person)=><option key={person.id} value={person.name}>{person.name}</option>)}</select>}
          {item.type==='add_to_campaign'?<select aria-label={`Action ${index+1} value`} required value={item.value} onChange={(event)=>updateAction(index,{value:event.target.value})}><option value="">Choose campaign</option>{data.campaigns.map((campaign)=><option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select>:item.type==='add_to_audience'?<select aria-label={`Action ${index+1} value`} required value={item.value} onChange={(event)=>updateAction(index,{value:event.target.value})}><option value="">Choose audience</option>{data.segments.map((segment)=><option key={segment.id} value={segment.id}>{segment.name}</option>)}</select>:item.type==='change_pipeline_stage'?<select aria-label={`Action ${index+1} value`} required value={item.value} onChange={(event)=>updateAction(index,{value:event.target.value})}><option value="">Choose stage</option>{['New lead','Qualified','Proposal','Decision','Won'].map((stage)=><option key={stage}>{stage}</option>)}</select>:item.type==='update_member_status'?<select aria-label={`Action ${index+1} value`} required value={item.value} onChange={(event)=>updateAction(index,{value:event.target.value})}><option value="">Choose status</option>{['Active','Renewing','Prospect','Free listing','Lapsed','Non-member'].map((status)=><option key={status}>{status}</option>)}</select>:<input aria-label={`Action ${index+1} value`} required value={item.value} placeholder={item.type==='assign_task'?'Assignee name':item.type==='queue_email'?'Email subject and queued body':'Action value'} onChange={(event)=>updateAction(index,{value:event.target.value})}/>}
          <button type="button" aria-label={`Remove action ${index+1}`} disabled={draft.actions.length===1} onClick={()=>update('actions',draft.actions.filter((_,position)=>position!==index))}><Trash2 size={16}/></button></div>)}
      </section>
      {error&&<p className="form-error" role="alert">{error}</p>}
      <div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">{rule?'Save automation':'Create automation'}</Button></div>
    </form>
  </Modal>
}
