import type { CRMData } from './types'
import { expandedContacts, expandedListings, expandedOrganisations, seededEvents, supplementalListings } from './seedExpansion'

export const initialData: CRMData = {
  organisations: [
    {
      id: 'org-001', name: 'Valechester Castle', type: 'Attraction', town: 'Castle Quarter',
      address: 'Castle Rise, Valechester, VC1 1AA', website: 'https://example.com/valechester-castle',
      tier: 'Tier 1', status: 'Active', health: 'Happy', owner: 'Morgan Lee',
      primaryContactId: 'con-001', renewalDate: '2027-08-31', membershipStart: '2026-09-01',
      annualValue: 3919, listings: 2, lastActivity: '2026-09-19T14:24:00Z',
      nextAction: 'Confirm Christmas campaign content', nextActionDate: '2026-09-23',
      tags: ['Major attraction', 'Family', 'Travel trade'],
      notes: 'Key strategic partner. Include in quarterly campaign planning and travel trade activity.', colour: '#6952d7',
    },
    {
      id: 'org-002', name: 'Riverside Playhouse', type: 'Arts & culture', town: 'Riverside',
      address: 'Waterside, Valechester, VC1 2RP', website: 'https://example.com/riverside-playhouse',
      tier: 'Tier 1', status: 'Active', health: 'Happy', owner: 'Alex Morgan',
      primaryContactId: 'con-002', renewalDate: '2027-08-31', membershipStart: '2026-09-01',
      annualValue: 3919, listings: 3, lastActivity: '2026-09-18T10:15:00Z',
      nextAction: 'Review winter programme listing', nextActionDate: '2026-09-22',
      tags: ['Theatre', 'Culture', 'Travel trade'], notes: 'High-profile content partner with multiple venues.', colour: '#db5f62',
    },
    {
      id: 'org-003', name: 'The Lantern House Hotel', type: 'Accommodation', town: 'Riverside',
      address: '8 Lantern Walk, Valechester, VC1 2LH', website: 'https://example.com/lantern-house',
      tier: 'Tier 2', status: 'Renewing', health: 'OK', owner: 'Morgan Lee', primaryContactId: 'con-003',
      renewalDate: '2026-09-30', membershipStart: '2025-10-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-17T09:40:00Z', nextAction: 'Call about renewal proposal', nextActionDate: '2026-09-21',
      tags: ['Hotel', 'Luxury', 'MICE'], notes: 'Renewal proposal sent. Interested in more MICE exposure.', colour: '#2a8f8a',
    },
    {
      id: 'org-004', name: 'Vale & Hearth Distillery', type: 'Food & drink', town: 'Willowmere',
      address: 'Mill Lane, Willowmere, VC4 5HG', website: 'https://example.com/vale-and-hearth',
      tier: 'Tier 2', status: 'Active', health: 'Happy', owner: 'Morgan Lee', primaryContactId: 'con-004',
      renewalDate: '2027-03-31', membershipStart: '2026-04-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-16T16:05:00Z', nextAction: 'Invite to October Tourism Forum', nextActionDate: '2026-09-24',
      tags: ['Experience', 'Food & drink', 'Groups'], notes: 'Good campaign contributor and strong bookable experience.', colour: '#d89232',
    },
    {
      id: 'org-005', name: 'Museum of Motion', type: 'Attraction', town: 'Eastgate',
      address: 'Foundry Road, Eastgate, VC3 0BJ', website: 'https://example.com/museum-of-motion',
      tier: 'Tier 2', status: 'Active', health: 'OK', owner: 'Morgan Lee', primaryContactId: 'con-005',
      renewalDate: '2027-01-31', membershipStart: '2026-02-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-12T12:30:00Z', nextAction: 'Request updated accessibility details', nextActionDate: '2026-09-26',
      tags: ['Museum', 'Family', 'Groups'], notes: 'Content needs a refresh before autumn half term.', colour: '#3875c5',
    },
    {
      id: 'org-006', name: 'Valechester Gallery & Park', type: 'Arts & culture', town: 'North Vale',
      address: 'Gallery Park, North Vale, VC3 9HZ', website: 'https://example.com/gallery-park',
      tier: 'Tier 3', status: 'Active', health: 'Happy', owner: 'Casey Reed', primaryContactId: 'con-006',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 571, listings: 1,
      lastActivity: '2026-09-18T15:20:00Z', nextAction: 'Approve new exhibition event', nextActionDate: '2026-09-21',
      tags: ['Gallery', 'Outdoors', 'Events'], notes: 'Regular event uploader. Strong imagery available.', colour: '#668f51',
    },
    {
      id: 'org-007', name: 'The Copper Fox', type: 'Food & drink', town: 'Market Vale',
      address: '10 Market Street, Valechester, VC1 4DP', website: 'https://example.com/copper-fox',
      tier: 'Tier 4', status: 'Active', health: 'Needs attention', owner: 'Casey Reed', primaryContactId: 'con-007',
      renewalDate: '2026-10-15', membershipStart: '2025-10-16', annualValue: 212, listings: 1,
      lastActivity: '2026-08-28T11:00:00Z', nextAction: 'Renewal call — no response to email', nextActionDate: '2026-09-21',
      tags: ['Restaurant', 'Town centre'], notes: 'Two renewal emails sent. Try primary contact by phone.', colour: '#c76887',
    },
    {
      id: 'org-008', name: 'Wren & Quill Books', type: 'Retail', town: 'Market Vale',
      address: '12 Market Arcade, Valechester, VC1 1JB', website: 'https://example.com/wren-and-quill',
      tier: 'Tier 4', status: 'Active', health: 'Happy', owner: 'Casey Reed', primaryContactId: 'con-008',
      renewalDate: '2027-05-31', membershipStart: '2026-06-01', annualValue: 212, listings: 1,
      lastActivity: '2026-09-15T09:10:00Z', nextAction: 'Add to independent shopping guide', nextActionDate: '2026-09-29',
      tags: ['Independent', 'Shopping'], notes: 'Enthusiastic new member; good source for local content.', colour: '#8f6b52',
    },
    {
      id: 'org-009', name: 'Old Orchard Gardens', type: 'Attraction', town: 'Castle Quarter',
      address: 'Orchard Close, Valechester, VC1 6HF', website: 'https://example.com/old-orchard-gardens',
      tier: 'Tier 4', status: 'Renewing', health: 'OK', owner: 'Casey Reed', primaryContactId: 'con-009',
      renewalDate: '2026-09-30', membershipStart: '2025-10-01', annualValue: 212, listings: 1,
      lastActivity: '2026-09-10T13:45:00Z', nextAction: 'Confirm PO reference for invoice', nextActionDate: '2026-09-22',
      tags: ['Gardens', 'Heritage', 'Volunteers'], notes: 'Requires PO before invoice can be processed.', colour: '#57a375',
    },
    {
      id: 'org-010', name: 'Riverside Gardens', type: 'Outdoors', town: 'Riverside',
      address: 'River Terrace, Valechester, VC1 4AA', website: 'https://example.com/riverside-gardens',
      tier: 'Free Listing', status: 'Free listing', health: 'OK', owner: 'Sam Taylor', primaryContactId: 'con-010',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 0, listings: 1,
      lastActivity: '2026-09-06T10:20:00Z', nextAction: 'Review seasonal opening information', nextActionDate: '2026-10-02',
      tags: ['Park', 'Free', 'Accessible'], notes: 'Public-space directory record. No invoice required.', colour: '#50a1a9',
    },
    {
      id: 'org-011', name: 'Marlow House', type: 'Food & drink', town: 'Market Vale',
      address: 'High Street, Valechester', website: 'https://example.com/marlow-house',
      tier: 'Tier 3', status: 'Active', health: 'OK', owner: 'Morgan Lee', primaryContactId: 'con-011',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 571, listings: 1,
      lastActivity: '2026-09-19T08:50:00Z', nextAction: 'Follow up after opening week', nextActionDate: '2026-10-05',
      tags: ['Restaurant', 'New opening', 'Prospect'], notes: 'Opening late September. Introductory call completed.', colour: '#223f63',
    },
    {
      id: 'org-012', name: 'Vale Executive Travel', type: 'Supplier', town: 'Valechester',
      address: 'Valechester, England', website: 'https://example.com/vale-executive-travel',
      tier: 'Supplier', status: 'Active', health: 'OK', owner: 'Morgan Lee', primaryContactId: 'con-012',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 495, listings: 1,
      lastActivity: '2026-09-18T11:10:00Z', nextAction: 'Send supplier membership proposal', nextActionDate: '2026-09-21',
      tags: ['Supplier', 'Transport', 'Travel trade'], notes: 'Strong fit for new Supplier membership.', colour: '#775c9f',
    },
    ...expandedOrganisations,
  ],
  contacts: [
    { id: 'con-001', organisationId: 'org-001', name: 'Laura Bennett', jobTitle: 'Partnerships Director', email: 'laura.bennett@example.com', phone: '01926 000 101', roles: ['Primary', 'Membership'], primary: true, portalAccess: true },
    { id: 'con-013', organisationId: 'org-001', name: 'Finance Team', jobTitle: 'Accounts', email: 'accounts.wc@example.com', phone: '01926 000 102', roles: ['Accounts'], portalAccess: false },
    { id: 'con-002', organisationId: 'org-002', name: 'James Hart', jobTitle: 'Head of Tourism', email: 'james.hart@example.com', phone: '01789 000 201', roles: ['Primary', 'Membership', 'Signatory'], primary: true, portalAccess: true },
    { id: 'con-014', organisationId: 'org-002', name: 'Emma Price', jobTitle: 'Campaigns Manager', email: 'emma.price@example.com', phone: '01789 000 202', roles: ['Marketing'], portalAccess: true },
    { id: 'con-003', organisationId: 'org-003', name: 'Sophie Martin', jobTitle: 'General Manager', email: 'sophie.martin@example.com', phone: '01789 000 301', roles: ['Primary', 'Signatory'], primary: true, portalAccess: true },
    { id: 'con-015', organisationId: 'org-003', name: 'Hotel Accounts', jobTitle: 'Finance Office', email: 'accounts.arden@example.com', phone: '01789 000 302', roles: ['Accounts'], portalAccess: false },
    { id: 'con-004', organisationId: 'org-004', name: 'Tom Walker', jobTitle: 'Visitor Experience Manager', email: 'tom.walker@example.com', phone: '01608 000 401', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-005', organisationId: 'org-005', name: 'Priya Shah', jobTitle: 'Marketing Manager', email: 'priya.shah@example.com', phone: '01926 000 501', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-006', organisationId: 'org-006', name: 'Rachel Moore', jobTitle: 'Communications Lead', email: 'rachel.moore@example.com', phone: '01926 000 601', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-007', organisationId: 'org-007', name: 'Daniel King', jobTitle: 'General Manager', email: 'daniel.king@example.com', phone: '01926 000 701', roles: ['Primary', 'Membership', 'Accounts'], primary: true, portalAccess: true },
    { id: 'con-008', organisationId: 'org-008', name: 'Julie Stevens', jobTitle: 'Owner', email: 'julie.stevens@example.com', phone: '01926 000 801', roles: ['Primary', 'Signatory', 'Accounts'], primary: true, portalAccess: true },
    { id: 'con-009', organisationId: 'org-009', name: 'Martin Green', jobTitle: 'Trustee', email: 'martin.green@example.com', phone: '01926 000 901', roles: ['Primary', 'Membership'], primary: true, portalAccess: true },
    { id: 'con-010', organisationId: 'org-010', name: 'Parks Team', jobTitle: 'Place Operations', email: 'parks@example.com', phone: '01926 000 010', roles: ['Primary'], primary: true, portalAccess: false },
    { id: 'con-011', organisationId: 'org-011', name: 'Hannah Ellis', jobTitle: 'Launch Marketing Manager', email: 'hannah.ellis@example.com', phone: '020 7000 0111', roles: ['Primary', 'Marketing'], primary: true, portalAccess: false },
    { id: 'con-012', organisationId: 'org-012', name: 'Mark Collins', jobTitle: 'Managing Director', email: 'mark.collins@example.com', phone: '01789 000 121', roles: ['Primary', 'Signatory'], primary: true, portalAccess: false },
    ...expandedContacts,
  ],
  benefits: [
    { id: 'ben-001', name: 'Enhanced website listing', kind: 'Ongoing', allowance: 1, category: 'Listing' },
    { id: 'ben-002', name: 'Social media features', kind: 'Allowance', allowance: 4, category: 'Marketing' },
    { id: 'ben-003', name: 'Dedicated member email', kind: 'Single use', allowance: 1, category: 'Marketing' },
    { id: 'ben-004', name: 'Campaign participation', kind: 'Allowance', allowance: 4, category: 'Marketing' },
    { id: 'ben-005', name: 'Tourism Forum places', kind: 'Allowance', allowance: 2, category: 'Networking' },
    { id: 'ben-006', name: 'Quarterly insight report', kind: 'Ongoing', allowance: 1, category: 'Insight' },
    { id: 'ben-007', name: 'Travel trade representation', kind: 'Ongoing', allowance: 1, category: 'Support' },
    { id: 'ben-008', name: 'Account planning session', kind: 'Allowance', allowance: 2, category: 'Support' },
  ],
  levels: [
    { id: 'level-001', name: 'Tier 1', price: 3919, description: 'Highest-profile partnership with strategic input and year-round campaign support.', colour: '#6d294f', benefits: ['ben-001','ben-002','ben-003','ben-004','ben-005','ben-006','ben-007','ben-008'], listingAllowance: 5, imageAllowance: 10, videoAllowance: 2, taxonomyAllowance: 12, active: true, members: 15 },
    { id: 'level-002', name: 'Tier 2', price: 1321, description: 'Enhanced visibility, campaigns and business development support.', colour: '#f0785e', benefits: ['ben-001','ben-002','ben-004','ben-005','ben-006','ben-007'], listingAllowance: 3, imageAllowance: 5, videoAllowance: 1, taxonomyAllowance: 10, active: true, members: 15 },
    { id: 'level-003', name: 'Tier 3', price: 571, description: 'A strong promotional package for growing visitor businesses.', colour: '#7a9a83', benefits: ['ben-001','ben-002','ben-004','ben-005','ben-006'], listingAllowance: 2, imageAllowance: 3, videoAllowance: 0, taxonomyAllowance: 8, active: true, members: 15 },
    { id: 'level-004', name: 'Tier 4', price: 212, description: 'Core membership and an enhanced presence across the destination.', colour: '#a86b78', benefits: ['ben-001','ben-005','ben-006'], listingAllowance: 1, imageAllowance: 1, videoAllowance: 0, taxonomyAllowance: 6, active: true, members: 15 },
    { id: 'level-005', name: 'Supplier', price: 495, description: 'For businesses supplying the visitor economy and destination partners.', colour: '#247a77', benefits: ['ben-001','ben-002','ben-005','ben-006','ben-007'], listingAllowance: 1, imageAllowance: 8, videoAllowance: 1, taxonomyAllowance: 8, active: true, members: 15 },
    { id: 'level-006', name: 'Free Listing', price: 0, description: 'A basic directory entry for eligible visitor businesses.', colour: '#7b8798', benefits: [], listingAllowance: 1, imageAllowance: 0, videoAllowance: 0, taxonomyAllowance: 3, active: true, members: 15 },
  ],
  benefitUsage: [
    { id: 'use-001', organisationId: 'org-001', benefitId: 'ben-002', used: 2, allowance: 4, note: 'Summer reels and family campaign', updatedAt: '2026-08-19' },
    { id: 'use-002', organisationId: 'org-001', benefitId: 'ben-003', used: 1, allowance: 1, note: 'May dedicated email', updatedAt: '2026-05-14' },
    { id: 'use-003', organisationId: 'org-001', benefitId: 'ben-004', used: 2, allowance: 4, updatedAt: '2026-08-30' },
    { id: 'use-004', organisationId: 'org-003', benefitId: 'ben-002', used: 1, allowance: 4, updatedAt: '2026-07-10' },
    { id: 'use-005', organisationId: 'org-003', benefitId: 'ben-004', used: 3, allowance: 4, updatedAt: '2026-09-01' },
    { id: 'use-006', organisationId: 'org-004', benefitId: 'ben-002', used: 3, allowance: 4, updatedAt: '2026-09-15' },
    { id: 'use-007', organisationId: 'org-005', benefitId: 'ben-004', used: 1, allowance: 4, updatedAt: '2026-07-28' },
  ],
  listings: [
    { id: 'list-001', organisationId: 'org-001', name: 'Valechester Castle', category: 'Castles & heritage', town: 'Castle Quarter', status: 'Published', completeness: 96, views: 18420, enquiries: 814, shortDescription: 'Climb the towers and uncover nine centuries of Valechester stories.', description: 'A landmark day out with sweeping views, atmospheric rooms, family trails and live stories in the historic heart of town.', website: 'https://example.com/valechester-castle', bookingUrl: 'https://example.com/valechester-castle/tickets', phone: '01926 555101', email: 'castle@example.com', openingHours: 'Open daily, times vary by season', facilities: ['Accessible route','Café','Parking','Family friendly','Great views'], searchTags: ['Great for families','Full-day experience','Interactive history','Outdoor experience','Accessible','Food available','On-site parking','Booking recommended'], reviewHighlights: ['Spectacular live shows','History brought to life','Impressive castle and grounds'], goodToKnow: ['Mostly outdoors','Lots of walking','Busy during school holidays'], lastUpdated: '2026-09-12', image: 'castle' },
    { id: 'list-002', organisationId: 'org-001', name: 'The Keep Lodges', category: 'Accommodation', town: 'Castle Quarter', status: 'Published', completeness: 88, views: 4930, enquiries: 230, shortDescription: 'Stay beside the old walls in beautifully designed family lodges.', description: 'Extend the adventure with an overnight stay beside the castle, complete with evening storytelling and breakfast.', website: 'https://example.com/keep-lodges', bookingUrl: 'https://example.com/keep-lodges/book', phone: '01926 555102', email: 'stays@example.com', openingHours: 'Open all year', facilities: ['Parking','Restaurant','Family rooms','Wi-Fi'], searchTags: ['Great for families','Romantic','Overnight stay','Food available','On-site parking','Accessible'], reviewHighlights: ['Memorable setting','Comfortable family stays','Excellent breakfast'], goodToKnow: ['Advance booking recommended','Evening access is for staying guests'], lastUpdated: '2026-08-28', image: 'lodge' },
    { id: 'list-003', organisationId: 'org-002', name: 'Riverside Playhouse', category: 'Theatre', town: 'Riverside', status: 'Published', completeness: 98, views: 15210, enquiries: 621, shortDescription: 'Bold live performance in a landmark theatre beside the water.', description: 'The Riverside Playhouse presents theatre, comedy and new writing throughout the year, with welcoming public spaces overlooking the Vale.', website: 'https://example.com/riverside-playhouse', bookingUrl: 'https://example.com/riverside-playhouse/whats-on', phone: '01926 555201', email: 'tickets@example.com', openingHours: 'Box office open daily', facilities: ['Accessible seating','Restaurant','Bar','Hearing loop'], searchTags: ['Rainy-day activity','Indoor attraction','Evening activity','Accessible','Suitable for groups','Food available','Booking recommended'], reviewHighlights: ['Excellent performances','Welcoming staff','Great riverside atmosphere'], goodToKnow: ['Arrive early for popular shows','Pre-theatre dining available'], lastUpdated: '2026-09-18', image: 'theatre' },
    { id: 'list-004', organisationId: 'org-003', name: 'The Lantern House Hotel', category: 'Hotels', town: 'Riverside', status: 'Published', completeness: 84, views: 3840, enquiries: 197, shortDescription: 'A characterful riverside hotel steps from the playhouse.', description: 'Relax in a warm, contemporary hotel with destination dining, a courtyard garden and the river on the doorstep.', website: 'https://example.com/lantern-house', bookingUrl: 'https://example.com/lantern-house/book', phone: '01926 555301', email: 'stay@example.com', openingHours: 'Open all year', facilities: ['Parking','Restaurant','Accessible rooms','Wi-Fi','Dog friendly'], searchTags: ['Romantic','Dog-friendly','Accessible','Overnight stay','Food available','On-site parking'], reviewHighlights: ['Peaceful rooms','Friendly team','Beautiful river views'], goodToKnow: ['Limited on-site parking','Accessible rooms should be requested'], lastUpdated: '2026-09-19', image: 'hotel' },
    { id: 'list-005', organisationId: 'org-004', name: 'Vale & Hearth Distillery', category: 'Experiences', town: 'Willowmere', status: 'Published', completeness: 91, views: 5620, enquiries: 308, shortDescription: 'Meet the makers behind Valechester’s small-batch gin and whisky.', description: 'Join a guided distillery tour, explore the craft and enjoy a tutored tasting in a restored riverside mill.', website: 'https://example.com/vale-and-hearth', bookingUrl: 'https://example.com/vale-and-hearth/tours', phone: '01926 555401', email: 'tours@example.com', openingHours: 'Tours daily, advance booking recommended', facilities: ['Parking','Shop','Accessible tour','Café'], searchTags: ['Rainy-day activity','Indoor attraction','Couples','Suitable for groups','Food available','On-site parking','Booking recommended'], reviewHighlights: ['Knowledgeable guides','Generous tastings','Fascinating craft story'], goodToKnow: ['Over-18s only for tastings','Tours include standing'], lastUpdated: '2026-09-15', image: 'distillery' },
    { id: 'list-006', organisationId: 'org-005', name: 'Museum of Motion', category: 'Museums', town: 'Eastgate', status: 'Published', completeness: 72, views: 6890, enquiries: 350, shortDescription: 'Ingenious machines, remarkable journeys and plenty to get hands-on with.', description: 'Discover two centuries of transport and invention through beautifully restored vehicles and interactive family galleries.', website: 'https://example.com/museum-of-motion', bookingUrl: 'https://example.com/museum-of-motion/visit', phone: '01926 555501', email: 'enquiries@example.com', openingHours: 'Daily 10am–5pm', facilities: ['Parking','Café','Accessible','Family activities'], searchTags: ['Great for families','Rainy-day activity','Indoor attraction','Accessible','Free for under 5s','Food available','On-site parking'], reviewHighlights: ['Hands-on galleries','Friendly explainers','Great family day out'], goodToKnow: ['Allow at least three hours','Some busy sensory spaces'], lastUpdated: '2026-07-02', image: 'museum' },
    { id: 'list-007', organisationId: 'org-006', name: 'Valechester Gallery & Park', category: 'Galleries', town: 'North Vale', status: 'Published', completeness: 94, views: 4770, enquiries: 214, shortDescription: 'Contemporary art and historic collections in 80 acres of parkland.', description: 'Explore ambitious exhibitions, local stories and peaceful landscaped parkland in one inspiring day out.', website: 'https://example.com/gallery-park', bookingUrl: 'https://example.com/gallery-park/tickets', phone: '01926 555601', email: 'gallery@example.com', openingHours: 'Tue–Sun, 10.30am–5pm', facilities: ['Parking','Café','Accessible','Families','Picnic area'], searchTags: ['Rainy-day activity','Outdoor experience','Accessible','Great for families','Dog-friendly','Food available','On-site parking','Free outdoor spaces'], reviewHighlights: ['Beautiful grounds','Thought-provoking exhibitions','Peaceful atmosphere'], goodToKnow: ['Gallery tickets and park access differ','Dogs are limited to outdoor areas'], lastUpdated: '2026-09-01', image: 'gallery' },
    { id: 'list-008', organisationId: 'org-007', name: 'The Copper Fox', category: 'Restaurants', town: 'Market Vale', status: 'Published', completeness: 58, views: 1040, enquiries: 38, shortDescription: 'A relaxed dining room celebrating the best of the Vale.', description: 'Seasonal food, local drinks and welcoming service just moments from Valechester’s historic market square.', website: 'https://example.com/copper-fox', bookingUrl: '', phone: '01926 555701', email: 'hello@example.com', openingHours: 'Daily from 8am', facilities: ['Restaurant','Bar','Rooms','Wi-Fi'], searchTags: ['Romantic','Food available','Evening activity','Accessible','Dog-friendly'], reviewHighlights: ['Warm service','Seasonal menu','Relaxed atmosphere'], goodToKnow: ['Booking recommended at weekends','Street parking nearby'], lastUpdated: '2026-06-20', image: 'restaurant' },
    { id: 'list-009', organisationId: 'org-008', name: 'Wren & Quill Books', category: 'Shopping', town: 'Market Vale', status: 'Published', completeness: 82, views: 870, enquiries: 21, shortDescription: 'A much-loved independent bookshop with a distinctly local point of view.', description: 'Browse a thoughtful collection, meet visiting writers and discover the stories that shaped the Vale.', website: 'https://example.com/wren-and-quill', bookingUrl: '', phone: '01926 555801', email: 'books@example.com', openingHours: 'Mon–Sat 9.30am–5pm', facilities: ['Town centre','Accessible entrance','Events'], searchTags: ['Rainy-day activity','Indoor attraction','Free to visit','Accessible','Independent shopping'], reviewHighlights: ['Helpful booksellers','Excellent local selection','Characterful shop'], goodToKnow: ['Events may require tickets','Step-free entrance at the side'], lastUpdated: '2026-09-10', image: 'books' },
    { id: 'list-010', organisationId: 'org-009', name: 'Old Orchard Gardens', category: 'Gardens', town: 'Castle Quarter', status: 'Published', completeness: 79, views: 1260, enquiries: 44, shortDescription: 'Restored Victorian gardens tucked behind the old town walls.', description: 'Step into a rare group of historic leisure gardens, complete with summerhouses, heritage fruit and seasonal planting.', website: 'https://example.com/old-orchard-gardens', bookingUrl: '', phone: '01926 555901', email: 'visit@example.com', openingHours: 'Open most weekdays and weekends; check before travel', facilities: ['Tea room','Accessible routes','Gardens'], searchTags: ['Outdoor experience','Romantic','Peaceful','Heritage','Food available','Accessible'], reviewHighlights: ['Beautiful planting','Hidden gem','Relaxing visit'], goodToKnow: ['Opening days vary','Paths can be uneven after rain'], lastUpdated: '2026-08-14', image: 'gardens' },
    { id: 'list-011', organisationId: 'org-010', name: 'Riverside Gardens', category: 'Parks & gardens', town: 'Riverside', status: 'Published', completeness: 68, views: 2380, enquiries: 60, shortDescription: 'Elegant public gardens following the curve of the River Vale.', description: 'Stroll through formal gardens, visit the glasshouse or simply pause beside the river with the town skyline beyond.', website: 'https://example.com/riverside-gardens', bookingUrl: '', phone: '', email: '', openingHours: 'Open daily', facilities: ['Free entry','Accessible paths','Café','Play area'], searchTags: ['Free to visit','Great for families','Dog-friendly','Outdoor experience','Accessible','Food available'], reviewHighlights: ['Beautiful riverside walks','Well-kept gardens','Relaxing atmosphere'], goodToKnow: ['Cycling is restricted in formal gardens','Café opening varies seasonally'], lastUpdated: '2026-07-30', image: 'park' },
    ...supplementalListings,
    ...expandedListings,
  ],
  events: seededEvents,
  invoices: [
    { id: 'inv-001', number: 'VV-2026-1048', organisationId: 'org-001', description: 'Tier 1 membership 2026/27', issueDate: '2026-09-01', dueDate: '2026-09-30', subtotal: 3919, vat: 783.8, total: 4702.8, status: 'Sent', remindersPaused: false, reminderStep: 0, sentTo: 'accounts.castle@example.com' },
    { id: 'inv-002', number: 'VV-2026-1049', organisationId: 'org-002', description: 'Tier 1 membership 2026/27', issueDate: '2026-09-01', dueDate: '2026-09-30', subtotal: 3919, vat: 783.8, total: 4702.8, status: 'Paid', remindersPaused: false, reminderStep: 0, sentTo: 'james.hart@example.com', paidAt: '2026-09-12' },
    { id: 'inv-003', number: 'VV-2026-1018', organisationId: 'org-003', description: 'Tier 2 membership renewal', issueDate: '2026-08-20', dueDate: '2026-09-19', subtotal: 1321, vat: 264.2, total: 1585.2, status: 'Overdue', remindersPaused: false, reminderStep: 1, sentTo: 'accounts.lantern@example.com' },
    { id: 'inv-004', number: 'VV-2026-1055', organisationId: 'org-006', description: 'Tier 3 membership 2026/27', issueDate: '2026-09-02', dueDate: '2026-10-02', subtotal: 571, vat: 114.2, total: 685.2, status: 'Sent', remindersPaused: false, reminderStep: 0, sentTo: 'rachel.moore@example.com' },
    { id: 'inv-005', number: 'VV-2026-0992', organisationId: 'org-007', description: 'Tier 4 membership renewal', issueDate: '2026-08-01', dueDate: '2026-08-31', subtotal: 212, vat: 42.4, total: 254.4, status: 'Overdue', remindersPaused: true, reminderStep: 2, sentTo: 'daniel.king@example.com' },
    { id: 'inv-006', number: 'VV-2026-1059', organisationId: 'org-008', description: 'Tier 4 membership 2026/27', issueDate: '2026-09-05', dueDate: '2026-10-05', subtotal: 212, vat: 42.4, total: 254.4, status: 'Draft', remindersPaused: false, reminderStep: 0, sentTo: 'julie.stevens@example.com' },
    { id: 'inv-007', number: 'VV-2026-1004', organisationId: 'org-009', description: 'Tier 4 membership renewal', issueDate: '2026-08-12', dueDate: '2026-09-11', subtotal: 212, vat: 42.4, total: 254.4, status: 'Overdue', remindersPaused: true, reminderStep: 1, sentTo: 'martin.green@example.com' },
    { id: 'inv-008', number: 'VV-2026-0975', organisationId: 'org-004', description: 'Tier 2 membership 2026/27', issueDate: '2026-07-15', dueDate: '2026-08-14', subtotal: 1321, vat: 264.2, total: 1585.2, status: 'Paid', remindersPaused: false, reminderStep: 0, sentTo: 'tom.walker@example.com', paidAt: '2026-08-10' },
  ],
  agreements: [
    { id: 'agr-001', number: 'AGR-2026-088', organisationId: 'org-001', membershipLevel: 'Tier 1', signatory: 'Laura Bennett', signatoryEmail: 'laura.bennett@example.com', status: 'Signed', createdAt: '2026-08-20', sentAt: '2026-08-22', signedAt: '2026-08-25', validUntil: '2027-08-31' },
    { id: 'agr-002', number: 'AGR-2026-091', organisationId: 'org-002', membershipLevel: 'Tier 1', signatory: 'James Hart', signatoryEmail: 'james.hart@example.com', status: 'Signed', createdAt: '2026-08-24', sentAt: '2026-08-25', signedAt: '2026-08-29', validUntil: '2027-08-31' },
    { id: 'agr-003', number: 'AGR-2026-104', organisationId: 'org-003', membershipLevel: 'Tier 2', signatory: 'Sophie Martin', signatoryEmail: 'sophie.martin@example.com', status: 'Viewed', createdAt: '2026-09-10', sentAt: '2026-09-11', validUntil: '2026-10-01' },
    { id: 'agr-004', number: 'AGR-2026-108', organisationId: 'org-007', membershipLevel: 'Tier 4', signatory: 'Daniel King', signatoryEmail: 'daniel.king@example.com', status: 'Sent', createdAt: '2026-09-14', sentAt: '2026-09-15', validUntil: '2026-10-15' },
    { id: 'agr-005', number: 'AGR-2026-112', organisationId: 'org-009', membershipLevel: 'Tier 4', signatory: 'Martin Green', signatoryEmail: 'martin.green@example.com', status: 'Draft', createdAt: '2026-09-18', validUntil: '2026-10-20' },
  ],
  tasks: [
    { id: 'task-001', title: 'Call The Lantern House Hotel about renewal', organisationId: 'org-003', dueDate: '2026-09-21', dueTime: '10:00', priority: 'High', assignee: 'Morgan Lee', category: 'Renewal', completed: false },
    { id: 'task-002', title: 'Send supplier proposal to Vale Executive Travel', organisationId: 'org-012', dueDate: '2026-09-21', dueTime: '12:00', priority: 'High', assignee: 'Morgan Lee', category: 'Follow-up', completed: false },
    { id: 'task-003', title: 'Approve Gallery & Park exhibition event', organisationId: 'org-006', dueDate: '2026-09-21', dueTime: '15:00', priority: 'Medium', assignee: 'Casey Reed', category: 'Content', completed: false },
    { id: 'task-004', title: 'Review overdue invoices and reminder pauses', dueDate: '2026-09-22', priority: 'High', assignee: 'Alex Morgan', category: 'Finance', completed: false },
    { id: 'task-005', title: 'Confirm winter content with Valechester Castle', organisationId: 'org-001', dueDate: '2026-09-23', priority: 'Medium', assignee: 'Sam Taylor', category: 'Content', completed: false },
    { id: 'task-006', title: 'Invite Vale & Hearth to Tourism Forum', organisationId: 'org-004', dueDate: '2026-09-24', priority: 'Low', assignee: 'Casey Reed', category: 'General', completed: false },
    { id: 'task-007', title: 'Update Museum of Motion accessibility copy', organisationId: 'org-005', dueDate: '2026-09-19', priority: 'Medium', assignee: 'Sam Taylor', category: 'Content', completed: false },
    { id: 'task-008', title: 'Record Playhouse membership payment', organisationId: 'org-002', dueDate: '2026-09-12', priority: 'High', assignee: 'Alex Morgan', category: 'Finance', completed: true },
  ],
  opportunities: [
    { id: 'opp-001', organisationName: 'Marlow House', contactName: 'Hannah Ellis', stage: 'Qualified', proposedLevel: 'Tier 3', value: 571, probability: 35, source: 'New opening', nextAction: 'Follow up after opening week', nextActionDate: '2026-10-05', owner: 'Morgan Lee', daysInStage: 3 },
    { id: 'opp-002', organisationName: 'Vale Executive Travel', contactName: 'Mark Collins', stage: 'Proposal', proposedLevel: 'Supplier', value: 495, probability: 60, source: 'Referral', nextAction: 'Send membership proposal', nextActionDate: '2026-09-21', owner: 'Morgan Lee', daysInStage: 2 },
    { id: 'opp-003', organisationName: 'The Vale Arms', contactName: 'Olivia Turner', stage: 'New lead', proposedLevel: 'Tier 3', value: 571, probability: 15, source: 'Website enquiry', nextAction: 'Initial discovery call', nextActionDate: '2026-09-23', owner: 'Morgan Lee', daysInStage: 1 },
    { id: 'opp-004', organisationName: 'Johnson’s Coaches', contactName: 'Peter Johnson', stage: 'Qualified', proposedLevel: 'Supplier', value: 495, probability: 40, source: 'Travel trade', nextAction: 'Discuss group market benefits', nextActionDate: '2026-09-25', owner: 'Morgan Lee', daysInStage: 8 },
    { id: 'opp-005', organisationName: 'No. 34 Garden & Grill', contactName: 'Amelia Reed', stage: 'Decision', proposedLevel: 'Tier 4', value: 212, probability: 80, source: 'Team prospecting', nextAction: 'Confirm signatory details', nextActionDate: '2026-09-22', owner: 'Morgan Lee', daysInStage: 4 },
    { id: 'opp-006', organisationName: 'Vox City International', contactName: 'Alex Rossi', stage: 'Proposal', proposedLevel: 'Supplier', value: 495, probability: 55, source: 'WTM', nextAction: 'Share destination distribution plan', nextActionDate: '2026-09-28', owner: 'Morgan Lee', daysInStage: 11 },
    { id: 'opp-007', organisationName: 'Riverside Escapes', contactName: 'Nadia Ahmed', stage: 'New lead', proposedLevel: 'Tier 2', value: 1321, probability: 15, source: 'Member referral', nextAction: 'Research opening timeline', nextActionDate: '2026-09-24', owner: 'Morgan Lee', daysInStage: 2 },
    { id: 'opp-008', organisationName: 'Valechester Gin Co.', contactName: 'Ben Clarke', stage: 'Won', proposedLevel: 'Tier 3', value: 571, probability: 100, source: 'Tourism Forum', nextAction: 'Start onboarding', nextActionDate: '2026-09-21', owner: 'Morgan Lee', daysInStage: 1 },
  ],
  activities: [
    { id: 'act-001', organisationId: 'org-001', type: 'email', title: 'Campaign email sent', detail: 'Christmas campaign content request sent to Laura.', timestamp: '2026-09-19T14:24:00Z', user: 'Sam Taylor' },
    { id: 'act-002', organisationId: 'org-003', type: 'listing', title: 'Listing update submitted', detail: 'The Lantern House Hotel submitted new winter copy and images for review.', timestamp: '2026-09-19T09:30:00Z', user: 'Business portal' },
    { id: 'act-003', organisationId: 'org-012', type: 'note', title: 'Discovery call completed', detail: 'Good fit for Supplier membership; interested in travel trade introductions.', timestamp: '2026-09-18T11:10:00Z', user: 'Morgan Lee' },
    { id: 'act-004', organisationId: 'org-006', type: 'listing', title: 'Event submitted', detail: 'New autumn exhibition event is waiting for approval.', timestamp: '2026-09-18T10:05:00Z', user: 'Business portal' },
    { id: 'act-005', organisationId: 'org-002', type: 'invoice', title: 'Invoice marked paid', detail: 'VV-2026-1049 marked paid in full.', timestamp: '2026-09-12T16:40:00Z', user: 'Alex Morgan' },
    { id: 'act-006', organisationId: 'org-003', type: 'agreement', title: 'Agreement viewed', detail: 'Sophie Martin opened agreement AGR-2026-104.', timestamp: '2026-09-12T08:14:00Z', user: 'System' },
  ],
  socialMetrics: [
    { id: 'followers', label: 'Total followers', value: 112000, displayValue: '112k', context: '+89% year on year', source: 'Visit Valechester', period: 'Latest supplied annual figures', updatedAt: '2026-08-19' },
    { id: 'reach', label: 'Content reach', value: 11000000, displayValue: '11m', context: 'Latest annual total', source: 'Visit Valechester', period: 'Latest supplied annual figures', updatedAt: '2026-08-19' },
    { id: 'videoViews', label: 'Video views', value: 22500000, displayValue: '22.5m', context: 'Across social channels', source: 'Visit Valechester', period: 'Latest supplied annual figures', updatedAt: '2026-08-19' },
    { id: 'engagements', label: 'Engagements', value: 801000, displayValue: '801k', context: 'Reactions and actions', source: 'Visit Valechester', period: 'Latest supplied annual figures', updatedAt: '2026-08-19' },
  ],
  contentPages: [
    {id:'content-001',type:'Guide',title:'A rainy day in Valechester',slug:'rainy-day-valechester',summary:'Indoor culture, food and family ideas for wet-weather visits.',body:'Start with the Museum of Motion, pause for lunch in Market Vale and finish with a performance at Riverside Playhouse.',image:'museum',status:'Published',updatedAt:'2026-09-20'},
    {id:'content-002',type:'Itinerary',title:'48 hours in Valechester',slug:'48-hours-in-valechester',summary:'A two-day introduction to the castle, riverside and independent quarter.',body:'Day one explores Castle Quarter and Market Vale. Day two follows the river to the gallery and park.',image:'castle',status:'Draft',updatedAt:'2026-09-20'},
    {id:'content-003',type:'Trail',title:'Castle Quarter heritage trail',slug:'castle-quarter-heritage-trail',summary:'A self-guided walk through the oldest streets in Valechester.',body:'Follow the signed route from Market Gate to the castle walls, abbey gardens and river viewpoint.',image:'gardens',status:'Published',updatedAt:'2026-09-20'},
  ],
  analyticsEvents: [
    {id:'web-001',type:'page_view',path:'/',title:'Visit Valechester',visitorId:'visitor-001',source:'Google',campaign:'autumn-breaks',occurredAt:'2026-09-22T08:14:00Z'},
    {id:'web-002',type:'page_view',path:'/place/list-001',title:'Valechester Castle',visitorId:'visitor-001',source:'Google',campaign:'autumn-breaks',occurredAt:'2026-09-22T08:16:00Z'},
    {id:'web-003',type:'cta_click',path:'/place/list-001',title:'Book Valechester Castle',visitorId:'visitor-001',source:'Google',campaign:'autumn-breaks',occurredAt:'2026-09-22T08:18:00Z'},
    {id:'web-004',type:'page_view',path:'/events',title:"What's on in Valechester",visitorId:'visitor-002',source:'Direct',occurredAt:'2026-09-22T09:02:00Z'},
    {id:'web-005',type:'page_view',path:'/guides/rainy-day-valechester',title:'A rainy day in Valechester',visitorId:'visitor-003',source:'Facebook',occurredAt:'2026-09-21T18:42:00Z'},
    {id:'web-006',type:'page_view',path:'/place/list-003',title:'Riverside Playhouse',visitorId:'visitor-003',source:'Facebook',occurredAt:'2026-09-21T18:46:00Z'},
    {id:'web-007',type:'form_submit',path:'/contact',title:'Visitor enquiry',visitorId:'visitor-003',source:'Facebook',occurredAt:'2026-09-21T18:51:00Z'},
    {id:'web-008',type:'page_view',path:'/',title:'Visit Valechester',visitorId:'visitor-004',source:'Instagram',campaign:'weekend-in-the-vale',occurredAt:'2026-09-20T11:20:00Z'},
    {id:'web-009',type:'page_view',path:'/plan',title:'Plan your visit',visitorId:'visitor-004',source:'Instagram',campaign:'weekend-in-the-vale',occurredAt:'2026-09-20T11:22:00Z'},
    {id:'web-010',type:'page_view',path:'/place/list-004',title:'The Lantern House Hotel',visitorId:'visitor-004',source:'Instagram',campaign:'weekend-in-the-vale',occurredAt:'2026-09-20T11:25:00Z'},
    {id:'web-011',type:'booking_completed',path:'/place/list-004',title:'Hotel booking completed',visitorId:'visitor-004',source:'Instagram',campaign:'weekend-in-the-vale',occurredAt:'2026-09-20T11:31:00Z'},
    {id:'web-012',type:'page_view',path:'/trails/castle-quarter-heritage-trail',title:'Castle Quarter heritage trail',visitorId:'visitor-005',source:'Newsletter',occurredAt:'2026-09-19T07:55:00Z'},
  ],
  submissions: [],
  workspace: {
    destinationName: 'Visit Valechester', legalName: 'Valechester Visitor Economy Partnership',
    strapline: 'Past, present, perfectly placed.', contactEmail: 'hello@visitvalechester.example',
    address: 'Valechester Visitor Economy Partnership, Valechester, England', timezone: 'Europe/London', currency: 'GBP',
    financialYearStart: 'September', membershipYearStart: '1 September', primaryColour: '#6d294f', accentColour: '#f0785e', supportingColour: '#7a9a83',
    visitorVolume: 5800000, visitorSpend: 412000000, overnightStays: 1240000,
  },
}

export const typeOptions = ['Accommodation', 'Attraction', 'Arts & culture', 'Food & drink', 'Retail', 'Outdoors', 'Supplier', 'Other']
export const townOptions = ['Valechester', 'Castle Quarter', 'Riverside', 'Market Vale', 'Eastgate', 'North Vale', 'Willowmere', 'Other']
