import type { CRMData } from './types'

export const demoData: CRMData = {
  organisations: [
    {
      id: 'org-001', name: 'Warwick Castle', type: 'Attraction', town: 'Warwick',
      address: 'Castle Hill, Warwick, CV34 4QU', website: 'https://www.warwick-castle.com',
      tier: 'Strategic', status: 'Active', health: 'Happy', owner: 'Vicki Zamudio',
      primaryContactId: 'con-001', renewalDate: '2027-08-31', membershipStart: '2026-09-01',
      annualValue: 3919, listings: 2, lastActivity: '2026-09-19T14:24:00Z',
      nextAction: 'Confirm Christmas campaign content', nextActionDate: '2026-09-23',
      tags: ['Major attraction', 'Family', 'Travel trade'],
      notes: 'Key strategic partner. Include in quarterly campaign planning and travel trade activity.', colour: '#6952d7',
    },
    {
      id: 'org-002', name: 'Royal Shakespeare Company', type: 'Arts & culture', town: 'Stratford-upon-Avon',
      address: 'Waterside, Stratford-upon-Avon, CV37 6BB', website: 'https://www.rsc.org.uk',
      tier: 'Strategic', status: 'Active', health: 'Happy', owner: 'Darren Tosh',
      primaryContactId: 'con-002', renewalDate: '2027-08-31', membershipStart: '2026-09-01',
      annualValue: 3919, listings: 3, lastActivity: '2026-09-18T10:15:00Z',
      nextAction: 'Review winter programme listing', nextActionDate: '2026-09-22',
      tags: ['Theatre', 'Culture', 'Travel trade'], notes: 'High-profile content partner with multiple venues.', colour: '#db5f62',
    },
    {
      id: 'org-003', name: 'The Arden Hotel', type: 'Accommodation', town: 'Stratford-upon-Avon',
      address: 'Waterside, Stratford-upon-Avon, CV37 6BA', website: 'https://www.theardenhotelstratford.com',
      tier: 'Gold', status: 'Renewing', health: 'OK', owner: 'Vicki Zamudio', primaryContactId: 'con-003',
      renewalDate: '2026-09-30', membershipStart: '2025-10-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-17T09:40:00Z', nextAction: 'Call about renewal proposal', nextActionDate: '2026-09-21',
      tags: ['Hotel', 'Luxury', 'MICE'], notes: 'Renewal proposal sent. Interested in more MICE exposure.', colour: '#2a8f8a',
    },
    {
      id: 'org-004', name: 'Cotswolds Distillery', type: 'Food & drink', town: 'Shipston-on-Stour',
      address: 'Phillip’s Field, Stourton, CV36 5HG', website: 'https://www.cotswoldsdistillery.com',
      tier: 'Gold', status: 'Active', health: 'Happy', owner: 'Vicki Zamudio', primaryContactId: 'con-004',
      renewalDate: '2027-03-31', membershipStart: '2026-04-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-16T16:05:00Z', nextAction: 'Invite to October Tourism Forum', nextActionDate: '2026-09-24',
      tags: ['Experience', 'Food & drink', 'Groups'], notes: 'Good campaign contributor and strong bookable experience.', colour: '#d89232',
    },
    {
      id: 'org-005', name: 'British Motor Museum', type: 'Attraction', town: 'Gaydon',
      address: 'Banbury Road, Gaydon, CV35 0BJ', website: 'https://www.britishmotormuseum.co.uk',
      tier: 'Gold', status: 'Active', health: 'OK', owner: 'Vicki Zamudio', primaryContactId: 'con-005',
      renewalDate: '2027-01-31', membershipStart: '2026-02-01', annualValue: 1321, listings: 2,
      lastActivity: '2026-09-12T12:30:00Z', nextAction: 'Request updated accessibility details', nextActionDate: '2026-09-26',
      tags: ['Museum', 'Family', 'Groups'], notes: 'Content needs a refresh before autumn half term.', colour: '#3875c5',
    },
    {
      id: 'org-006', name: 'Compton Verney', type: 'Arts & culture', town: 'Warwick',
      address: 'Compton Verney, Warwickshire, CV35 9HZ', website: 'https://www.comptonverney.org.uk',
      tier: 'Silver', status: 'Active', health: 'Happy', owner: 'Sian Cooper', primaryContactId: 'con-006',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 571, listings: 1,
      lastActivity: '2026-09-18T15:20:00Z', nextAction: 'Approve new exhibition event', nextActionDate: '2026-09-21',
      tags: ['Gallery', 'Outdoors', 'Events'], notes: 'Regular event uploader. Strong imagery available.', colour: '#668f51',
    },
    {
      id: 'org-007', name: 'The Globe', type: 'Food & drink', town: 'Warwick',
      address: '10 Theatre Street, Warwick, CV34 4DP', website: 'https://www.theglobewarwick.co.uk',
      tier: 'Bronze', status: 'Active', health: 'Needs attention', owner: 'Sian Cooper', primaryContactId: 'con-007',
      renewalDate: '2026-10-15', membershipStart: '2025-10-16', annualValue: 212, listings: 1,
      lastActivity: '2026-08-28T11:00:00Z', nextAction: 'Renewal call — no response to email', nextActionDate: '2026-09-21',
      tags: ['Restaurant', 'Town centre'], notes: 'Two renewal emails sent. Try primary contact by phone.', colour: '#c76887',
    },
    {
      id: 'org-008', name: 'Kenilworth Books', type: 'Retail', town: 'Kenilworth',
      address: '12 Talisman Square, Kenilworth, CV8 1JB', website: 'https://www.kenilworthbooks.co.uk',
      tier: 'Bronze', status: 'Active', health: 'Happy', owner: 'Sian Cooper', primaryContactId: 'con-008',
      renewalDate: '2027-05-31', membershipStart: '2026-06-01', annualValue: 212, listings: 1,
      lastActivity: '2026-09-15T09:10:00Z', nextAction: 'Add to independent shopping guide', nextActionDate: '2026-09-29',
      tags: ['Independent', 'Shopping'], notes: 'Enthusiastic new member; good source for local content.', colour: '#8f6b52',
    },
    {
      id: 'org-009', name: 'Hill Close Gardens', type: 'Attraction', town: 'Warwick',
      address: 'Bread and Meat Close, Warwick, CV34 6HF', website: 'https://www.hillclosegardens.com',
      tier: 'Bronze', status: 'Renewing', health: 'OK', owner: 'Sian Cooper', primaryContactId: 'con-009',
      renewalDate: '2026-09-30', membershipStart: '2025-10-01', annualValue: 212, listings: 1,
      lastActivity: '2026-09-10T13:45:00Z', nextAction: 'Confirm PO reference for invoice', nextActionDate: '2026-09-22',
      tags: ['Gardens', 'Heritage', 'Volunteers'], notes: 'Requires PO before invoice can be processed.', colour: '#57a375',
    },
    {
      id: 'org-010', name: 'Jephson Gardens', type: 'Outdoors', town: 'Royal Leamington Spa',
      address: 'Newbold Terrace, Leamington Spa, CV32 4AA', website: 'https://www.warwickdc.gov.uk',
      tier: 'Free Listing', status: 'Free listing', health: 'OK', owner: 'Hannah Ward', primaryContactId: 'con-010',
      renewalDate: '2027-08-31', membershipStart: '2026-09-01', annualValue: 0, listings: 1,
      lastActivity: '2026-09-06T10:20:00Z', nextAction: 'Review seasonal opening information', nextActionDate: '2026-10-02',
      tags: ['Park', 'Free', 'Accessible'], notes: 'Public-space directory record. No invoice required.', colour: '#50a1a9',
    },
    {
      id: 'org-011', name: 'The Ivy Collection', type: 'Food & drink', town: 'Stratford-upon-Avon',
      address: 'High Street, Stratford-upon-Avon', website: 'https://ivycollection.com',
      tier: 'Silver', status: 'Prospect', health: 'OK', owner: 'Vicki Zamudio', primaryContactId: 'con-011',
      renewalDate: '', membershipStart: '', annualValue: 571, listings: 0,
      lastActivity: '2026-09-19T08:50:00Z', nextAction: 'Follow up after opening week', nextActionDate: '2026-10-05',
      tags: ['Restaurant', 'New opening', 'Prospect'], notes: 'Opening late September. Introductory call completed.', colour: '#223f63',
    },
    {
      id: 'org-012', name: 'Prestige Chauffeurs', type: 'Supplier', town: 'Stratford-upon-Avon',
      address: 'Stratford-upon-Avon, Warwickshire', website: 'https://example.com',
      tier: 'Supplier', status: 'Prospect', health: 'OK', owner: 'Vicki Zamudio', primaryContactId: 'con-012',
      renewalDate: '', membershipStart: '', annualValue: 495, listings: 0,
      lastActivity: '2026-09-18T11:10:00Z', nextAction: 'Send supplier membership proposal', nextActionDate: '2026-09-21',
      tags: ['Supplier', 'Transport', 'Travel trade'], notes: 'Strong fit for new Supplier membership.', colour: '#775c9f',
    },
  ],
  contacts: [
    { id: 'con-001', organisationId: 'org-001', name: 'Laura Bennett', jobTitle: 'Partnerships Director', email: 'laura.bennett@example.com', phone: '01926 000 101', roles: ['Primary', 'Membership'], primary: true, portalAccess: true },
    { id: 'con-013', organisationId: 'org-001', name: 'Finance Team', jobTitle: 'Accounts', email: 'accounts.wc@example.com', phone: '01926 000 102', roles: ['Accounts'], portalAccess: false },
    { id: 'con-002', organisationId: 'org-002', name: 'James Hart', jobTitle: 'Head of Tourism', email: 'james.hart@example.com', phone: '01789 000 201', roles: ['Primary', 'Membership', 'Signatory'], primary: true, portalAccess: true },
    { id: 'con-014', organisationId: 'org-002', name: 'Emma Price', jobTitle: 'Campaigns Manager', email: 'emma.price@example.com', phone: '01789 000 202', roles: ['Marketing'], portalAccess: true },
    { id: 'con-003', organisationId: 'org-003', name: 'Sophie Martin', jobTitle: 'General Manager', email: 'sophie.martin@example.com', phone: '01789 000 301', roles: ['Primary', 'Signatory'], primary: true, portalAccess: true },
    { id: 'con-015', organisationId: 'org-003', name: 'Hotel Accounts', jobTitle: 'Finance Office', email: 'accounts.arden@example.com', phone: '01789 000 302', roles: ['Accounts'], portalAccess: false },
    { id: 'con-004', organisationId: 'org-004', name: 'Tom Walker', jobTitle: 'Visitor Experience Manager', email: 'tom.walker@example.com', phone: '01608 000 401', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-005', organisationId: 'org-005', name: 'Priya Shah', jobTitle: 'Marketing Manager', email: 'priya.shah@example.com', phone: '01926 000 501', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-006', organisationId: 'org-006', name: 'Rachel Moore', jobTitle: 'Communications Lead', email: 'rachel.moore@example.com', phone: '01926 000 601', roles: ['Primary', 'Marketing'], primary: true, portalAccess: true },
    { id: 'con-007', organisationId: 'org-007', name: 'Daniel King', jobTitle: 'General Manager', email: 'daniel.king@example.com', phone: '01926 000 701', roles: ['Primary', 'Membership', 'Accounts'], primary: true, portalAccess: true },
    { id: 'con-008', organisationId: 'org-008', name: 'Julie Stevens', jobTitle: 'Owner', email: 'julie.stevens@example.com', phone: '01926 000 801', roles: ['Primary', 'Signatory', 'Accounts'], primary: true, portalAccess: true },
    { id: 'con-009', organisationId: 'org-009', name: 'Martin Green', jobTitle: 'Trustee', email: 'martin.green@example.com', phone: '01926 000 901', roles: ['Primary', 'Membership'], primary: true, portalAccess: true },
    { id: 'con-010', organisationId: 'org-010', name: 'Parks Team', jobTitle: 'Place Operations', email: 'parks@example.com', phone: '01926 000 010', roles: ['Primary'], primary: true, portalAccess: false },
    { id: 'con-011', organisationId: 'org-011', name: 'Hannah Ellis', jobTitle: 'Launch Marketing Manager', email: 'hannah.ellis@example.com', phone: '020 7000 0111', roles: ['Primary', 'Marketing'], primary: true, portalAccess: false },
    { id: 'con-012', organisationId: 'org-012', name: 'Mark Collins', jobTitle: 'Managing Director', email: 'mark.collins@example.com', phone: '01789 000 121', roles: ['Primary', 'Signatory'], primary: true, portalAccess: false },
  ],
  benefits: [
    { id: 'ben-001', name: 'Enhanced website listing', kind: 'Ongoing', allowance: 1, category: 'Listing' },
    { id: 'ben-002', name: 'Social media features', kind: 'Allowance', allowance: 4, category: 'Marketing' },
    { id: 'ben-003', name: 'Dedicated member email', kind: 'Single use', allowance: 1, category: 'Marketing' },
    { id: 'ben-004', name: 'Campaign participation', kind: 'Allowance', allowance: 4, category: 'Marketing' },
    { id: 'ben-005', name: 'Tourism Forum places', kind: 'Allowance', allowance: 2, category: 'Networking' },
    { id: 'ben-006', name: 'Quarterly insight report', kind: 'Ongoing', allowance: 1, category: 'Insight' },
    { id: 'ben-007', name: 'Travel trade representation', kind: 'Ongoing', allowance: 1, category: 'Support' },
    { id: 'ben-008', name: 'Account planning session', kind: 'Allowance', allowance: 2, category: 'Support' },
  ],
  levels: [
    { id: 'level-001', name: 'Strategic', price: 3919, description: 'Highest-profile partnership with strategic input and year-round campaign support.', colour: '#6952d7', benefits: ['ben-001','ben-002','ben-003','ben-004','ben-005','ben-006','ben-007','ben-008'], listingAllowance: 5, imageAllowance: 30, videoAllowance: 5, active: true, members: 8 },
    { id: 'level-002', name: 'Gold', price: 1321, description: 'Enhanced visibility, campaigns and business development support.', colour: '#d39935', benefits: ['ben-001','ben-002','ben-004','ben-005','ben-006','ben-007'], listingAllowance: 3, imageAllowance: 20, videoAllowance: 3, active: true, members: 18 },
    { id: 'level-003', name: 'Silver', price: 571, description: 'A strong promotional package for growing visitor businesses.', colour: '#6c7a8d', benefits: ['ben-001','ben-002','ben-004','ben-005','ben-006'], listingAllowance: 2, imageAllowance: 12, videoAllowance: 1, active: true, members: 29 },
    { id: 'level-004', name: 'Bronze', price: 212, description: 'Core membership and an enhanced presence across the destination.', colour: '#a86b45', benefits: ['ben-001','ben-005','ben-006'], listingAllowance: 1, imageAllowance: 6, videoAllowance: 0, active: true, members: 44 },
    { id: 'level-005', name: 'Supplier', price: 495, description: 'For businesses supplying the visitor economy and destination partners.', colour: '#247a77', benefits: ['ben-001','ben-002','ben-005','ben-006','ben-007'], listingAllowance: 1, imageAllowance: 8, videoAllowance: 1, active: true, members: 0 },
    { id: 'level-006', name: 'Free Listing', price: 0, description: 'A basic directory entry for eligible visitor businesses.', colour: '#7b8798', benefits: [], listingAllowance: 1, imageAllowance: 1, videoAllowance: 0, active: true, members: 47 },
  ],
  benefitUsage: [
    { id: 'use-001', organisationId: 'org-001', benefitId: 'ben-002', used: 2, allowance: 4, note: 'Summer reels and family campaign', updatedAt: '2026-08-19' },
    { id: 'use-002', organisationId: 'org-001', benefitId: 'ben-003', used: 1, allowance: 1, note: 'May dedicated email', updatedAt: '2026-05-14' },
    { id: 'use-003', organisationId: 'org-001', benefitId: 'ben-004', used: 2, allowance: 4, updatedAt: '2026-08-30' },
    { id: 'use-004', organisationId: 'org-003', benefitId: 'ben-002', used: 1, allowance: 4, updatedAt: '2026-07-10' },
    { id: 'use-005', organisationId: 'org-003', benefitId: 'ben-004', used: 3, allowance: 4, updatedAt: '2026-09-01' },
    { id: 'use-006', organisationId: 'org-004', benefitId: 'ben-002', used: 3, allowance: 4, updatedAt: '2026-09-15' },
    { id: 'use-007', organisationId: 'org-005', benefitId: 'ben-004', used: 1, allowance: 4, updatedAt: '2026-07-28' },
  ],
  listings: [
    { id: 'list-001', organisationId: 'org-001', name: 'Warwick Castle', category: 'Castles & heritage', town: 'Warwick', status: 'Published', completeness: 96, views: 18420, enquiries: 814, shortDescription: 'Experience more than 1,100 years of history at Britain’s ultimate castle.', description: 'Epic adventures for all ages, from live shows and soaring birds of prey to beautifully restored interiors and historic grounds.', website: 'https://www.warwick-castle.com', bookingUrl: 'https://www.warwick-castle.com/tickets', phone: '01926 495421', email: 'info@example.com', openingHours: 'Open daily, times vary by season', facilities: ['Accessible toilets','Café','Parking','Family friendly','Dogs welcome outdoors'], lastUpdated: '2026-09-12', image: 'castle' },
    { id: 'list-002', organisationId: 'org-001', name: 'Knight’s Village', category: 'Accommodation', town: 'Warwick', status: 'Published', completeness: 88, views: 4930, enquiries: 230, shortDescription: 'Stay overnight in a medieval-themed lodge beside Warwick Castle.', description: 'Extend the adventure with an overnight stay in a themed lodge, complete with evening entertainment and breakfast.', website: 'https://www.warwick-castle.com/stay-overnight', bookingUrl: 'https://www.warwick-castle.com/stay-overnight', phone: '01926 495421', email: 'stays@example.com', openingHours: 'Seasonal opening', facilities: ['Parking','Restaurant','Family rooms','Wi-Fi'], lastUpdated: '2026-08-28', image: 'lodge' },
    { id: 'list-003', organisationId: 'org-002', name: 'Royal Shakespeare Theatre', category: 'Theatre', town: 'Stratford-upon-Avon', status: 'Published', completeness: 98, views: 15210, enquiries: 621, shortDescription: 'See Shakespeare’s work brought to life in his home town.', description: 'The iconic Royal Shakespeare Theatre sits beside the River Avon and presents world-class productions throughout the year.', website: 'https://www.rsc.org.uk', bookingUrl: 'https://www.rsc.org.uk/whats-on', phone: '01789 331111', email: 'tickets@example.com', openingHours: 'Box office open daily', facilities: ['Accessible seating','Restaurant','Bar','Hearing loop'], lastUpdated: '2026-09-18', image: 'theatre' },
    { id: 'list-004', organisationId: 'org-003', name: 'The Arden Hotel', category: 'Hotels', town: 'Stratford-upon-Avon', status: 'In review', completeness: 84, views: 3840, enquiries: 197, shortDescription: 'A sophisticated riverside hotel opposite the Royal Shakespeare Theatre.', description: 'Relax in a stylish town-centre hotel with award-winning dining, landscaped gardens and the theatres on the doorstep.', website: 'https://www.theardenhotelstratford.com', bookingUrl: 'https://www.theardenhotelstratford.com/book', phone: '01789 298682', email: 'stay@example.com', openingHours: 'Open all year', facilities: ['Parking','Restaurant','Accessible rooms','Wi-Fi','Dog friendly'], lastUpdated: '2026-09-19', image: 'hotel' },
    { id: 'list-005', organisationId: 'org-004', name: 'Cotswolds Distillery', category: 'Experiences', town: 'Shipston-on-Stour', status: 'Published', completeness: 91, views: 5620, enquiries: 308, shortDescription: 'Discover award-winning whisky and gin in the beautiful Cotswolds countryside.', description: 'Join a guided distillery tour, learn how spirits are made and enjoy a tutored tasting in a spectacular rural setting.', website: 'https://www.cotswoldsdistillery.com', bookingUrl: 'https://www.cotswoldsdistillery.com/pages/tours', phone: '01608 238533', email: 'tours@example.com', openingHours: 'Tours daily, advance booking recommended', facilities: ['Parking','Shop','Accessible tour','Café'], lastUpdated: '2026-09-15', image: 'distillery' },
    { id: 'list-006', organisationId: 'org-005', name: 'British Motor Museum', category: 'Museums', town: 'Gaydon', status: 'Changes requested', completeness: 72, views: 6890, enquiries: 350, shortDescription: 'Explore the world’s largest collection of historic British cars.', description: 'Discover more than 400 vehicles and the stories behind the people who designed, built and drove them.', website: 'https://www.britishmotormuseum.co.uk', bookingUrl: 'https://www.britishmotormuseum.co.uk/plan-your-visit', phone: '01926 895300', email: 'enquiries@example.com', openingHours: 'Daily 10am–5pm', facilities: ['Parking','Café','Accessible','Family activities'], lastUpdated: '2026-07-02', image: 'museum' },
    { id: 'list-007', organisationId: 'org-006', name: 'Compton Verney', category: 'Galleries', town: 'Warwick', status: 'Published', completeness: 94, views: 4770, enquiries: 214, shortDescription: 'An award-winning gallery set in 120 acres of Capability Brown parkland.', description: 'Enjoy nationally important art collections, ambitious exhibitions and beautiful landscaped parkland in one inspiring day out.', website: 'https://www.comptonverney.org.uk', bookingUrl: 'https://www.comptonverney.org.uk/tickets', phone: '01926 645500', email: 'info@example.com', openingHours: 'Tue–Sun, 10.30am–5pm', facilities: ['Parking','Café','Accessible','Families','Picnic area'], lastUpdated: '2026-09-01', image: 'gallery' },
    { id: 'list-008', organisationId: 'org-007', name: 'The Globe', category: 'Restaurants', town: 'Warwick', status: 'Draft', completeness: 58, views: 1040, enquiries: 38, shortDescription: 'A relaxed pub and dining room in the heart of Warwick.', description: 'Seasonal food, welcoming service and comfortable rooms just moments from Warwick’s historic Market Place.', website: 'https://www.theglobewarwick.co.uk', bookingUrl: '', phone: '01926 479100', email: 'hello@example.com', openingHours: 'Daily from 8am', facilities: ['Restaurant','Bar','Rooms','Wi-Fi'], lastUpdated: '2026-06-20', image: 'restaurant' },
    { id: 'list-009', organisationId: 'org-008', name: 'Kenilworth Books', category: 'Shopping', town: 'Kenilworth', status: 'Published', completeness: 82, views: 870, enquiries: 21, shortDescription: 'An award-winning independent bookshop in the heart of Kenilworth.', description: 'Browse a thoughtfully curated collection, meet visiting authors and discover local stories in a friendly independent shop.', website: 'https://www.kenilworthbooks.co.uk', bookingUrl: '', phone: '01926 855784', email: 'books@example.com', openingHours: 'Mon–Sat 9.30am–5pm', facilities: ['Town centre','Accessible entrance','Events'], lastUpdated: '2026-09-10', image: 'books' },
    { id: 'list-010', organisationId: 'org-009', name: 'Hill Close Gardens', category: 'Gardens', town: 'Warwick', status: 'Published', completeness: 79, views: 1260, enquiries: 44, shortDescription: 'Rare surviving Victorian gardens overlooking Warwick racecourse.', description: 'Step into a unique group of restored Victorian leisure gardens, complete with summerhouses, heritage fruit and seasonal planting.', website: 'https://www.hillclosegardens.com', bookingUrl: '', phone: '01926 493339', email: 'visit@example.com', openingHours: 'Open most weekdays and weekends; check before travel', facilities: ['Tea room','Accessible routes','Gardens'], lastUpdated: '2026-08-14', image: 'gardens' },
    { id: 'list-011', organisationId: 'org-010', name: 'Jephson Gardens', category: 'Parks & gardens', town: 'Royal Leamington Spa', status: 'Published', completeness: 68, views: 2380, enquiries: 60, shortDescription: 'Elegant riverside gardens at the heart of Royal Leamington Spa.', description: 'Stroll through beautifully maintained formal gardens, visit the glasshouse or simply pause beside the River Leam.', website: 'https://www.warwickdc.gov.uk', bookingUrl: '', phone: '', email: '', openingHours: 'Open daily', facilities: ['Free entry','Accessible paths','Café','Play area'], lastUpdated: '2026-07-30', image: 'park' },
  ],
  invoices: [
    { id: 'inv-001', number: 'SE-2026-1048', organisationId: 'org-001', description: 'Strategic membership 2026/27', issueDate: '2026-09-01', dueDate: '2026-09-30', subtotal: 3919, vat: 783.8, total: 4702.8, status: 'Sent', remindersPaused: false, reminderStep: 0, sentTo: 'accounts.wc@example.com' },
    { id: 'inv-002', number: 'SE-2026-1049', organisationId: 'org-002', description: 'Strategic membership 2026/27', issueDate: '2026-09-01', dueDate: '2026-09-30', subtotal: 3919, vat: 783.8, total: 4702.8, status: 'Paid', remindersPaused: false, reminderStep: 0, sentTo: 'james.hart@example.com', paidAt: '2026-09-12' },
    { id: 'inv-003', number: 'SE-2026-1018', organisationId: 'org-003', description: 'Gold membership renewal', issueDate: '2026-08-20', dueDate: '2026-09-19', subtotal: 1321, vat: 264.2, total: 1585.2, status: 'Overdue', remindersPaused: false, reminderStep: 1, sentTo: 'accounts.arden@example.com' },
    { id: 'inv-004', number: 'SE-2026-1055', organisationId: 'org-006', description: 'Silver membership 2026/27', issueDate: '2026-09-02', dueDate: '2026-10-02', subtotal: 571, vat: 114.2, total: 685.2, status: 'Sent', remindersPaused: false, reminderStep: 0, sentTo: 'rachel.moore@example.com' },
    { id: 'inv-005', number: 'SE-2026-0992', organisationId: 'org-007', description: 'Bronze membership renewal', issueDate: '2026-08-01', dueDate: '2026-08-31', subtotal: 212, vat: 42.4, total: 254.4, status: 'Overdue', remindersPaused: true, reminderStep: 2, sentTo: 'daniel.king@example.com' },
    { id: 'inv-006', number: 'SE-2026-1059', organisationId: 'org-008', description: 'Bronze membership 2026/27', issueDate: '2026-09-05', dueDate: '2026-10-05', subtotal: 212, vat: 42.4, total: 254.4, status: 'Draft', remindersPaused: false, reminderStep: 0, sentTo: 'julie.stevens@example.com' },
    { id: 'inv-007', number: 'SE-2026-1004', organisationId: 'org-009', description: 'Bronze membership renewal', issueDate: '2026-08-12', dueDate: '2026-09-11', subtotal: 212, vat: 42.4, total: 254.4, status: 'Overdue', remindersPaused: true, reminderStep: 1, sentTo: 'martin.green@example.com' },
    { id: 'inv-008', number: 'SE-2026-0975', organisationId: 'org-004', description: 'Gold membership 2026/27', issueDate: '2026-07-15', dueDate: '2026-08-14', subtotal: 1321, vat: 264.2, total: 1585.2, status: 'Paid', remindersPaused: false, reminderStep: 0, sentTo: 'tom.walker@example.com', paidAt: '2026-08-10' },
  ],
  agreements: [
    { id: 'agr-001', number: 'AGR-2026-088', organisationId: 'org-001', membershipLevel: 'Strategic', signatory: 'Laura Bennett', signatoryEmail: 'laura.bennett@example.com', status: 'Signed', createdAt: '2026-08-20', sentAt: '2026-08-22', signedAt: '2026-08-25', validUntil: '2027-08-31' },
    { id: 'agr-002', number: 'AGR-2026-091', organisationId: 'org-002', membershipLevel: 'Strategic', signatory: 'James Hart', signatoryEmail: 'james.hart@example.com', status: 'Signed', createdAt: '2026-08-24', sentAt: '2026-08-25', signedAt: '2026-08-29', validUntil: '2027-08-31' },
    { id: 'agr-003', number: 'AGR-2026-104', organisationId: 'org-003', membershipLevel: 'Gold', signatory: 'Sophie Martin', signatoryEmail: 'sophie.martin@example.com', status: 'Viewed', createdAt: '2026-09-10', sentAt: '2026-09-11', validUntil: '2026-10-01' },
    { id: 'agr-004', number: 'AGR-2026-108', organisationId: 'org-007', membershipLevel: 'Bronze', signatory: 'Daniel King', signatoryEmail: 'daniel.king@example.com', status: 'Sent', createdAt: '2026-09-14', sentAt: '2026-09-15', validUntil: '2026-10-15' },
    { id: 'agr-005', number: 'AGR-2026-112', organisationId: 'org-009', membershipLevel: 'Bronze', signatory: 'Martin Green', signatoryEmail: 'martin.green@example.com', status: 'Draft', createdAt: '2026-09-18', validUntil: '2026-10-20' },
  ],
  tasks: [
    { id: 'task-001', title: 'Call The Arden Hotel about renewal', organisationId: 'org-003', dueDate: '2026-09-21', dueTime: '10:00', priority: 'High', assignee: 'Vicki Zamudio', category: 'Renewal', completed: false },
    { id: 'task-002', title: 'Send supplier proposal to Prestige Chauffeurs', organisationId: 'org-012', dueDate: '2026-09-21', dueTime: '12:00', priority: 'High', assignee: 'Vicki Zamudio', category: 'Follow-up', completed: false },
    { id: 'task-003', title: 'Approve Compton Verney exhibition event', organisationId: 'org-006', dueDate: '2026-09-21', dueTime: '15:00', priority: 'Medium', assignee: 'Sian Cooper', category: 'Content', completed: false },
    { id: 'task-004', title: 'Review overdue invoices and reminder pauses', dueDate: '2026-09-22', priority: 'High', assignee: 'Darren Tosh', category: 'Finance', completed: false },
    { id: 'task-005', title: 'Confirm Christmas content with Warwick Castle', organisationId: 'org-001', dueDate: '2026-09-23', priority: 'Medium', assignee: 'Hannah Ward', category: 'Content', completed: false },
    { id: 'task-006', title: 'Invite Cotswolds Distillery to Tourism Forum', organisationId: 'org-004', dueDate: '2026-09-24', priority: 'Low', assignee: 'Sian Cooper', category: 'General', completed: false },
    { id: 'task-007', title: 'Update British Motor Museum accessibility copy', organisationId: 'org-005', dueDate: '2026-09-19', priority: 'Medium', assignee: 'Hannah Ward', category: 'Content', completed: false },
    { id: 'task-008', title: 'Record RSC membership payment', organisationId: 'org-002', dueDate: '2026-09-12', priority: 'High', assignee: 'Darren Tosh', category: 'Finance', completed: true },
  ],
  opportunities: [
    { id: 'opp-001', organisationName: 'The Ivy Collection', contactName: 'Hannah Ellis', stage: 'Qualified', proposedLevel: 'Silver', value: 571, probability: 35, source: 'New opening', nextAction: 'Follow up after opening week', nextActionDate: '2026-10-05', owner: 'Vicki Zamudio', daysInStage: 3 },
    { id: 'opp-002', organisationName: 'Prestige Chauffeurs', contactName: 'Mark Collins', stage: 'Proposal', proposedLevel: 'Supplier', value: 495, probability: 60, source: 'Referral', nextAction: 'Send membership proposal', nextActionDate: '2026-09-21', owner: 'Vicki Zamudio', daysInStage: 2 },
    { id: 'opp-003', organisationName: 'The Warwick Arms', contactName: 'Olivia Turner', stage: 'New lead', proposedLevel: 'Silver', value: 571, probability: 15, source: 'Website enquiry', nextAction: 'Initial discovery call', nextActionDate: '2026-09-23', owner: 'Vicki Zamudio', daysInStage: 1 },
    { id: 'opp-004', organisationName: 'Johnson’s Coaches', contactName: 'Peter Johnson', stage: 'Qualified', proposedLevel: 'Supplier', value: 495, probability: 40, source: 'Travel trade', nextAction: 'Discuss group market benefits', nextActionDate: '2026-09-25', owner: 'Vicki Zamudio', daysInStage: 8 },
    { id: 'opp-005', organisationName: 'No. 34 Garden & Grill', contactName: 'Amelia Reed', stage: 'Decision', proposedLevel: 'Bronze', value: 212, probability: 80, source: 'Team prospecting', nextAction: 'Confirm signatory details', nextActionDate: '2026-09-22', owner: 'Vicki Zamudio', daysInStage: 4 },
    { id: 'opp-006', organisationName: 'Vox City International', contactName: 'Alex Rossi', stage: 'Proposal', proposedLevel: 'Supplier', value: 495, probability: 55, source: 'WTM', nextAction: 'Share destination distribution plan', nextActionDate: '2026-09-28', owner: 'Vicki Zamudio', daysInStage: 11 },
    { id: 'opp-007', organisationName: 'Riverside Escapes', contactName: 'Nadia Ahmed', stage: 'New lead', proposedLevel: 'Gold', value: 1321, probability: 15, source: 'Member referral', nextAction: 'Research opening timeline', nextActionDate: '2026-09-24', owner: 'Vicki Zamudio', daysInStage: 2 },
    { id: 'opp-008', organisationName: 'Warwickshire Gin Co.', contactName: 'Ben Clarke', stage: 'Won', proposedLevel: 'Silver', value: 571, probability: 100, source: 'Tourism Forum', nextAction: 'Start onboarding', nextActionDate: '2026-09-21', owner: 'Vicki Zamudio', daysInStage: 1 },
  ],
  activities: [
    { id: 'act-001', organisationId: 'org-001', type: 'email', title: 'Campaign email sent', detail: 'Christmas campaign content request sent to Laura.', timestamp: '2026-09-19T14:24:00Z', user: 'Hannah Ward' },
    { id: 'act-002', organisationId: 'org-003', type: 'listing', title: 'Listing update submitted', detail: 'The Arden Hotel submitted new winter copy and images for review.', timestamp: '2026-09-19T09:30:00Z', user: 'Business portal' },
    { id: 'act-003', organisationId: 'org-012', type: 'note', title: 'Discovery call completed', detail: 'Good fit for Supplier membership; interested in travel trade introductions.', timestamp: '2026-09-18T11:10:00Z', user: 'Vicki Zamudio' },
    { id: 'act-004', organisationId: 'org-006', type: 'listing', title: 'Event submitted', detail: 'New autumn exhibition event is waiting for approval.', timestamp: '2026-09-18T10:05:00Z', user: 'Business portal' },
    { id: 'act-005', organisationId: 'org-002', type: 'invoice', title: 'Invoice marked paid', detail: 'SE-2026-1049 marked paid in full.', timestamp: '2026-09-12T16:40:00Z', user: 'Darren Tosh' },
    { id: 'act-006', organisationId: 'org-003', type: 'agreement', title: 'Agreement viewed', detail: 'Sophie Martin opened agreement AGR-2026-104.', timestamp: '2026-09-12T08:14:00Z', user: 'System' },
  ],
}

export const typeOptions = ['Accommodation', 'Attraction', 'Arts & culture', 'Food & drink', 'Retail', 'Outdoors', 'Supplier', 'Other']
export const townOptions = ['Stratford-upon-Avon', 'Warwick', 'Royal Leamington Spa', 'Kenilworth', 'Shipston-on-Stour', 'Gaydon', 'Other']
