import type { MemberValueEntry, MemberValueType, PlatformData } from './platformTypes'
import type { CRMData, Organisation } from './types'

export const memberValueTypes:MemberValueType[]=['Website listing exposure','Campaign participation','Newsletter feature','Social promotion','PR/media opportunity','Travel trade opportunity','Familiarisation visit','Business event lead','Events/networking','Training','Research/data','Member offer','Membership benefit used','Other']
export function membershipPeriod(org:Organisation,offset=0){
  const start=new Date(`${org.membershipStart}T12:00:00Z`),end=new Date(`${org.renewalDate}T12:00:00Z`)
  if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime()))return null
  start.setUTCFullYear(start.getUTCFullYear()+offset);end.setUTCFullYear(end.getUTCFullYear()+offset)
  return {start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}
}
export function inPeriod(date:string,period:{start:string;end:string}|null){return Boolean(date&&period&&date>=period.start&&date<period.end)}
export function valueType(entry:MemberValueEntry):MemberValueType{return entry.type??(entry.category==='Website'?'Website listing exposure':entry.category==='PR'?'PR/media opportunity':entry.category==='Travel trade'?'Travel trade opportunity':entry.category==='MICE'?'Business event lead':'Other')}
export function memberValueRows(crm:CRMData,platform:PlatformData):MemberValueEntry[]{
  const manual=platform.memberValue.map((entry)=>({...entry,type:valueType(entry),calculation:entry.calculation??'manual' as const,source:entry.source??(entry.opportunityId?'Opportunity':entry.campaignId?'Campaign':'Manual record')}))
  const linked=new Set(manual.filter((entry)=>entry.opportunityId).map((entry)=>`${entry.opportunityId}:${entry.organisationId}`))
  const linkedCampaigns=new Set(manual.filter((entry)=>entry.campaignId&&entry.type==='Campaign participation').map((entry)=>`${entry.campaignId}:${entry.organisationId}`))
  const linkedBenefits=new Set(manual.filter((entry)=>entry.benefitId).map((entry)=>`${entry.benefitId}:${entry.organisationId}`))
  const automatic:MemberValueEntry[]=[]
  const add=(entry:MemberValueEntry)=>{if(entry.date)automatic.push({...entry,calculation:'automatic'})}
  for(const use of crm.benefitUsage){if(use.used<=0||!use.updatedAt||linkedBenefits.has(`${use.benefitId}:${use.organisationId}`))continue;const benefit=crm.benefits.find((item)=>item.id===use.benefitId);if(!benefit)continue;add({id:`benefit-${use.id}`,organisationId:use.organisationId,benefitId:use.benefitId,date:use.updatedAt.slice(0,10),type:'Membership benefit used',category:'Engagement',activity:benefit.name,quantity:use.used,estimatedValue:0,source:'Membership benefit usage',evidence:`${use.used} of ${use.allowance} recorded as used; date is latest update, not each use date.`,notes:use.note})}
  for(const campaign of platform.campaigns){for(const organisationId of new Set([...campaign.organisationIds,...(campaign.partners??[]).filter((partner)=>['Confirmed','Active','Completed'].includes(partner.status)).map((partner)=>partner.organisationId)])){if(linkedCampaigns.has(`${campaign.id}:${organisationId}`))continue;add({id:`campaign-${campaign.id}-${organisationId}`,organisationId,campaignId:campaign.id,date:campaign.startDate,type:'Campaign participation',category:'Marketing',activity:campaign.name,quantity:1,estimatedValue:0,source:'Campaign participation',evidence:`Campaign ${campaign.name} (${campaign.status}); no monetary value inferred.`})}}
  for(const opportunity of platform.memberOpportunities){for(const application of opportunity.applications.filter((item)=>item.participated)){if(linked.has(`${opportunity.id}:${application.organisationId}`))continue;add({id:`opportunity-${opportunity.id}-${application.organisationId}`,organisationId:application.organisationId,opportunityId:opportunity.id,campaignId:opportunity.campaignId,date:opportunity.activityStartDate||application.updatedAt?.slice(0,10)||opportunity.closingDate,type:opportunity.type==='Familiarisation visit'?'Familiarisation visit':opportunity.type==='Training'?'Training':opportunity.type==='Travel trade activity'||opportunity.type==='Trade show'?'Travel trade opportunity':opportunity.type==='Business event lead'?'Business event lead':opportunity.type==='Press opportunity'||opportunity.type==='Influencer opportunity'?'PR/media opportunity':'Other',category:'Engagement',activity:opportunity.title,quantity:1,estimatedValue:0,source:'Opportunity participation',evidence:'Participation recorded; no monetary value inferred.',notes:application.outcome})}}
  for(const trip of platform.famTrips.filter((item)=>item.endDate<=new Date().toISOString().slice(0,10)&&Boolean(item.outcome?.trim()||item.feedback?.trim()))){for(const organisationId of trip.organisationIds){add({id:`fam-${trip.id}-${organisationId}`,organisationId,relatedId:trip.id,date:trip.endDate,type:'Familiarisation visit',category:'Travel trade',activity:trip.title,quantity:1,estimatedValue:0,source:'FAM trip',evidence:'Completed trip with recorded outcome; no monetary value inferred.',notes:trip.outcome||trip.feedback})}}
  for(const lead of platform.tradeLeads){for(const distribution of lead.distributions??[]){if(!distribution.sharedAt)continue;add({id:`trade-${lead.id}-${distribution.organisationId}`,organisationId:distribution.organisationId,relatedId:lead.id,date:distribution.sharedAt.slice(0,10),type:'Travel trade opportunity',category:'Travel trade',activity:lead.description,quantity:1,estimatedValue:0,source:'Travel trade lead',evidence:`Lead shared with member; response ${distribution.response}. No member revenue inferred.`})}}
  for(const enquiry of platform.businessEnquiries.filter((item)=>item.stage==='Won'&&item.winningVenueId)){const organisationId=crm.listings.find((item)=>item.id===enquiry.winningVenueId)?.organisationId;if(!organisationId)continue;add({id:`mice-${enquiry.id}-${organisationId}`,organisationId,relatedId:enquiry.id,date:enquiry.preferredDates.match(/\d{4}-\d{2}-\d{2}/)?.[0]??'',type:'Business event lead',category:'MICE',activity:enquiry.client,quantity:1,estimatedValue:0,source:'Business events enquiry',evidence:'Winning venue recorded; no attendee spend or economic value allocated to member.'})}
  for(const opportunity of platform.prOpportunities.filter((item)=>item.responseSent)){for(const organisationId of opportunity.organisationIds){add({id:`pr-${opportunity.id}-${organisationId}`,organisationId,relatedId:opportunity.id,date:opportunity.deadline,type:'PR/media opportunity',category:'PR',activity:opportunity.title,quantity:1,estimatedValue:0,source:'PR opportunity',evidence:opportunity.outcome||'Response sent; no media value inferred.'})}}
  for(const coverage of platform.mediaCoverage){for(const organisationId of coverage.organisationIds){add({id:`coverage-${coverage.id}-${organisationId}`,organisationId,relatedId:coverage.id,date:coverage.publicationDate,type:'PR/media opportunity',category:'PR',activity:coverage.title,quantity:1,estimatedValue:0,source:'Media coverage',evidence:coverage.url||coverage.outlet,notes:'Media exposure only; any estimated media value must be entered and evidenced separately.'})}}
  return [...manual,...automatic].sort((a,b)=>b.date.localeCompare(a.date))
}
export function valueTotals(rows:MemberValueEntry[]){return {estimated:rows.reduce((sum,item)=>sum+Math.max(0,item.estimatedValue||0),0),actual:rows.reduce((sum,item)=>sum+Math.max(0,item.actualValue||0),0),activities:rows.length}}
export function memberExposure(crm:CRMData,organisationId:string){const listings=crm.listings.filter((item)=>item.organisationId===organisationId);return {listings:listings.length,views:listings.reduce((sum,item)=>sum+(item.views||0),0),enquiries:listings.reduce((sum,item)=>sum+(item.enquiries||0),0)}}
