import type { PlatformData } from './platformTypes'

export const initialPlatformData:PlatformData={
  memberValue:[],
  resources:[
    {id:'resource-001',title:'VisitMade member brand toolkit',category:'Toolkit',description:'Logos, usage guidance and campaign-ready assets.',url:'#',membershipLevels:[],published:true,updatedAt:'2026-09-12'},
    {id:'resource-002',title:'Accessible visitor information guide',category:'Member guide',description:'Practical steps for clear and inclusive pre-arrival information.',url:'#',membershipLevels:['Tier 1','Tier 2','Tier 3','Tier 4'],published:true,updatedAt:'2026-09-05'},
  ],
  communicationTemplates:[
    {id:'template-001',name:'Membership renewal — 60 days',category:'Renewal reminder',subject:'Your {{organisation_name}} membership renews soon',previewText:'Your current membership and next steps.',body:'Hello {{first_name}},\n\nYour {{membership_level}} membership renews on {{renewal_date}}. We would be delighted to continue working with {{organisation_name}}.',senderName:'Membership team',updatedAt:'2026-09-10'},
    {id:'template-002',name:'Opportunity invitation',category:'Opportunity invitation',subject:'A new opportunity for {{organisation_name}}',previewText:'Apply through your member portal.',body:'Hello {{first_name}},\n\nA new member opportunity is now open. Sign in to your portal to review the details and apply.',senderName:'Destination team',updatedAt:'2026-09-15'},
    {id:'template-003',name:'Welcome to membership',category:'Welcome to membership',subject:'Welcome to membership, {{organisation_name}}',previewText:'Your membership starts here.',body:'# Welcome, {{first_name}}\n\nWe are delighted to welcome {{organisation_name}} as a member. Here are the first steps to get the most from your membership.',senderName:'Membership team',updatedAt:'2026-09-22'},
    {id:'template-004',name:'Invoice reminder',category:'Invoice reminder',subject:'A reminder about your membership invoice',previewText:'Your invoice and payment details.',body:'Hello {{first_name}},\n\nThis is a reminder that an invoice for {{organisation_name}} is due. Please contact us if you need another copy or would like to discuss payment.',senderName:'Membership team',updatedAt:'2026-09-22'},
    {id:'template-005',name:'Event invitation',category:'Event invitation',subject:'You are invited to a destination event',previewText:'Join the destination network.',body:'Hello {{first_name}},\n\nWe would be pleased to welcome you to our upcoming event. Follow the link below for details and registration.',senderName:'Destination team',updatedAt:'2026-09-22'},
    {id:'template-006',name:'Travel trade update',category:'Trade update',subject:'Latest travel trade updates',previewText:'New products and destination news.',body:'Hello {{first_name}},\n\nHere is the latest travel trade news from our destination, including new experiences and member products.',senderName:'Travel trade team',updatedAt:'2026-09-22'},
    {id:'template-007',name:'Destination newsletter',category:'Newsletter',subject:'News from our destination',previewText:'Stories, events and opportunities.',body:'# Destination news\n\nHello {{first_name}},\n\nHere is this month’s round-up from our destination.\n\n- New experiences\n- Events\n- Member news',senderName:'Destination team',updatedAt:'2026-09-22'},
  ],
  segments:[
    {id:'segment-001',name:'Tier 1 and Tier 2 accommodation members',description:'Higher-tier accommodation members for priority campaigns.',filters:[{field:'membership_level',operator:'is one of',value:'Tier 1, Tier 2'},{field:'organisation_type',operator:'equals',value:'Accommodation'}],dynamic:true,updatedAt:'2026-09-14'},
    {id:'segment-002',name:'Renewing in 60 days — needs attention',description:'Relationship follow-up for near-term renewals.',filters:[{field:'renewal_period',operator:'within',value:'60 days'},{field:'health',operator:'equals',value:'Needs attention'}],dynamic:true,updatedAt:'2026-09-18'},
  ],
  communications:[],
  communicationPreferences:[],
  automations:[],
  automationRuns:[],
  automationNotifications:[],
  campaigns:[
    {id:'campaign-001',name:'Write Your Own Christmas Story',owner:'Sam Taylor',status:'Active',startDate:'2026-11-09',endDate:'2027-01-01',objective:'Drive winter breaks and member referrals',audience:'UK families and couples',markets:['UK'],themes:['Christmas','Short breaks'],channels:['Meta','Google','PR','Email'],budget:12500,actualSpend:4820,organisationIds:['org-001','org-003','org-004'],listingIds:['list-001','list-004'],pageIds:[],impressions:284000,reach:176000,clicks:6420,conversions:318,referrals:1240},
    {id:'campaign-002',name:'Autumn in the Vale',owner:'Sam Taylor',status:'Completed',startDate:'2026-08-15',endDate:'2026-09-15',objective:'Extend the shoulder season',audience:'Culture-led couples',markets:['UK','Ireland'],themes:['Heritage','Food'],channels:['Email','PR','Organic social'],budget:6500,actualSpend:6120,organisationIds:['org-001','org-002'],listingIds:['list-001','list-003'],pageIds:[],impressions:198000,reach:121000,clicks:5210,conversions:246,referrals:892},
  ],
  memberOpportunities:[
    {id:'member-opp-001',title:'Christmas campaign partner feature',description:'A featured placement across the Christmas landing page and member newsletter.',category:'Campaign participation',eligibleLevels:['Tier 1','Tier 2','Tier 3'],capacity:8,price:250,closingDate:'2026-10-12',campaignId:'campaign-001',requirements:'Landscape image, 80-word copy and bookable winter offer.',status:'Open',applications:[{id:'application-001',organisationId:'org-003',contactId:'contact-003',response:'We would like to feature our two-night winter package.',listingId:'list-004',notes:'Images ready',status:'Applied',amount:250}]},
    {id:'member-opp-002',title:'WTM buyer meeting slots',description:'Join the destination delegation for pre-qualified buyer meetings.',category:'Trade show participation',eligibleLevels:['Tier 1','Tier 2'],capacity:6,price:400,closingDate:'2026-10-01',requirements:'Trade rates and product sheet.',status:'Open',applications:[]},
  ],
  travelBuyers:[
    {id:'buyer-001',company:'Britain Bound GmbH',contact:'Anna Weber',country:'Germany',market:'Germany',type:'Tour operator',sourceMarkets:['Germany','Austria'],segments:['Culture','Groups'],fitGroup:'Both',interests:['Heritage','Gardens'],relationshipStatus:'Active',priority:'High',lastContacted:'2026-09-09',nextAction:'Share group itinerary',owner:'Morgan Lee',notes:'Seeking commissionable group products.',tags:['Heritage','Groups']},
    {id:'buyer-002',company:'NorthStar Travel',contact:'Elena Rossi',country:'Italy',market:'Italy',type:'Wholesaler',sourceMarkets:['Italy'],segments:['FIT','Luxury'],fitGroup:'FIT',interests:['Food & drink','Boutique hotels'],relationshipStatus:'Developing',priority:'Medium',lastContacted:'2026-08-30',nextAction:'Meet at WTM',owner:'Morgan Lee',notes:'Interested in two-night add-ons.',tags:['WTM']},
  ],
  tradeLeads:[{id:'trade-lead-001',buyerId:'buyer-001',description:'Three-night heritage and gardens group programme',dates:'May–June 2027',partySize:36,markets:['Germany'],interests:['Heritage','Gardens'],organisationIds:['org-001','org-003'],estimatedValue:18500,stage:'Shared with members',owner:'Morgan Lee',nextAction:'Collect group rates by 30 September',outcome:''}],
  tradeShows:[{id:'show-001',name:'WTM London',location:'ExCeL London',startDate:'2026-11-03',endDate:'2026-11-05',cost:8200,attendees:['Morgan Lee','Alex Morgan'],organisationIds:['org-001','org-003'],appointments:18,qualifiedBuyers:11,leads:7,followUps:4,estimatedPipeline:62000,notes:'Prioritise Germany, Netherlands and domestic groups.'}],
  famTrips:[{id:'fam-001',title:'German heritage and gardens FAM',startDate:'2026-10-16',endDate:'2026-10-18',targetMarket:'Germany',buyerIds:['buyer-001'],organisationIds:['org-001','org-003','org-009'],listingIds:['list-001','list-004'],itinerary:'Day 1: castle welcome and riverside dinner. Day 2: gardens, gallery and hotel site visits. Day 3: market quarter and departures.',dietary:'One vegetarian participant',accessibility:'Step-free rooms and coach drop-off required',cost:3800,feedback:'',followUp:'Trade-ready itinerary and rates within seven days.'}],
  venueCapabilities:[{id:'venue-001',listingId:'list-004',maxDelegates:180,theatre:180,classroom:90,boardroom:28,banquet:140,reception:220,bedrooms:84,breakoutRooms:5,parking:true,accessibility:'Step-free main rooms and accessible bedrooms',catering:true,av:true,wifi:true,sustainability:'Green Tourism Silver'}],
  businessEnquiries:[{id:'mice-001',client:'Northbridge Association',organisation:'Northbridge Association',contact:'Priya Shah',eventType:'Annual conference',preferredDates:'12–14 March 2027',delegates:140,roomNights:220,bedrooms:80,requirements:'Plenary for 140, four breakouts and gala dinner',budget:48000,location:'Riverside preferred',source:'Website enquiry',economicValue:76000,stage:'Issued',owner:'Alex Morgan',nextAction:'Responses due 30 September',invitedVenueIds:['venue-001'],responses:[]}],
  mediaProfiles:[{id:'media-001',name:'Clara Hughes',outlet:'The Weekend Edit',type:'Journalist',country:'UK',topics:['UK breaks','Food','Heritage'],audience:240000,relationshipStatus:'Active',preference:'Email',lastContact:'2026-09-17',notes:'Planning winter short-break feature.',tags:['National media','Christmas']}],
  prOpportunities:[{id:'pr-opp-001',title:'Best UK Christmas towns',mediaProfileId:'media-001',publication:'The Weekend Edit',deadline:'2026-10-03',request:'Fresh festive experiences and high-resolution imagery.',organisationIds:['org-001','org-002','org-004'],responseSent:false,outcome:'',owner:'Sam Taylor'}],
  mediaCoverage:[{id:'coverage-001',outlet:'Vale & County',journalist:'Clara Hughes',title:'A weekend beside the Vale',publicationDate:'2026-08-29',url:'https://example.com/vale-weekend',mediaType:'Magazine',topics:['Heritage','Food'],organisationIds:['org-001','org-003'],audience:85000,sentiment:'Positive',estimatedValue:1200,notes:'Estimated value is indicative only.'}],
  surveys:[{id:'survey-001',title:'2026 member satisfaction survey',introduction:'Help us shape next year’s member programme.',status:'Open',openingDate:'2026-09-15',closingDate:'2026-10-14',anonymous:false,audience:'Active members',slug:'member-satisfaction-2026',thankYou:'Thank you. Your feedback will inform our 2027 programme.',questions:[{id:'q-001',label:'How likely are you to recommend membership?',type:'nps',required:true,options:[]},{id:'q-002',label:'Which support has been most valuable?',type:'multiple_choice',required:false,options:['Website promotion','Campaigns','Networking','Research','Travel trade']},{id:'q-003',label:'What should we improve?',type:'long_text',required:false,options:[]}] }],
  surveyResponses:[{id:'response-001',surveyId:'survey-001',organisationId:'org-001',contactId:'contact-001',submittedAt:'2026-09-20T10:15:00Z',answers:{'q-001':9,'q-002':['Website promotion','Campaigns'],'q-003':'More advance notice of campaign opportunities.'}}],
  healthIssues:[
    {id:'health-001',area:'Accessibility',severity:'High',title:'Missing alternative text',description:'One image in the image bank has no useful alternative text.',entityType:'Image',entityId:'image-003',route:'images',resolved:false,check:'Images with an empty alt field'},
    {id:'health-002',area:'SEO',severity:'Medium',title:'Meta description is too short',description:'The Plan your visit page description is under 70 characters.',entityType:'Page',entityId:'website-plan',route:'pages',resolved:false,check:'Meta description between 70 and 160 characters'},
    {id:'health-003',area:'Content',severity:'High',title:'Listing completeness below threshold',description:'The Lantern House Hotel listing is below the configured 70% threshold.',entityType:'Listing',entityId:'list-004',route:'listings',resolved:false,check:'Published and review-stage listings at least 70% complete'},
  ],
  engagementSettings:{weights:{contactRecency:20,benefitsUsed:15,portalActivity:10,listingCompleteness:15,campaignParticipation:15,websiteReferrals:10,invoices:15},riskDays:90,completenessThreshold:70},
}
