import type { PlatformData, TradeLead, TradeLeadStage, TravelBuyer } from './platformTypes'
import type { CRMData, Listing } from './types'

export const tradeTypes=['Tour operator','DMC','OTA','Wholesaler','Travel agent','Coach operator','Trade association','Other distribution partner'] as const
export const tradeLeadStages:TradeLeadStage[]=['New','Qualified','Shared','Responded','Converted','Lost']
export function normaliseBuyer(buyer:TravelBuyer):TravelBuyer{return {...buyer,sourceMarkets:buyer.sourceMarkets??(buyer.country?[buyer.country]:[]),segments:buyer.segments??[],interests:buyer.interests??[],productIds:buyer.productIds??[],pricePosition:buyer.pricePosition??'Mixed',tags:buyer.tags??[]}}
export function normaliseTradeLead(lead:TradeLead):TradeLead{return {...lead,stage:lead.stage==='Shared with members'?'Shared':lead.stage==='Proposal'?'Responded':lead.stage==='Won'&&lead.convertedAt&&lead.outcome.trim()?'Converted':lead.stage==='Won'?'Responded':lead.stage,distributions:lead.distributions??lead.organisationIds.map((organisationId)=>({organisationId,sharedAt:'',response:'Awaiting' as const,notes:''})),createdAt:lead.createdAt??'',actualValue:lead.actualValue??0}}
export function canSetTradeLeadStage(lead:TradeLead,next:TradeLeadStage){const current=normaliseTradeLead(lead).stage;if(current===next)return false;if(next==='Converted')return Boolean(lead.outcome.trim()&&lead.convertedAt&&lead.distributions?.some((item)=>item.sharedAt&&item.response!=='Awaiting'));if(next==='Shared')return Boolean(lead.distributions?.some((item)=>item.sharedAt));if(next==='Responded')return Boolean(lead.distributions?.some((item)=>item.sharedAt&&item.response!=='Awaiting'));return true}
const words=(value:string)=>value.toLowerCase().split(/[^a-z0-9]+/).filter((part)=>part.length>2)
export function matchTradeProducts(buyer:TravelBuyer,listings:Listing[]){const interests=normaliseBuyer(buyer).interests.map((item)=>item.toLowerCase());return listings.filter((item)=>item.status==='Published').map((listing)=>{const haystack=[listing.name,listing.category,listing.shortDescription,...listing.searchTags,...(listing.visitorTaxonomy??[])].join(' ').toLowerCase();const matches=interests.filter((interest)=>haystack.includes(interest)||words(interest).some((part)=>haystack.includes(part)));return {listing,matches,score:matches.length}}).filter((item)=>item.score>0).sort((a,b)=>b.score-a.score||a.listing.name.localeCompare(b.listing.name))}
export function tradeReport(crm:CRMData,platform:PlatformData){const buyers=platform.travelBuyers.map(normaliseBuyer),leads=platform.tradeLeads.map(normaliseTradeLead),meetings=platform.tradeActivities.filter((item)=>item.type==='Meeting'||item.type==='Sales call');const represented=new Set([...platform.tradeShows.flatMap((item)=>item.organisationIds),...platform.famTrips.flatMap((item)=>item.organisationIds),...leads.flatMap((item)=>item.organisationIds)]);const linkedContacts=(buyer:TravelBuyer)=>crm.contacts.filter((contact)=>contact.organisationId===buyer.organisationId);return {activeContacts:new Set(buyers.filter((item)=>item.relationshipStatus==='Active').flatMap((item)=>linkedContacts(item).map((contact)=>contact.id))).size,markets:[...new Set(buyers.flatMap((item)=>item.sourceMarkets))].map((market)=>({market,contacts:new Set(buyers.filter((item)=>item.sourceMarkets.includes(market)).flatMap((item)=>linkedContacts(item).map((contact)=>contact.id))).size,priorityEngagement:platform.tradeActivities.filter((item)=>buyers.some((buyer)=>buyer.id===item.buyerId&&buyer.sourceMarkets.includes(market)&&buyer.priority==='High')).length})),meetings:meetings.length,eventAppointments:platform.tradeShows.filter((item)=>item.endDate<=new Date().toISOString().slice(0,10)).reduce((sum,item)=>sum+item.appointments,0),leadsGenerated:leads.length,leadsShared:leads.filter((item)=>item.distributions!.some((distribution)=>distribution.sharedAt)&&['Shared','Responded','Converted'].includes(item.stage)).length,conversions:leads.filter((item)=>item.stage==='Converted'&&item.convertedAt&&item.outcome.trim()).length,famParticipation:platform.famTrips.filter((item)=>item.endDate<=new Date().toISOString().slice(0,10)&&Boolean(item.outcome?.trim()||item.feedback?.trim())).reduce((sum,item)=>sum+item.buyerIds.length,0),tradeEvents:platform.tradeShows.length,membersRepresented:represented.size}}
